getsentry/sentry-cli

- src/api.rs
- src/commands/releases.rs
Feel free to tell me this is terrible way to do this, but this seemed best I could come up with.
Example logs:
```
[INFO] sentry_cli::api request GET https://sentry.io/api/0/projects/burn-it-all-down/lol-gonna-get-burnt/releases/abc/
[INFO] sentry_cli::api using token authentication
[INFO] sentry_cli::api response: 200
[DEBUG] sentry_cli::api headers:
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 14 Nov 2016 23:39:20 GMT
Content-Type: application/json
Content-Length: 235
Connection: close
X-XSS-Protection: 1; mode=block
Content-Language: en
X-Content-Type-Options: nosniff
Vary: Accept-Language, Cookie
Allow: GET, PUT, DELETE, HEAD, OPTIONS
X-Frame-Options: deny
X-Served-By: web-7
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
[DEBUG] sentry_cli::api body: …
```
> Add debug logging to all responses for body/headers

- src/api.rs
- src/commands/releases.rs
- src/sourcemaputils.rs
This PR adds support for automatic emitting of sourcemap headers on upload.
This will help greatly with react-native and some other situations where the references contained in the minified files are wrong/misleading or absent.
> Add support for automatic sourcemap headers on upload

- bin/install-sentry-cli
- package.json
There were a few issues when trying to install sentry cli using the npm package on Windows
1. Running `./bin/install-sentry-cli` doesn't work so I changed to calling the node executable.
2. The output binary must have an extension otherwise it cannot be run so I added .exe on windows.
3. Use absolute paths with __dirname
4. Symlink sentry-cli.exe to sentry-cli on windows so the package.json bin works.
Tested that npm install runs successfully and the cli works on both mac and windows.
> Fix npm install on Windows

- src/api.rs
Currently when an upload does not create any new dsyms the
association will fail because no checksums are returned.  We now
change the logic so that we just pretend we did an HTTP request
that did not do any assocations.
This way callers do not need to special case.
Fixes #83
> Add support for empty dsym associations

- Cargo.lock
- Cargo.toml
- src/commands/difutil.rs
- src/commands/difutil_check.rs
- src/commands/difutil_find.rs
- src/commands/mod.rs
- src/commands/react_native.rs
- src/commands/upload_dsym.rs
- src/commands/upload_proguard.rs
- src/macros.rs
- src/utils/macho.rs
This can check debug info files and find the if needed
Running against dsym files:
Running against macho binaries without debug info:
Running against proguard files:
Scanning for specific files:
> Add Debug Info File Utilities

- src/commands/upload_dsym.rs
- src/utils/codepush.rs
- src/utils/fs.rs
- src/utils/mod.rs
- src/utils/releases.rs
- src/utils/xcode.rs
There are some issues with plist loading, in particular we do not have a
consistent path for it right now and variable expansion is kinda hacky.
This PR adds preprocessor support and go through consistent paths
for dealing with plist files.
> New PList Loading (Preprocessor Support)

- .vscode/tasks.json
- src/utils/codepush.rs
- src/utils/releases.rs
Releases with Codepush had a problem that they did not include the VersionCode in the release itself.
This PR fixes this by using already existing functionality from `infer_gradle_release_name`
> fix: Refactor and fix release name for android codepush command

- src/commands/send_event.rs
When using --extra x:y or -e x:y, no extra information was sent. but when using --tag a:b, the pair a:b was sent as a tag AND as an extra information.
> Fix typo leading to --extra param being ignored in send-event command

- .editorconfig
- .vscode/extensions.json
- Cargo.lock
- Cargo.toml
- docs/releases.rst
- src/commands/releases.rs
- src/commands/upload_dsym.rs
- src/errors.rs
- src/main.rs
This PR adds two flags to the releases:files:upload-sourcemaps command:
- `-i` or `--ignore`: Ignore a certain glob **relative to the cwd**.
This allows to, for instance, exclude `node_modules/`.
- `-I` or `--ignore-file`: Set a file containing one more more ignore
patterns **relative to the file's path**. Any file that is a valid
gitignore file can also be used here. This also includes overrides
in the form of `!pattern`. If the specified file is not found in the
cwd, sentry-cli traverses up the directory tree until it finds the
file.
Both options can be used together, with the patterns declared in `--ignore`
taking precedence. There is no default ignore file configured, but it would
be easy to default to something like `.sentryignore`.
Along with these changes, file extension matching …
> feat: Add --ignore and --ignore-file to releases files upload-sourcemaps

- src/commands/react_native_codepush.rs
This points out that bundle IDs are also necessary for other cases than just xcode builds on non macs.
> docs: Improve bundle ID docs for codepush.  Refs #143

- Cargo.lock
- Cargo.toml
- docs/index.rst
- docs/send-event.rst
- src/commands/send_event.rs
- src/event.rs
- src/main.rs
- src/utils/mod.rs
- src/utils/system.rs
This makes send-event actually useful.  In particular it supports basic
breadcrumbs by attaching log files and a few things more like user info
and basic device info as well as environment variables.
> feat: Improve send-event and add docs

- src/bashsupport.sh
- src/commands/bash_hook.rs
- src/commands/mod.rs
- src/commands/send_event.rs
- src/event.rs
This adds basic support for automatically capturing failures in bash scripts:
```
export SENTRY_DSN="..."
eval "$(sentry-cli bash-hook)"
```
What it does: it turns on `set -e` and captures failures on non 0 status codes and sends them to sentry.
(Known issue is that stderr and stdout can not interleave until buffer is full. This can only be fixed with emulating a tty which I am too lazy to do)
> feat: Added bash hook

- src/bashsupport.sh
First of all - thanks for adding this feature, it's useful being able to track errors in even more places than before!
One problem I'm having is that the logfile doesn't get parsed into breadcrumbs by my default locale:
```console
$ echo $LANG $LANGUAGE
en_GB.UTF-8 en_GB:en
$ awk '{ system(""); print strftime("%c"), "stdout:", $0; system(""); }'
hello world
Tue 28 Nov 2017 22:49:56 GMT stdout: hello world
```
And without:
```console
$ awk '{ system(""); print strftime("%c"), "stdout:", $0; system(""); }'
hello world
Tue Nov 28 22:56:19 2017 stdout: hello world
```
In the first case, no breadcrumbs get added to the sentry issue - as rust-anylog can't parse it. Other languages would probably face plenty of other problems, as the day and month names won't match either.
This PR should change …
> Switch strftime to common log format

- src/utils/sourcemaps.rs
This fixes #160
In the absence of this commit unless rewrite was passed the files were
never loaded so zero sourcemap references were resolved.
> fix: Flush sources before adding references

- CHANGELOG.md
- src/commands/react_native_codepush.rs
- src/utils/codepush.rs
- src/utils/cordova.rs
- src/utils/mod.rs
- src/utils/releases.rs
This pull request adds support for parsing version info from the
cordova config.  Separately we still need to drag out the version
code for when we upload artifacts later in a new command.
> feat: Added basic cordova release name support

- src/api.rs
The configuration option `http.verify_ssl` should disable verification of the SSL certificate. Right now, it only disables host name verification ([`CURLOPT_SSL_VERIFYHOST`](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html)) but it should also/instead disable certificate verification ([`CURLOPT_SSL_VERIFYPEER`](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html)).
I'd argue that we should **only** disable peer certificate validation and leave host validation in place to support self-signed certificates.
Fixes #178
> fix: Also disable SSL peer certificate verification with flag

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/utils/enc.rs
`uchardet` is [depreciated](https://github.com/emk/rust-uchardet/commit/22d9eb8f2e34e0018d18edf1ab7c2d4edff0e601#diff-04c6e90faac2675aa89e2176d2eec7d8R3) in favor of `chardet`.
With `uchardet` you always need to have `libuchardet-dev` installed, otherwise the compiled rust program will error.
> Replace uchardet with chardet

- src/event.rs
This sends a `curl` request before logging events. 
I have compiled and tested _(on linux)_:
This requires that user has `curl` installed. I know `libcurl` is a dependency that means `curl` should be available in bash right?
https://github.com/getsentry/sentry-cli/issues/191
> Get users IP address before sending event

- js/index.js
I think the linked issue has a fair point.
Do you see any reason not to do this, @kamilogorek @HazAT ?
Fixes getsentry/sentry-webpack-plugin#7
> fix(node): Inherit process environment

- src/utils/xcode.rs
Fixes #198 
Tested for the use case described in the issue. I have every reason to believe this doesn't affect the existing functionality since xcode copies all files to the build directory, but didn't test this. I believe this is the recommended way to look at `Info.plist` during build. See e.g. https://github.com/facebook/react-native/blob/master/scripts/react-native-xcode.sh#L99 (but they use another variable to get the directory 🤔).
Also never touched rust before so feel free to make it more rusty 😉
> Use Info.plist from build with xcode

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/bash_hook.rs
- src/commands/difutil.rs
- src/commands/difutil_check.rs
- src/commands/difutil_find.rs
- src/commands/difutil_uuid.rs
- src/commands/info.rs
- src/commands/issues.rs
- src/commands/login.rs
- src/commands/mod.rs
- src/commands/projects.rs
- src/commands/react_native.rs
- src/commands/react_native_codepush.rs
- src/commands/react_native_gradle.rs
- src/commands/react_native_xcode.rs
- src/commands/releases.rs
- src/commands/repos.rs
- src/commands/send_event.rs
- src/commands/uninstall.rs
- src/commands/update.rs
- src/commands/upload_breakpad.rs
- src/commands/upload_dsym.rs
- src/commands/upload_proguard.rs
- src/config.rs
- src/main.rs
- src/utils/system.rs
- src/utils/update.rs
- src/utils/xcode.rs
This refactors the internal config system to no longer require explicit
passing of the config.  This also changes the config object to no longer
expose the internal fields.
The hope is that with this we can restructure the config loading greatly
to then also affect how (and when) we load .env and other information.
This is the first work needed to get workspaces in place.
> ref: New Config System

- docs/configuration.rst
This should have been included in the related commit.
But I noticed when I started this feature my original issue was with the docs repo.
https://github.com/getsentry/sentry-docs/issues/191
So with this I can close that one.
> Add configuration values to the docs

- src/config.rs
- src/utils/mod.rs
- src/utils/rcfile.rs
This changes the config handling to always use both .properties and .ini
for all files.  We now try to read `.sentryclirc`, then `sentrycli.ini` and
then `sentry.properties`.  All files can support all formats (both java
properties and ini, we switch on demand).
This needs better tests.
> [WIP] feat: Use internal rcfile abstraction

- src/utils/codepush.rs
Also looks for codepush in `<cwd>/node_modules/.bin` and improves error messages if something goes wrong (using error chains 🎉 ):
- If codepush is missing entirely:
```
> Fetching latest code-push package info
error: Codepush not found. Is it installed and on the PATH?
```
- If codepush cannot be executed:
```
> Fetching latest code-push package info
error: Failed to run codepush
caused by: Permission denied (os error 13)
```
- If codepush encounters an error:
```
> Fetching latest code-push package info
error: Failed to get codepush deployments
caused by: You are not currently logged in. Run the 'code-push login' command to authenticate with the CodePush server.
```
Fixes #218
> ref(codepush): Improve codepush error messages

- README.md
- src/api.rs
- src/utils/ui.rs
Since rust 1.23.0 this is no longer necessary and there's not really a point in supporting old rust versions for `sentry-cli`.
> ref: Remove explicit AsciiExt usage

- README.md
- bin/install-sentry-cli
- docs/installation.rst
This should help people use their own download source for the npm version of sentry-cli. Still, we could consider uploading the binaries to a second CDN (maybe even the Raven one?) as a fallback.
See #207 and #196
> ref(npm): Update NPM download mirror and add docs

- Dockerfile
Installs the required `ca-certificates` package in our docker container, which was removed with the new musl builds. Previously, it was a transitive dependency of `libcurl`. 
Ref #223
> fix(docker): Include CA certificates in our docker container

- .editorconfig
- .eslintrc
- .prettierrc
- bin/sentry-cli
- js/__tests__/helper.test.js
- js/__tests__/index.test.js
- js/helper.js
- js/index.js
- js/releases/__tests__/index.test.js
- js/releases/index.js
- js/releases/options/uploadSourcemaps.js
- package.json
- scripts/install.js
- yarn.lock
Since we dropped support for Node 0.12 recently, we can now use a considerable subset of the ES6 spec. This PR updates the linter and formatter and applies the new style to all files.
Most of the changeset was generated automatically. See comments below for exceptions.
> ref(js): Use ES6 language level

- js/helper.js
- js/index.js
- js/releases/index.js
- js/releases/options/uploadSourcemaps.js
Adds JSDoc comments everywhere. Also renames some internal functions and variables.
I tried to make types as strict as possible everywhere, but was too lazy to type out the options for `releases.uploadSourceMaps`. Please let me know, if you'd prefer a `@typedef` instead.
Also note the comments below.
> docs(js): Add JSDoc comments to all methods

- scripts/install.js
Compensates the script was moved from `bin/` to `scripts/`. Therefore, the path of `sentry-cli.exe` has to go back to the `bin/` directory.
Fixes #238
> fix(npm): Fix install location on Windows

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/bash_hook.rs
- src/commands/info.rs
- src/commands/issues.rs
- src/commands/projects.rs
- src/commands/react_native_codepush.rs
- src/commands/react_native_gradle.rs
- src/commands/react_native_xcode.rs
- src/commands/releases.rs
- src/commands/repos.rs
- src/commands/send_event.rs
- src/commands/upload_breakpad.rs
- src/commands/upload_dbg.rs
- src/commands/upload_dsym.rs
- src/commands/upload_proguard.rs
- src/main.rs
- src/utils/dif_upload.rs
- src/utils/update.rs
This spawns up to `concurrency` threads that all upload. It also changes the API to have a TLS backing so each thread in the pool automatically gets its own API.
> feat: implement tls api and concurrent uploads

- js/__tests__/helper.test.js
- js/__tests__/index.test.js
- js/helper.js
> fix(js): Only use the mocked binary in tests

- js/helper.js
- js/index.js
Since I am very lazy, lets expose `execute` so we can call `upload-dif` for electron without writing a lot of code.
> feat: Expose execute to be able to run all commands

- scripts/install.js
The finish event informs listeners that `stream.end` has been called and all
data has been flushed to disk, however the file may still be open. In some cases
this may cause an ETXTBSY error to be thrown when the file is subsequently
executed to check its version.
> Wait for binary download file to close before resolving `downloadBinary`

- Cargo.lock
- Cargo.toml
- src/event.rs
Sentry requires timestamps for breadcrumsb or it will throw them
away.  This change makes up timestamps if we can't find any.
This also updates anylog which adds improved parsing so we should
be able to catch more timestamps.
> fix: Provide fallback timestamps for sentry

- Cargo.toml
This should link us statically against the crt.  See #267 for motivation
> build: statically link crt

- js/index.js
Simple fix to get `SentryCli.execute` method working. It's unlikely this ever worked as their is no `helper` property on the `SentryCli` class.
> Call execute on helper module

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/difutil.rs
- src/commands/difutil_check.rs
- src/commands/difutil_find.rs
- src/commands/difutil_id.rs
- src/commands/mod.rs
- src/commands/upload_dif.rs
- src/commands/upload_proguard.rs
- src/main.rs
- src/utils/args.rs
- src/utils/dif.rs
- src/utils/dif_upload.rs
This PR uses `ObjectId` for debug information files in place of the former `UUID`. Since serialization and deserialization are compatible with UUIDs for all cases where UUIDs are currently being used, this change should not break current API behavior.
The `difutil uuid` command has been renamed `difutil id`, but there is a hidden alias to `difutil uuid` to remain backward compatible.
Likewise, the `difutil find --uuid` option has been renamed `--id` with an alias `--uuid`.
From now on, all API responses returning a `DebugInfoFile` can contain a full object ID in the `debug_id` field in addition to a UUID in `uuid` now. These are `<...>/files/dsyms` (legacy archive upload), `<...>/files/difs/assemble` (new chunk assemble), and `<...>/files/dsyms/associate` (build association for dSYMs).
> ref: Use DebugId in place of UUIDs

- docs/releases.rst
the feature was replaced in commit cd4b058
following up on https://twitter.com/rodneyrehm/status/981201897880260608
> doc: remove obsolete "reference label"

- src/api.rs
Thanks to @jan-auer for fixing this.
> fix: Use full API URL for send-event action

- src/utils/releases.rs
This detects `HEROKU_SLUG_COMMIT` in `sentry-cli releases propose-version`,
as users would expect: https://docs.sentry.io/integrations/heroku/#configure-releases
Fixes #289
> feat(releases): Detect HEROKU_SLUG_COMMIT in propose-version

- src/utils/dif_upload.rs
Adds more logging to the dif upload and skips invalid ZIP files instead of failing the upload. Those files will still generate a debug log, but the directory iterator will continue to search the file system.
Fixes: https://github.com/getsentry/react-native-sentry/issues/420
> fix(upload): Skip invalid ZIP files

- src/utils/codepush.rs
The `sentry-cli react-native codepush ...` command currently uses the `codepush` CLI, which is deprecated in favor of the App Center CLI. This PR moves over to the new App Center CLI.
The main difference is the output of the CLIs. App Center's output for `deployment list ...` is something like this:
```json
[["Staging", "123abc"], ["Release", "456def"]]
```
So I mapped that data into the array of structs that the old CodePush CLI outputted.
I'm not super familiar with Rust so if my code is ugly or not idiomatic let me know and I'll try to clean it up.
Addresses #218
> Switch from codepush to App Center CLI

- src/commands/mod.rs
- src/commands/react_native.rs
- src/commands/react_native_appcenter.rs
- src/commands/upload_dsym.rs
- src/utils/appcenter.rs
- src/utils/mod.rs
Introduces the command `sentry-cli react-native appcenter` to manager codepush deployments with AppCenter CLI. It uses `appcenter codepush deployment history` to get a history of recent releases and fetches the package label from the last entry in the history.
This also deprecates the `sentry-cli react-native codepush` command and hides it in the command overview. However, it will still work as expected.
The appcenter command is a simple copy/paste from the old codepush command with changed strings and better help messages. Apart from `get_appcenter_package`, the code is identical.
Since we only require a deployment's package label, I've implemented a custom visitor that discards all other values returned by AppCenter CLI. This theoretically also makes us more robust against changes in …
> feat(react_native): Add a command for appcenter-cli

- src/api.rs
New error message:
```
$ sentry-cli releases list
error: project not found
caused by: project was renamed to 'rust'
Please update the project slug in your .sentryclirc or sentry.properties
```
> feat(api): Add a more descriptive project rename error message

- src/utils/appcenter.rs
- src/utils/codepush.rs
Fixes https://github.com/getsentry/sentry-cli/issues/319
> fix(react_native): Use cmd wrappers for appcenter on Windows

- docs/releases.rst
Add a link to more information about configuring a GitHub repository, which must be done before commits can be set up. 
Depends on [this](https://github.com/getsentry/sentry-docs/pull/272) pull request being merged first.
> Link to repository configuration

- src/api.rs
- src/commands/mod.rs
- src/utils/system.rs
This resolves
```
thread 'unnamed' panicked at 'Config not bound yet': libcore/option.rs:960
stack backtrace:
0:        0x10f037a6e - backtrace::backtrace::trace::h514d75a2770f3a20
1:        0x10f036c2c - <backtrace::capture::Backtrace as core::default::Default>::default::hd67a7078af019b2d
2:        0x10f036cad - backtrace::capture::Backtrace::new::h5baec8c77729d101
3:        0x10eb18021 - sentry_cli::utils::system::init_backtrace::{{closure}}::hb329223ccdd28415
4:        0x10f0e828e - std::panicking::rust_panic_with_hook::h81c4f3add25e6667
5:        0x10f0e800e - std::panicking::continue_panic_fmt::hfa057b7c1de88179
6:        0x10f0e7c98 - _rust_begin_unwind
7:        0x10f12bc71 - core::panicking::panic_fmt::h4c82aa4e615d52a2
8:        0x10f11dfb8 - …
```
> fix: Safely reset handles only if the config managed to initialize

- docs/send-event.rst
- src/bashsupport.sh
`strftime` is not available in some versions of `awk`. 
Let's use Perl whenever possible :)
Fixes #357.
> fix: Resolve awk compatibility issue in bash hooks

- src/api.rs
- src/commands/difutil.rs
- src/commands/difutil_find.rs
- src/commands/react_native.rs
- src/commands/releases.rs
- src/config.rs
- src/utils/appcenter.rs
- src/utils/args.rs
- src/utils/cordova.rs
- src/utils/crashreporting.rs
- src/utils/dif.rs
- src/utils/dif_upload.rs
- src/utils/releases.rs
- src/utils/sourcemaps.rs
- src/utils/xcode.rs
With this change, sentry-cli will always show errors for DIFs during the
assemble poll, even if all their chunks had already been uploaded. Previously,
such an upload would just show:
```
> Nothing to upload, all files are on the server
```
This made it hard to track and reproduce DIF upload and assembly errors.
> fix(dif_upload): Also show errors from previous uploads

- .dockerignore
- Dockerfile
- README.md
- docker-entrypoint.sh
To facilitate migration to the new entrypoint, let's allow both execution formats for now.
If "sentry-cli" is given as a first argument, show a scary warning.
> fix(docker): Add a warning about the new Docker entrypoint

- src/commands/releases.rs
- src/utils/vcs.rs
This adds the new `integrations:` variants for integrations when trying to
resolve commits for a configured repository.
This might still not work for the github enterprise provider, since there URLs
do not contain the GitHub hostname.
Also, this PR makes the `VcsUrl` struct private and adds a new internal `VcsProvider` enum to differenciate between the repo's provider and a GIT URL detected provider (which has no meaning, really).
Fixes #371
> fix(releases): Restore behavior of set-commits for new integrations

- src/commands/projects.rs
The project ID will be required for operating Relay in simple proxy mode
> feat: Show project ID in project listing

- src/commands/bash_hook.rs
- src/commands/send_event.rs
- src/utils/event.rs
Fixes https://github.com/getsentry/sentry-cli/issues/350
> ref: Always print the event ID in send-event

- .appveyor.yml
- .craft.yml
- .travis.yml
`|| [[ ! "$TRAVIS_BRANCH" =~ ^release/ ]]` will only fail the build if the command before it fails *and* it's a build on the release branch.
> ci: Update "gcs" target options, make zeus upload fail for releases

- js/__tests__/helper.test.js
- js/helper.js
- js/releases/options/uploadSourcemaps.js
- src/commands/releases.rs
- Write out warning if the option is not set in the js helper or not specified
as CLI flag.
- Make --rewrite and --no-rewrite actually mutually exclusive.
- If `rewrite` in the js helper is explicitly set to false, pass `--no-rewrite` to CLI
> fix: Prepare for making --rewrite the default

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/utils/dif_upload.rs
Allows to upload debug files via chunk upload even if they share their debug identifier. This completely disables DIF deduplication **and does not check features**. The Sentry server will ignore redundant files during the upload.
Requires https://github.com/getsentry/sentry/pull/10052
Requires https://github.com/getsentry/symbolic/pull/92
> feat(upload): Upload files despite shared Debug ID

- .craft.yml
- scripts/install.js
Why: NPM and Brew installation methods need to have access to the uploaded binaries.
> build: Execute "gcs" Craft target before others

- .appveyor.yml
- .travis.yml
- scripts/build-in-docker.sh
Ignore some CI failures (zeus operations, end-to-end test with sentry) when PR is created from a fork.
PR is intentionally created from a forked repo.
> ci: Fix PR builds from forks

- src/api.rs
- src/utils/dif_upload.rs
Will merge this after the corresponding Sentry PR.
Example:
```
$ sentry-cli upload-dif -t dsym electron-v3.0.10-darwin-x64-dsym/Electron\ Framework.framework.dSYM
WARN    2018-11-26 15:32:41.761835 +01:00 Skipping debug file since it exceeds 500.00MB: Contents/Resources/DWARF/Electron Framework (1.40GB)
> Found 0 debug information files
> No debug debug information files found
```
> feat(upload): Reject DIFs that are larger than allowed

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/config.rs
- src/constants.rs
- src/utils/http.rs
- src/utils/mod.rs
- src/utils/retry.rs
Adds `with_retry` method on `ApiRequest` that retries the request with exponential (but constrained) backoff.
> feat: Retry on upload-related operations (chunk-upload, assemble)

- src/utils/vcs.rs
Relax the VCS URL parsing so that on-premise hosting works better. Right now github enterprise and gitlab on-premise users have a really hard time using `set-commits --auto` as their repositories don't easily match up.
Because we can't rely on users having either `gitlab` or `github` in the domain name I've relaxed the URL comparisons to be host + name based instead of provider, type, name. This does open the window for users hosting multiple repository providers on the same domain to have incorrect results but I feel that should be a very rare deployment scenario.
Refs getsentry/sentry#11055
Refs APP-955
> fix(vcs) Relax VCS url comparisons

- src/commands/upload_dif.rs
- src/utils/dif_upload.rs
Previously even if the server encountered errors the dif upload command would
report 0 as success code.  This changes it to return 1 instead so that build
processes can respond to it.
> feat: Report non zero status for server side processing errors on dif upload

- src/commands/react_native_xcode.rs
- src/commands/upload_proguard.rs
- src/utils/dif_upload.rs
- src/utils/fs.rs
Fixes incomplete DIF and Proguard uploads on Windows. 
Instead of Cloning the file handle, we now return a mutable reference to the actual file, instead. Additionally, this flushes all data to **disk** before passing the path on to libcurl. Without that, libcurl on Windows seems to pick up an incomplete state of the file.
I yet have to find out why Sentry did not recognize the form field at all before.
> fix(upload): Flush archives before uploading them

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/bash_hook.rs
- src/commands/info.rs
- src/commands/issues.rs
- src/commands/login.rs
- src/commands/mod.rs
- src/commands/monitors.rs
- src/commands/projects.rs
- src/commands/react_native_appcenter.rs
- src/commands/react_native_codepush.rs
- src/commands/react_native_gradle.rs
- src/commands/react_native_xcode.rs
- src/commands/releases.rs
- src/commands/repos.rs
- src/commands/send_event.rs
- src/commands/upload_dif.rs
- src/commands/upload_proguard.rs
- src/config.rs
- src/utils/dif_upload.rs
- src/utils/system.rs
- src/utils/update.rs
- src/utils/xcode.rs
We're pretty confident that curl handles stashed into TLS causes all
kinds of mischief on thread shutdown which sometimes might even cause a
segfault.  This instead stashes the handles into an r2d2 connection
pool.
This PR also adds more retries for common network issues we encounter.
> feat: Use a connection pool for curl to avoid TLS and retry on more errors

- js/releases/index.js
We add default ignoring (via the `newOptions` object), but then don't use it (we pass the original `options` object instead). This fixes that.
> fix(JS wrapper): Pass correct options when uploading source maps

- src/utils/sourcemaps.rs
This adds a simple check for the number of files uploaded to a release. This does not prevent the upload of more than 20k files over multiple requests, but ensures that large releases are not even attempted.
> feat(releases): Protect against uploads of too many files

- js/helper.js
- js/index.js
- Add options to Sentry Constructor (JS part)
- Pass silent option to Sentry to disable stdout (need it for https://github.com/getsentry/sentry-webpack-plugin/issues/104)
> Add options to JS SentryCli Constructor

- src/utils/system.rs
- src/utils/vcs.rs
Parse SSH URLs from Azure DevOps that use the project name as the SSH username.
Fixes #11055
> fix(releases) Accept more Azure Devops URLs

- src/commands/difutil_find.rs
- src/commands/mod.rs
> chores: update to new clippy lint names

- src/api.rs
- src/commands/releases.rs
- src/utils/sourcemaps.rs
This adds basic parallel uploads for source maps.  This is not the final say in
upload performance but adds some basic improvements in the short term.
> feat(sourcemaps): Implement basic parallel upload for source maps

- Cargo.lock
- Cargo.toml
This points to the bugfix for the empty buffer causing a segfault
(https://github.com/alexcrichton/curl-rust/pull/270)
> feat: Update to git version of curl-rust that does not catch

- src/commands/react_native_appcenter.rs
- src/commands/react_native_codepush.rs
- src/commands/react_native_gradle.rs
- src/commands/react_native_xcode.rs
- src/commands/releases.rs
- src/utils/sourcemaps.rs
Adds `--wait` to all commands that upload sourcemaps. By default, users can upload even large bundles in a matter of seconds without waiting for the server to process them. With the optional flag, one can wait for release assembly, but that should not be necessary in most cases.
Example that uploads roughly 300 files to Sentry:
```
$ time sentry-cli releases files 8beb5e7294d1e2f0608d24783eb9dc78e1ecc670 upload-sourcemaps ~/Downloads/sentry/ram
> Analyzing 2 sources
> Adding source map references
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File processing complete
Source Map Upload Report
Source Maps
~/main.jsbundle.map
Indexed RAM Bundles (expanded)
~/main.jsbundle
0.47s user 0.09s system 16% cpu 3.345 total
```
> ref(sourcemaps): Add a command to skip waiting for assemble

- src/utils/sourcemaps.rs
This fixes a regression in #540 for sourcemap uploads with an absolute path in `--url-prefix`. Example:
```
$ sentry-cli releases files <release> upload-sourcemaps <path> --url-prefix /home/ubuntu/server
```
Fixes #543
> fix(sourcemap): Support absolute paths for sourcemaps

- src/commands/react_native_appcenter.rs
- src/utils/appcenter.rs
My app has `staging` and `production` environments. For each env, I have only 1 bundle name like `com.app.staging`, `com.app.production`. I integrate both CodePush and Sentry so I must upload bundle files to Sentry by manually. With your current cli, I have 2 options to set release version:
- Don't override `bundle-id` -> Sentry version: `com.app-1.0`
- Override `bundle-id` with `com.app.staging` -> Sentry version: `com.app.staging`
The problem is version number is not included in the 2nd option automatically. So I update code a little bit to resolve that problem. Also I add another parameter called `version-name` in case anyone want to override the value.
Please review and merge it if you think it's helpful.
Thanks!
> Add version name as parameter

- src/api.rs
Sanitize path arguments in chunk upload.
This has been theoretically broken since the introduction of chunk upload, but only surfaced when the sourcemap upload was redirected to the chunk upload endpoint.
Fixes #548
> fix(api): Sanitize path arguments for sourcemap upload

- src/utils/vcs.rs
We ran into issues when associating commits from git repositories with mixed uppercasing in their url.
> ensure is_matching_url and VcsUrl::parse is case insensitive

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/upload_dif.rs
- src/utils/dif_upload.rs
This implements the upload of PE and PDB files.
`sentry-cli` only attempts the upload if the `pdbs` capability is returned by the chunk upload endpoint. Otherwise, it silently skips PDBs like before.
If PDBs are selected for upload, `sentry-cli` **additionally** scans for PEs and remembers their age. Once all files have been compiled, the PDBs' age is fixed using the one from the PE. The PE files are only uploaded if they are selected and contain usable information (either a symbol table, or unwind info on x64 builds)
See https://github.com/getsentry/sentry/pull/13725
> feat(upload): Implement PDB and PE upload

- src/utils/sourcemaps.rs
The reason for the 20.000 files limit on the client was a protection against a badly
perfoming file deletion loop caused by `upload_files_parallel` which first fetches
all old release files through pagination.
The artifact bundle code does not do that so it seems sensible to relax this
restriction for new artifact bundle based uploads.
> feat: Relax the total limit of files in an artifact bundle

- src/api.rs
This solves the issue observed in the java frontend if embedded newlines are in the auth token: https://github.com/getsentry/sentry-java/issues/734
> feat: Remove embedded newlines in headers

- .craft.yml
Here we use a couple of new Craft features:
* `requireNames` will check that every pattern has a matching file present. This will help to avoid situations when Zeus doesn't know anything about Appveyor some builds (e.g. those that were not started yet) and reports build as green.
* `checksums` will compute and add file checksums to the release registry.
> build: Update Craft config (checksums, required files)

- src/utils/vcs.rs
This fixes comparison problems that are causing some azure repos to not be located by sentry-cli.
Fixes #550
> fix(releases) Normalize newer Azure urls to lower case

- src/commands/releases.rs
It was never intended to strip the path of uploaded files, only the references inside source maps rewrites.
linked: https://github.com/getsentry/sentry-docs/pull/1214
closes: https://github.com/getsentry/sentry-cli/issues/436
> docs: Update strip-prefix description

- Cargo.lock
- Cargo.toml
- src/commands/difutil_bundle_sources.rs
- src/utils/dif_upload.rs
This PR fixes the upload of source bundles using `upload-dif`. 
Also, the `bundle-sources` command now detects dSYM folders and puts the ZIP files next to that. Finally, the output of `bundle-sources` has been adapted so that it can be consumed by scripts more easily: It prints all written files on stdout, and everything else on stderr.
> fix(dif): Fix source bundle upload

- src/commands/releases.rs
(based on customer confusion)
Make it clear that any use of this option overwrites the defaults, so things like `.js` and `.map` need to be included explicitly.
> fix(releases): Clarify help text for `--ext` option

- .travis.yml
- src/utils/vcs.rs
A customer was experiencing an issue when trying to specify commits using an annotated tag. The `find_matching_rev` function was returning the SHA of the tag instead of getting the SHA of it's associated commit.
This PR fixes that, and adds two tests (one against a lightweight tag, and one against an annotated tag) to ensure it's correctness and keep it correct.
> fix(bug): Using annotated tags now returns the correct commit SHA

- src/bashsupport.sh
How to reproduce:
```
#!/bin/bash
set -E
eval "$(sentry-cli bash-hook)"
>&2 echo error
$(false)
echo no error
```
this gives:
```
error: Could not open logfile
caused by: No such file or directory (os error 2)
```
Actually i'm using this workaround:
```
eval "$(sentry-cli bash-hook | sed 's/: > "\$_SENTRY_LOG_FILE"//g' | sed 's/export SENTRY_LAST_EVENT/: > "\$_SENTRY_LOG_FILE"\n  export SENTRY_LAST_EVENT/g')"
```
> fix: log missing if errtrace is used

- src/commands/releases.rs
Fixes #587
`ignore::types::TypeBuilder` doesn't like dots in type names, and neither does it like underscores. We could either generate unique names, e.g. by enumerating the extensions, or simply replace all the dots out.
> fix(sourcemaps): Allow dots in extensions for upload

- js/releases/index.js
When calling `setCommits` in the release module, it validates the input to always contain the `repo` key. However, when using `auto`, this repo key is never used.
This PR fixes that.
Also see getsentry/sentry-webpack-plugin#156
> Fix for commit requirement when release flag is set to auto

- src/api.rs
- src/commands/upload_dif.rs
- src/utils/dif_upload.rs
- src/utils/sourcemaps.rs
Adds a new `--wait` flag to `upload-dif`. Without this flag, the DIF upload will finish as soon as files have been uploaded to Sentry and the CLI will no longer wait for assembly. The report will then show a `PENDING` state:
```
> Found 1 debug information file
> Prepared debug information file for upload
> Uploaded 1 missing debug information file
> File processing complete:
PENDING dd63acf2-cc84-3091-bc2b-d883f7809a20 (sentry-cli; x86_64 executable)
```
**This changes default behavior of `upload-dif`!** To get the old behavior, users now must specify `--wait`.
> ref(upload): Add an optional --wait flag for upload-dif

- src/api.rs
- src/commands/releases.rs
Before this patch, the release list command would not show the
project(s) associated to each release.
After this patch the "Projects" column show the all the release's
project slugs.
> release list: Show a column with each release project's slug.

- src/utils/vcs.rs
Git integration always provides regular `https://git.whatever.com/repo` url, and some people are using `git+ssh://` protocol locally, which doesn't match and prevents `set-commit --auto` from working.
> feat: Add support for git:// git+ssh:// and git+https?:// protocols

- src/commands/releases.rs
- src/config.rs
- src/utils/vcs.rs
Git is decentralised, so it's usual to have several remote
repositories. Origin is usually the default remote repository
but it's not mandatory.
Sentry-cli only allowed to use the remote repository "origin" when
working with commits during a release.
It is now possible to set the remote name in the configuration file
or as environment variable.
In ~/.sentryclirc: defaults.vcs_remote.
In env: SENTRY_VCS_REMOTE.
If not provided, defaults to "origin" so it's backward-compatible.
> feat: Allow setting of Git remote

- Cargo.lock
- Cargo.toml
- src/utils/sourcemaps.rs
When encountering hermes bytecode, the file is cleared and flagged as minified source, that way it will get a correct sourcemap reference. Other than that, the update to `sourcemap` will make sure that the rewritten sourcemap will keep the `x_facebook_sources` scopes.
> feat: Implement workarounds for dealing with hermes bytecode

- src/utils/dif_upload.rs
Fixes a regression in #624 which skipped all source files smaller than 1MB, instead of the ones larger than 1MB.
> fix(dif): Skip files larger than 1MB

- src/commands/react_native_xcode.rs
The default react-native-xcode.sh script invoked builds determines
whether $CONFIGURATION is a debug build or not by loosely matching on
*Debug*. See: https://github.com/facebook/react-native/blob/f19fb2454d164d88aad619fd992edeae51981096/scripts/react-native-xcode.sh#L33
Using a similar regex prevents build failures from occurring anytime a
build configuration has a name that contains but is not exactly "Debug".
This is useful for projects that utilize build configs for different
product flavors (e.g. Debug-dev, Debug-beta, Debug-prod).
> fix: react-native xcode uses regex to detect Debug builds

- js/helper.js
- js/index.js
Potential fix for https://github.com/getsentry/sentry-webpack-plugin/issues/175
Right now, providing a `configFile` to `SentryCli()` overrides the `process.env.SENTRY_PROPERTIES` on the entire process. This is problematic when multiple instances of `SentryCli` are used in the same Node process, and each uses a different `configFile` parameter.
One potential fix for this is to override `SENTRY_PROPERTIES` at the local execution level, rather that mutating the global `process.env` environment. I'm open to feedback, though!
> fix: Override local env.SENTRY_PROPERTIES rather than global process.env

- Cargo.lock
- Cargo.toml
Points to ref: https://github.com/getsentry/symbolic/commit/8f9a01756e48dcbba2e42917a064f495d74058b7
> deps: Bump symbolic to support GNU decompression changes

- .craft.yml
This is a follow-up to https://github.com/getsentry/homebrew-tools/pull/2.
> meta: Add Linux support to the Homebrew formula

- src/api.rs
- src/config.rs
- src/utils/chunks.rs
- src/utils/http.rs
Closes: https://github.com/getsentry/sentry-cli/issues/649
Closes: https://github.com/getsentry/sentry-cli/issues/651
Closes: https://github.com/getsentry/sentry-cli/issues/663
> fix: Make sure that requests are not authenticated twice and warn for relative urls

- src/utils/xcode.rs
Closes https://github.com/getsentry/sentry-cli/issues/278
ref: https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW154
ref: https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options
> feat: Add support for INFOPLIST_OTHER_PREPROCESSOR_FLAGS

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/bash_hook.rs
- src/commands/releases.rs
- src/commands/repos.rs
- src/utils/dif_upload.rs
- src/utils/sourcemaps.rs
- src/utils/update.rs
Symbolic `7.1.1` was released without git dependencies. Going forward, we can run regular releases of `symbolic` again and do not need to worry about git hashes.
Also fixes clippy lints for Rust 1.42.0.
> build: Move to released symbolic

- src/commands/react_native_appcenter.rs
- src/utils/appcenter.rs
Add `--release-name` as an optional argument to `react-native appcenter` to override the entire release name. This can be used to get around issues with the CodePush package label (used by the CLI by default) not being consistent between CodePush environments (#372 ) among other uses.
> Add an optional argument to override the entire release name for a CodePush release

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/config.rs
Encoding update is based on https://docs.rs/crate/percent-encoding/1.0.1/source/lib.rs
`uuid` cannot be updated due to `proguard` `symbolic-common` and `debugid` depending on version `0.7`.
> misc: Spring dependencies update

- js/index.js
- js/releases/index.js
Follow-up for a bug introduced by #667
Before, initializing `SentryCli()` would override `process.env.SENTRY_PROPERTIES`. This was problematic if multiple SentryCli instances were being used in the same Node process, in addition to mutating a global process object. To improve this, #667 moved the `SENTRY_PROPERTIES` override to a local env override that only applies to each individual `execute()` call.
However, this fix didn't take into account that the `Releases` class calls `helper.execute()` directly, rather than `SentryCli().execute()`. This leads the release commands to not know about the overridden configFile that they are expecting.
https://github.com/getsentry/sentry-cli/blob/6d9ba9f3e3f061839735e986839d8935672e6121/js/releases/index.js#L42
To resolve this, I've added a second …
> fix: Respect configFile for release commands

- js/__tests__/helper.test.js
- package.json
- yarn.lock
Fixes https://github.com/getsentry/sentry-cli/issues/695#issuecomment-604073843
Ref https://github.com/getsentry/sentry-cli/issues/698
> utils: Downgrade mkdirp as they drop support for node 8

- src/constants.rs
- src/utils/dif.rs
- src/utils/dif_upload.rs
The debug file upload skips all files without a debug id, since Sentry cannot handle them. This patch adds a message to difutil check so that it is easier to debug why the file is not being uploaded. 
We do not emit a warning, since it's quite common to point `sentry-cli` to directory that contain `.o` object files. Each of those would generate a warning during upload.
> fix(difutil): Mark files as unusable without id

- src/api.rs
Presumably this happens if someone has exactly a multiple of per-page files uploaded.
> fix: Do not error when offsetting too far on enumeration

- src/utils/args.rs
We should use https://docs.rs/clap/2.33.1/clap/struct.Arg.html#method.allow_hyphen_values but it's currently broken for positional arguments https://github.com/clap-rs/clap/issues/1437 https://github.com/clap-rs/clap/issues/1287
so we have to use https://docs.rs/clap/2.33.1/clap/enum.AppSettings.html#variant.AllowLeadingHyphen instead.
closes: https://github.com/getsentry/sentry-cli/issues/769
ref: https://github.com/getsentry/sentry-webpack-plugin/issues/197
> fix: Allow for release names with leading hyphen

- src/api.rs
- src/commands/releases.rs
- src/utils/vcs.rs
In this PR, we are moving the code in `set-manual-commits` into `set-commits`. When you run `set-commits --auto` if the user does not have a repo based integration, run the `set-manual-commits` code.
We have agreed to use `--local` optional flag to represent always using the local git tree to get the commits and to use `--initial-depth` as the optional flag for the number of commits for the initial release.
> feat: mv set-manual-commits into set-commits --auto

- Cargo.lock
- Cargo.toml
- package.json
- src/api.rs
- src/commands/releases.rs
- src/utils/args.rs
- src/utils/snapshots/sentry_cli__utils__vcs__generate_patch_default_twenty.snap
- src/utils/snapshots/sentry_cli__utils__vcs__generate_patch_set_base.snap
- src/utils/snapshots/sentry_cli__utils__vcs__generate_patch_set_previous_commit.snap
- src/utils/snapshots/sentry_cli__utils__vcs__get_commits_from_git.snap
- src/utils/vcs.rs
We want to enable users to send formatted commit metadata  through sentry-cli, even if they do not have a repo-based integration.
Currently, if you don’t have a repo based integration, you need to write your own script to send us commits for a release.
A lot of our customers write their own script for git. So, with this project, we’re hoping to reduce the amount of work a user needs to do to send us commits.
> feat: Upload formatted commit metadata from local git tree to Sentry for a release

- src/api.rs
- src/config.rs
We want to see how successful our pipelines are.
Our pipelines use `sentry-cli` to send release and commit information. We want to see how widely these pipelines are being used. So, we need to have some way of being able to distinguish when a release is created through a pipeline vs just via `sentry-cli`.
Currently, all `sentry-cli` requests are sent with a `sentry-cli` user agent. 
In this PR, we are allowing users to configure an environment variable for their pipeline that is then sent in through the user agent.
> feat: Add pipeline env variable option and include it in UA string

- src/utils/vcs.rs
Based on https://github.com/getsentry/sentry/blob/87a67caeebbadc1b2f40ab11fd99fe113feb7042/src/sentry/integrations/bitbucket_server/repository.py#L43 and https://github.com/getsentry/sentry/blob/87a67caeebbadc1b2f40ab11fd99fe113feb7042/tests/sentry/integrations/bitbucket_server/test_repository.py#L96
> fix: Parse BitBucket Server integration repo url correctly

- src/utils/vcs.rs
We want to silence the output of the setup for the snapshot tests for `set-commits --local`.
_Before_
_After
_
> fix: Silence the git output in tests

- src/api.rs
- src/commands/react_native_appcenter.rs
- src/commands/react_native_codepush.rs
- src/commands/react_native_gradle.rs
- src/commands/react_native_xcode.rs
- src/commands/releases.rs
- src/utils/file_search.rs
- src/utils/file_upload.rs
- src/utils/mod.rs
- src/utils/progress.rs
- src/utils/sourcemaps.rs
Summary of the changes:
- introduce batch upload for release files, which recursively walks directories in order to find all matching files (mimics behavior of sourcemap upload, with all the `ignore`, `ignore_file`, `extensions` flags)
- decouple source map processing from the upload step
- decouple release files searching and release files uploading into two separate things
- reuse file searching, processing and and uploading across both commands (sourcemaps and regular release files)
Closes: https://github.com/getsentry/sentry-cli/issues/704
> feat: Batch upload; Release file upload refactor;

- src/utils/releases.rs
I extended propose-release feature for CircleCI, make it look 'CIRCLE_SHA1` .
`CIRCLE_SHA1` is:
> The SHA1 hash of the last commit of the current build.
https://circleci.com/docs/2.0/env-vars/
>  add propose-release support for CircleCI

- src/commands/releases.rs
- src/config.rs
- src/utils/system.rs
Refer to https://github.com/getsentry/sentry-cli/issues/789
When an org has no integrations setup and runs `sentry-cli releases set-commits --auto`, it currently bails. The expected behaviour is to create a new repo (with Unknown Provider) in Sentry and upload the local git commit metadata.
> fix: Default to sending local commits if no repos linked

- src/commands/releases.rs
Fixes https://github.com/getsentry/sentry-cli/issues/806
If anything, it should be done in the Sentry, not the CLI.
> fix: Dont limit commits count for release updates

- azure-pipelines.yml
`macos-10.13` is already deprecated and removed from Azure, ~and I don't see a reason why not to use latest instead.~
> Bump macOS VM version on Azure Pipeline

- Cargo.lock
- Cargo.toml
This fixes a compilation error on the old version of symbolic on stable and nightly compilers.
Before:
```
Compiling symbolic-debuginfo v7.4.0
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'d` due to conflicting requirements
--> /home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.4.0/src/object.rs:348:23
|
348 |         Box::new(self.symbols())
|                       ^^^^^^^
|
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 347:5...
--> /home/svenstaro/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.4.0/src/object.rs:347:5
|
347 |     fn symbols(&self) -> DynIterator<'_, Symbol<'_>> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...so that …
```
> Upgrade symbolic to 7.5.0 to fix compilation errors

- scripts/install.js
This PR adds the possibility to download other architecture builds than x86_64 or i686.
os.arch returns the following possible values: 'arm', 'arm64', 'ia32', 'mips', 'mipsel', 'ppc', 'ppc64', 's390', 's390x', 'x32', and 'x64'. [https://nodejs.org/api/os.html#os_os_arch](Source)
With the current implementation, it is not possible to have it work with any other architecture, even when changing the CDN_URL value via env. variables as it always defaults to i686.
> Added possibility to support other arch than x86/x64

- src/utils/vcs.rs
This error is confusing to users, and required rewording for clarity.
> Fix double negative

- scripts/install.js
Fixes OS detection for 32 bits `ia32` (https://github.com/getsentry/sentry-cli/pull/811#discussion_r487866892)
> Fixed OS arch detection for IA32

- js/helper.js
- js/index.js
- js/releases/index.js
Expose common options available via environment variables as configurable parameters to the CLI constructor.
```javascript
new SentryCli(null, {
authToken: ...
});
```
> feat: Expose environment configuration in javascript

- js/helper.js
- js/releases/__tests__/index.test.js
- js/releases/index.js
- src/api.rs
- src/utils/dif_upload.rs
This PR enables setting multiple projects when creating a release with the JS wrapper for the CLI. It adds a new optional parameter to the `new` function called `options` which has a `projects` field which is an array of strings. Example:
```
cli.releases.new('my-version', { projects: ['proj-a', 'proj-b'] });
```
Becomes:
```
sentry-cli releases new -p proj-a -p proj-b my-version
```
CLI docs: https://docs.sentry.io/product/releases/#using-the-cli
I've also added the multiple project options for the `uploadSourceMaps` command as well. However, the underlying CLI cannot handle multiple options and will throw this error:
```
error: The argument '--project <PROJECT>' was provided more than once, but cannot be used multiple times
```
However, you can still provide a single option which is …
> feat(js): allows the user to specify multiple projects for a release

- src/bashsupport.sh
- src/commands/bash_hook.rs
When using `sentry-cli` through Docker, the bash hook does not work as:
1. The inferred path of `sentry-cli` becomes the path inside the container, and does not apply to the host
2. The files used for reporting live outside the container and they need to be mapped to the container when running it.
This patch chooses the more flexible `--cli` argument to solve both problems where one can do something like
```shell
docker run --rm getsentry/sentry-cli bash-hook --cli='docker run --rm -v "$_SENTRY_TRACEBACK_FILE:$SENTRY_TRACEBACK_FILE" -v "$_SENTRY_LOG_FILE:$_SENTRY_LOG_FILE" getsentry/sentry-cli
```
Now that's ugly as hell, yes and we may opt to have auto detection for running inside docker to handle this. The downside is then we'd not support any other container engine.
> feat(bash-hook): Add cli arg to override sentry-cli command

- src/commands/difutil_check.rs
Changes `difutil check` to output a list item per architecture contained in a fat file, instead of a flat list of individual duplicated information.
---
Before:
After:
> fix(difutil): Render variants as list in difutil check

- src/commands/bash_hook.rs
Fixes regression introduced in https://github.com/getsentry/sentry-cli/pull/852, where the path of `sentry-cli` would be interpolated as `_/usr/local/bin/sentry-cli_`.
> fix(bash-hook): Add missing underscores for template

- .craft.yml
- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- build.rs
- src/api.rs
Adds a release build for AArch64 as "arm64" and publishes an additional "universal" binary that hosts both architectures. The CLI and install script will prefer the platform build over the universal binary due to its doubled size.
> build: arm64 and universal binaries

- .github/workflows/release.yml
Same as getsentry/symbolicator#319.
> ci(release): Add support for release via getsentry/publish repo

- scripts/bump-version.sh
Drops support for releasing sentry-cli locally and replaces sed for
compatibility with Linux.
> fix(craft): Bump version for the release action

- .github/workflows/build.yml
The `lipo` tool required for linking a universal binary is available on older macOS versions. Since `macos-latest` is expected to be the most available macOS release, this should speed up the build. While releasing 1.61.0, we noticed that builds using `macos-11.0` queue up for quite some time.
> ci(gha): Build universal macOS binary on macos-latest

- .github/workflows/build.yml
With Rust 1.49.0, the `aarch64-apple-darwin` has hit the stable channel. This
allows us to revert binary builds to the stable channel.
> build: macOS arm64 on stable Rust

- .craft.yml
#878 missed the homebrew config, which was still installing single-arch binaries.
> fix(brew): Prefer universal binaries in homebrew

- src/api.rs
- src/constants.rs
- src/utils/dif_upload.rs
- src/utils/file_upload.rs
Under some conditions, chunk upload may not respond within a given time frame or
even time out completely. This leads sentry-cli to wait forever on a response
from Sentry.
This PR introduces an upper bound of 5 minutes. In chunk upload options, the
Sentry server can override this limit. It is not configurable on the CLI.
Fixes https://github.com/getsentry/sentry-cli/issues/891 in combination with https://github.com/getsentry/sentry/pull/23455
> fix(chunk_upload): Limit chunk upload waiting to 5 minutes

- src/api.rs
- src/config.rs
Fixes https://github.com/getsentry/sentry-cli/issues/472
ref https://docs.rs/curl/0.4.34/curl/easy/struct.Easy2.html#method.proxy
> fix: Use http_proxy config value directly in handler

- Cargo.lock
- Cargo.toml
Includes getsentry/symbolic#317, which fixes a bug that caused us to skip over MIPS debug information.
> fix: Detect debug information in MIPS binaries

- Cargo.lock
- Cargo.toml
- src/utils/update.rs
This can happen only in the case of a broken registry, but we shouldn't report false-positives to the end-user.
https://sentry.io/get-cli/ is also using registry, so someone would let us know that it's not working correctly anyway.
Fixes https://github.com/getsentry/sentry-cli/issues/898
> ref: is_outdated should not report when release contain older version

- .craft.yml
- .github/workflows/build.yml
- Dockerfile
- build.rs
- scripts/build-in-docker.sh
- src/commands/mod.rs
TODO:
We need to decide whether this should be called `aarch64`, which seems to be the output of `uname -m` by 64-bit applications, or `arm64`, which would also match macOS.
get-cli: https://github.com/getsentry/sentry-cli/pull/890
> build: ARM for Linux

- scripts/install.js
- When install v1.64.0 inside arm64 Linux Docker, we got 403 error.
```
Error: Unable to download sentry-cli binary from https://downloads.sentry-cdn.com/sentry-cli/1.63.0/sentry-cli-Linux-arm64.
Server returned 403: Forbidden.
```
- In #890 , arm64 renamed as aarch64, so we should update install/scripts as same.
- https://github.com/getsentry/sentry-cli/issues/913
> rename arm64 as aarch64

- bin/sentry-cli
It looks like `spawn` does not fail if the command does not exist, causing the script to return a 0 code although it didn't actually run.
We have had problems with the CLI not downloading on `npm install`, that caused the built React Native app to not contain the JS bundle.
Code uses synchronous/blocking flavor of `fs.exists()`: because we run in a separate process we can allow to block. I chose the exit code at random (as long as it is non-zero).
> Verify CLI installation before launching

- Cargo.lock
- Cargo.toml
Updates symbolic to include getsentry/symbolic#316, which fixes detection of
hidden symbols in Apple dSYMs for BitCode builds.
> build: Fix detection of hidden Swift symbols

- package.json
- scripts/install.js
- yarn.lock
Currently, the install script doesn't log anything other than a progress
bar, which shows only the filename. If the sentry-cli download fails,
there's no paper trail for the user to debug the issue. This fixes that
by adding some simple logging to show what the installer is doing.
> fix(install): add some npm logging to aid in troubleshooting

- src/utils/update.rs
> fix: Run update nagger only for versions lower than current one

- src/commands/send_event.rs
This adds acceptable logging levels in the output of `sentry-cli send-event --help`
Fixes #73
> feat: List logging levels on CLI output

- Cargo.lock
- Cargo.toml
Fixes has_line_info for certain mappings (warning: proguard mapping was ignored because it does not contain any line information.)
[More info](https://github.com/getsentry/rust-proguard/pull/21)
> fix: Update proguard version

- src/commands/react_native_xcode.rs
- src/utils/appcenter.rs
- src/utils/codepush.rs
- src/utils/xcode.rs
This should make the debugging way easier than cryptic `EOF while parsing a value at line 1 column 0` error message.
Fixes https://github.com/getsentry/sentry-cli/issues/901
Ref https://github.com/getsentry/sentry-cli/issues/797
Ref https://github.com/getsentry/sentry-cli/issues/567
Ref https://github.com/getsentry/sentry-cli/issues/564
Ref https://github.com/getsentry/sentry-cli/issues/374
Ref https://github.com/getsentry/sentry-cli/issues/137
Ref https://github.com/getsentry/sentry-cli/issues/94
> ref: Provide a helpful error messages for xcode/codepush/appcenter binary calls

- js/helper.js
Fixes https://github.com/getsentry/sentry-webpack-plugin/issues/187
> fix: Redirect outputs to /dev/null instead of filling up pipe buffers

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/upload_dif.rs
- src/utils/dif.rs
- src/utils/dif_upload.rs
Adds support for uploading BCSymbolMaps and their associated PList
files.
----
Related PRs:
https://github.com/getsentry/sentry/pull/25712
https://github.com/getsentry/symbolic/pull/373
https://github.com/getsentry/symbolicator/pull/414
> feat(upload_dif): Support BCSymbolMap uploading

- src/commands/releases.rs
- src/utils/snapshots/sentry_cli__utils__vcs__generate_patch_ignore_missing.snap
- src/utils/vcs.rs
We _could_ go with the more complex route of fetching all N releases and use their previous commits one by one, until we find a working one, however:
- it wouldn't cut it for fresh projects (a single release which has squashed commit)
- it would require us to fetch all that data from the API, as `get_previous_release_with_commits` that we use currently, is a very specific `/previous-with-commits` endpoint that returns only a single release
This change will allow us to be more "generous" for malformed repositories and it will still work fine with `initial-depth` option. Tested it on production already and works as expected.
Fixes: https://github.com/getsentry/sentry-cli/issues/792
Fixes https://github.com/getsentry/sentry-cli/issues/945
Fixes: …
> feat: Allow for ignoring missing commits in set-commit

- src/commands/releases.rs
Without the `long` modifier, it's treated as a positional argument, which is then taken over by `version` match.
Explicitly adding `long` key to the argument makes it a flag, which can be used on any position.
Fixes https://github.com/getsentry/sentry-cli/issues/964
> fix: Change ignore-missing to flag with 'long' modifier

- src/api.rs
- src/config.rs
closes: https://github.com/getsentry/sentry-cli/issues/308
As discussed in the issue above, there are use cases where being able to attach a custom header to every request is useful.
This introduces support for a new env var `CUSTOM_HEADER`, as well as a config block under defaults called `custom_header`, that allows you to specify a string that is added directly as a request header to all outgoing requests. Note that this is not a key/value pair - this expects the format `key: value` as a string.
**Testing:**
Uploading a lib somewhere where we don't have permission:
```
$ /docker-entrypoint.sh --log-level DEBUG upload-dif -o 31 -p my_proj /usr/lib/libssl.so.1.1
...
DEBUG   2021-06-02 18:17:31.558003600 +00:00 > GET /api/0/organizations/31/chunk-upload/ HTTP/1.1
DEBUG   2021-06-02 …
```
> support custom request header from env / config

- src/commands/releases.rs
Otherwise, there is no easy way to ignore this error and allow the CI to progress when triggering the same `set-commit` command with no new commits. Simple `|| true` is not sufficient, as it will silent all possible valid errors.
Q: Not sure if we should call it `--allow-empty` or `--ignore-empty` to be consistent with newly added `ignore-missing` flag.
> feat: Add --ignore-empty flag that will not bail command when no patchset is created

- js/index.d.ts
- js/releases/index.js
Fixes https://github.com/getsentry/sentry-cli/pull/984
`started` and `finished` can use either timestamp in seconds or ISO 8601 format, so it _can_ accept a string.
> ref: Provide JSDocs for TS typings and change started/finished to number|string

- js/index.d.ts
- js/releases/__tests__/index.test.js
- js/releases/index.js
- src/api.rs
- src/commands/difutil_find.rs
- src/commands/login.rs
- src/commands/releases.rs
- src/commands/uninstall.rs
- src/utils/dif_upload.rs
- src/utils/file_search.rs
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
- src/utils/system.rs
- src/utils/vcs.rs
- src/utils/xcode.rs
In the `@sentry/cli` code, the `Releases. uploadSourceMaps()` method iterates over the `include` array in `options` and calls a separate upload command for each entry (see [here](https://github.com/getsentry/sentry-cli/blob/dfc380c8b4f95be5853b2b4f0abd2d0fbf1319ce/js/releases/index.js?plain=1#L167-L177)).
This means that it's possible (at least in theory) to have different options for each `include` entry. This PR brings that theory to fruition.
The motivation here is to make it easier to include multiple sets of files in the upload.
Suppose you have the following file structure:
```
animals
aardvarks
facts
photos
research
google.txt
wikipedia.txt
...
baboons
...
coatis
...
...
zebras
gifs
dramatic_zebra.gif
stampede.gif
...
sightings
sounds
```
and you want to upload only the files in …
> feat(js): Add ability for `include` in JS sourcemap upload options to be an object

- scripts/install.js
Fixes https://github.com/getsentry/sentry-cli/issues/1007
> fix: Dont render progress bar when content length is missing

- Cargo.lock
- Cargo.toml
This version has support to detect Mach-O compact unwind and will thus avoid reporting false negatives (dylibs that seemingly lack unwind info).
> ref: Update symbolic to 8.3.0

- src/commands/upload_dif.rs
Hidden until we make it usable, see: https://github.com/getsentry/sentry-cli/issues/1009#issuecomment-911516666
Closes https://github.com/getsentry/sentry-cli/issues/1009
> ref: Hide upload-symbol-maps flag for upload-dif command

- scripts/install.js
When arch="arm", set archString="armv7", so that the install script will download the correct binary.
Closes #1023
> fix: Set archString to "armv7" when arch="arm"

- CHANGELOG.md
- src/utils/dif_upload.rs
`.aar` are just zips: https://developer.android.com/studio/projects/android-library#aar-contents
This change will allow us running `dif-upload` pointing to a `.aar` without having to unzip it.
```
➜  sentry-cli git:(feat/android-aar-difupload) ✗ cargo build
Compiling sentry-cli v1.68.0 (/Users/bruno/git/sentry-cli)
Finished dev [unoptimized + debuginfo] target(s) in 7.97s
➜  sentry-cli git:(feat/android-aar-difupload) ✗ ./target/debug/sentry-cli  upload-dif -o sentry-sdks -p sentry-unity ~/git/sentry-unity/package-dev/Plugins/Android/Sentry/sentry-android-ndk-release.aar
WARN    2021-09-24 15:20:03.937446 -04:00 Skipping BCSymbolMap with invalid filename: jni/
WARN    2021-09-24 15:20:03.938707 -04:00 Skipping BCSymbolMap with invalid filename: jni/arm64-v8a/
WARN    2021-09-24 …
```
> feat(difupload): Look into aar files as zip

- CHANGELOG.md
- src/utils/dif_upload.rs
Reverts getsentry/sentry-cli#1031
Due to: https://github.com/getsentry/sentry-cli/pull/1031#discussion_r716638761
We decided not to peek into .aar for symbols.
> Revert "feat(difupload): Look into aar files as zip"

- Cargo.lock
- Cargo.toml
Includes a hotfix for https://github.com/getsentry/sentry-dart/issues/591, by making parsing more lenient and resilient against malformed ELFs.
> ref: Update symbolic 8.3.1

- .github/workflows/danger.yml
- dangerfile.js
Does what it says on the tin. Borrows most of its code from symbolicator's implementation with any irrelevant bits removed.
> Gently poke PR authors to include an entry in the changelog

- src/commands/uninstall.rs
- src/utils/update.rs
This adds example commands to the error messages we show when trying to update or uninstall a `sentry-cli` instance installed as part of `@sentry/cli`, both for convenience and as a hint that the npm package may be installed globally.
> fix(js): Add example commands to errors re: updating/uninstalling `@sentry/cli`

- js/helper.js
- js/index.d.ts
Follow up to https://github.com/getsentry/sentry-cli/pull/970. This option has proved quite useful so far, and it would be great to have support in the JS wrapper of the CLI as well.
PTAL @kamilogorek @jan-auer @mitsuhiko
> CUSTOM_HEADER support for JS wrapper

- src/utils/dif_upload.rs
- src/utils/xcode.rs
In the latest version of clippy, `large_enum_variant` is turned on by default, which fails with the current implementation.
Two removed fields from `XcodeProjectInfo` were unused.
> ref: Box ParseDif::Object value to prevent large enum variant

- src/config.rs
- src/constants.rs
- src/utils/dif_upload.rs
Currently, we have a hard limit of 1MB, and any source files larger than this are filtered out and not bundled, effectively making them unavailable for processing on the Sentry side. We do this by default, as most files larger than that default limit, are useless for our needs, and shouldn't be uploaded. There are however cases, where it might be desirable.
By adding `max_item_size` option under `dsym` group to `ini` config file, and using it inside the bundling function, we allow end-user to override this limit and bundle larger files.
I specifically didn't do that through additional argument, as it'd then have to be passed down the calls, which is kinda obscure and inefficient. Additionally, this is rather not a common use case, thus not exposing it widely is preferable. 
Resolves …
> feat: Allow for configuring max item size for dif bundles

- Cargo.toml
- src/commands/mod.rs
- src/commands/react_native_xcode.rs
- src/commands/upload_dif.rs
- src/utils/system.rs
- src/utils/xcode.rs
In macOS 10.13, changes to Objective-C runtime forbid calling ObjC code before and after forking the process. If we want to do that, and we need to, due to moving `sentry-cli` process to the background during XCode artifacts upload, we need to perform all those calls *after* we daemonize ourselves. This forces us to not spawn any processes, nor call any ObjC-compiled code (like cURL) before we actually get to that branch.
The thing that's detaching us is `MayDetach::wrap` via `MayDetach::may_detach` function.
If we call any cURL code or spawn any process before-hand, it will result in the background process crashing with:
```
objc[80549]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[80549]: +[__NSCFConstantString initialize] …
```
> fix: Prevent daemonize mode from crashing upload process

- package.json
- yarn.lock
`node-fetch@3.1.1` has an important security patch, that has just been ported to `2.6.7`, so we can use it without bumping the major version just yet. 
Closes https://github.com/getsentry/sentry-cli/pull/1105
> deps: Bump node-fetch and regenerate yarn.lock

- src/api.rs
- src/commands/releases.rs
Previously we fetched a list of files and iterated over them for a one-by-one removal.
We do however have an endpoint that allows for bulk removal, which we can use in our `--all` flag case.
> feat: Remove all release files instantaneously with --all flag

- src/utils/appcenter.rs
Not only bundle ID is required, but version name too.
Context: https://github.com/getsentry/sentry-cli/issues/554#issuecomment-1027936082
> Update log message when bundle ID is missing

- scripts/install.js
Closes #1121 by automatically quieting the progress bar if a CI environment is detected.
This saves end users from needing to set another env var when `CI: true` is already very widely implemented. GitHub, GitLab, CircleCI, Jenkins, Netlify, and others all set this by default.
> install: Silence progress bar in CI environments

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
See https://github.com/getsentry/symbolic/releases/tag/8.6.1 for fixes
> build: Update symbolic to 8.6.1

- src/utils/update.rs
- src/utils/xcode.rs
There are scenarios like the one lined below, where `xcodeproj` directories does not contain all the required files for `xcodebuild` to give us a proper data. In that case, instead of panicking, we can bail out with a warning, and let the command proceed, as it's possible to do that without associating dSYMs just fine - https://github.com/getsentry/sentry-cli/blob/765f26ac55987c6ceeeae5fdc2e6befbc2abc7ea/src/commands/upload_dif.rs#L302-L329
Fixes https://github.com/getsentry/sentry-cli/issues/1126
> ref: Dont panic on malformed xcodeproj directories

- package.json
- scripts/install.js
- yarn.lock
Keep in mind that it will still error if installed version won’t match the one required by the `package.json`, and we should not change that.
Closes https://github.com/getsentry/sentry-cli/issues/835
Note: I'll update docs with all the new `SENTRYCLI_` options soon.
> feat: Allow for using local binary through SENTRYCLI_USE_LOCAL env

- scripts/install.js
To make it consistent with other `SENTRYCLI_` flags.
> install: Rename flag to SENTRYCLI_NO_PROGRESS_BAR

- Cargo.lock
- Cargo.toml
Closes https://github.com/getsentry/sentry-cli/issues/1068
Ref https://github.com/rust-lang/git2-rs/pull/791
Ref https://github.com/rust-lang/git2-rs/commit/c55bd6dbdba52f90788150180ef124ef6c90daa6
> deps: Update git2 crate to 0.14.1 to support custom git extensions

- .github/workflows/ci.yml
- src/utils/vcs.rs
This change allows us to remove `fetch-depth` from the CI, as the tests are now fully isolated.
> ref: Rework find_matching_rev tests to not use our real repo history

- src/api.rs
- src/commands/releases.rs
- tests/commands/releases_info.rs
Closes https://github.com/getsentry/sentry-cli/issues/954
Note: these tests will be redone using snapshot testing, so its fine if they are like this right now.
> feat: Add show-projects and show-commits flags to 'releases info' command

- package.json
Instead of relying on some random `node`, which is decided by the `npm` on runtime (eg. `npm` adds everything from `node_modules/.bin` to `$PATH` for its lifecycle-scripts), let `#!/usr/bin/env node` from scripts itself decide. `./install/script.js` has all `-x` chmod flags set correctly, so it won't be a problem executing it.
> ref: Dont run install script using node binary

- src/commands/issues.rs
- src/commands/react_native_appcenter.rs
- src/commands/react_native_codepush.rs
- src/commands/react_native_gradle.rs
- src/commands/react_native_xcode.rs
- src/commands/releases.rs
- src/commands/upload_dif.rs
- src/commands/upload_dsym.rs
- src/commands/upload_proguard.rs
- src/utils/args.rs
`.global` is only propagating down, not up the command structure, so it will work for us perfectly.
Fixes https://github.com/getsentry/sentry-cli/issues/179
Fixed issue with multiple `project` flags from https://github.com/getsentry/sentry-cli/pull/1152/
> ref: Make org and project flags position independent

- CHANGELOG.md
Our release process had a hiccup due to github being down + me needing to release `1.74.2` patch to fix a breaking issue.
> misc: Update missing 1.74.1 changelog

- .eslintrc
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .prettierrc
- bin/sentry-cli
- js/__tests__/helper.test.js
- js/helper.js
- js/releases/__tests__/index.test.js
- js/releases/index.js
- package.json
- scripts/install.js
- yarn.lock
Minor and non-important changes were removed from the list below.
Related Rust code: https://github.com/getsentry/sentry-cli/pull/1172
Improvements:
- Remove `SENTRY_NO_PROGRESS_BAR` flag in favor of `SENTRYCLI_NO_PROGRESS_BAR` _(breaking)_
- Drop support for Node v10 and older and modernize JS codebase _(breaking)_
> sentry-cli v2 RC [js-part]

- .github/workflows/ci.yml
- src/commands/releases/archive.rs
- src/commands/releases/delete.rs
- src/commands/releases/finalize.rs
- src/commands/releases/info.rs
- src/commands/releases/mod.rs
- src/commands/releases/new.rs
- src/commands/releases/restore.rs
- src/commands/releases/set_commits.rs
- src/utils/args.rs
- tests/integration/_cases/releases/releases-new-help.trycmd
- tests/integration/_cases/releases/releases-new-with-project-hyphen.trycmd
- tests/integration/_cases/releases/releases-new-with-project.trycmd
- tests/integration/releases/new.rs
Moves `allow_hyphen_values` from the argument to the command itself. This makes it understand that `-p` is indeed a short flag and not a release name.
Added appropriate tests to cover this case.
Fixes https://github.com/getsentry/sentry-cli/issues/1186
> fix: Allow hyphenated release names with any flags position

- CHANGELOG.md
- src/commands/debug_files/check.rs
- src/commands/debug_files/upload.rs
- src/commands/mod.rs
- src/commands/releases/list.rs
- src/commands/releases/new.rs
- src/commands/releases/set_commits.rs
- src/commands/sourcemaps/upload.rs
- src/commands/upload_dsym.rs
- tests/integration/_cases/upload_dsym/upload_dsym-help.trycmd
- tests/integration/upload_dsym.rs
Fixes https://github.com/getsentry/sentry-fastlane-plugin/pull/119
Fixes https://github.com/getsentry/sentry-cli/issues/1190
Fixes https://github.com/getsentry/sentry-cli/issues/1188#issuecomment-1096806402
> ref: Restore and hide legacy aliases from 1.x for backward compatibility

- scripts/install.js
We can do that, as according to https://github.com/node-fetch/node-fetch/blob/main/docs/ERROR-HANDLING.md
> All operational errors other than aborted requests are rejected with a FetchError.
And because we don't have abort logic, we don't need to handle that.
> fix: Remove fetch.FetchError usage in favor of catch-all clause

- tests/integration/_cases/debug_files/debug_files-help.trycmd
- tests/integration/_cases/debug_files/debug_files-no-subcommand.trycmd
- tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
- tests/integration/_cases/deploys/deploys-help.trycmd
- tests/integration/_cases/deploys/deploys-no-subcommand.trycmd
- tests/integration/_cases/info/info-help.trycmd
- tests/integration/_cases/login/login-help.trycmd
- tests/integration/_cases/releases/releases-help.trycmd
- tests/integration/_cases/releases/releases-new-help.trycmd
- tests/integration/_cases/releases/releases-no-subcommand.trycmd
- tests/integration/_cases/send_event/send_event-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-no-subcommand.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-resolve-help.trycmd
- tests/integration/_cases/uninstall/uninstall-help.trycmd
- tests/integration/_cases/update/update-help.trycmd
- tests/integration/_cases/upload_dif/upload_dif-help.trycmd
- tests/integration/_cases/upload_dsym/upload_dsym-help.trycmd
- tests/integration/_cases/upload_proguard/upload_proguard-help.trycmd
Use
> [EXE] as part of the line: On Windows, matches .exe, ignored otherwise
instead of
> [..] as part of a line: match any characters. This is equivalent of [^\n]*?.
https://docs.rs/trycmd/latest/trycmd/index.html
> ref: Use more concrete [EXE] matcher from trycmd

- package.json
- scripts/install.js
- yarn.lock
We don't use anything from v3, to be honest, and v2 will have all the necessary fixes anyway:
> Critical bug fixes will continue to be published for v2. – https://github.com/node-fetch/node-fetch
Fixes https://github.com/getsentry/sentry-cli/issues/1204
> ref: Use node-fetch@v2 for the simplicity sake

- js/helper.js
`eval` usage is a workaround for `@vercel/nft` detecting the binary itself as the hard dependency and effectively always including it in the bundle, which is not what we want.
ref: https://github.com/getsentry/sentry-javascript/issues/3865
ref: https://github.com/vercel/nft/issues/203
> ref: Prevent @vercel/nft and similar tools from including binary file in their bundles

- README.md
ref: https://github.com/getsentry/sentry-docs/pull/4991
> docs(cli): Sync get-cli readme with our docs; add version specifier

- src/utils/dif_upload.rs
Looks like 'no-zips' option is broken.
Actually we need it due to a bug with pwd protected zips (https://github.com/getsentry/sentry-cli/issues/1238)
> fix: fixing 'no-zips' option.

- src/commands/sourcemaps/explain.rs
- tests/integration/_cases/sourcemaps/sourcemaps-explain-already-mapped.trycmd
When stacktrace frame is incorrectly marked as `inApp`, but it comes from the place that we cannot map (eg. built-in language SDK itself), then `print_mapped_frame` would fail, as despite being processed, this frame has no `context_line` that we can display.
This change filters through mapped frames and uses the first one that can be correctly printed.
> fix: Use first frame that has context-line in explain

- Cargo.lock
- Cargo.toml
- src/utils/fs.rs
This addresses GH-1250 -- it replaces the `Drop` implementation of `TempFile` with one that uses `FILE_FLAG_DELETE_ON_CLOSE` to defer deletion until the last handle is closed on Windows.
This also adds some error logging when `TempFile`'s `drop` fails -- not sure if that's appropriate? It'll help catch issues like this.
> Increase TempFile robustness on Windows

- src/commands/releases/archive.rs
- src/commands/releases/finalize.rs
- src/commands/releases/new.rs
- src/commands/releases/restore.rs
- src/commands/releases/set_commits.rs
- src/utils/sourcemaps.rs
- tests/integration/_cases/releases/releases-finalize-dates.trycmd
- tests/integration/_cases/releases/releases-finalize-hyphen.trycmd
- tests/integration/_cases/releases/releases-finalize.trycmd
- tests/integration/_cases/releases/releases-new-existing.trycmd
- tests/integration/_cases/releases/releases-new-finalize.trycmd
- tests/integration/_cases/releases/releases-new-hyphen.trycmd
- tests/integration/_cases/releases/releases-new-url.trycmd
- tests/integration/_cases/releases/releases-new-with-project-hyphen.trycmd
- tests/integration/_cases/releases/releases-new-with-project.trycmd
- tests/integration/_cases/releases/releases-new.trycmd
Because last "word" is always the value itself, it can be confusing whether dot is the part of user-provided value or not. Especially in paths/urls.
> ref: Remove confusing ending dots from command logs

- Cargo.lock
- Cargo.toml
- src/commands/bash_hook.rs
- src/utils/dif_upload.rs
- src/utils/fs.rs
Except `clap` and `indicatif`, because reasons.
(`clap` has breaking changes, don't want to spend time on them now, `indicatif` has an unidentified bug we cannot solve, see comment in `Cargo.toml`).
Major bumps of:
- `open`
- `proguard`
- `symbolic`
- `uuid`
> deps: Update all Rust dependencies

- js/index.d.ts
Hello!
It seems that the `dist` is wrongly placed at main settings, while (according to [this sourcecode](https://github.com/getsentry/sentry-cli/blob/master/js/releases/options/uploadSourcemaps.js#L10)) it need to be placed in source maps settings (_passing dist option to new SentryCli(path, opts) doesnt do anything, while passing it to uploadSourceMaps works_).
This PR moves `dist` from `SentryCliOptions` to `SentryCliUploadSourceMapsOptions`
> fix: move dist option to SentryCliUploadSourceMapsOptions

- src/commands/files/upload.rs
- src/commands/sourcemaps/upload.rs
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-upload-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-skip-already-uploaded.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-successfully-upload-file.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload.trycmd
- tests/integration/sourcemaps/mod.rs
- tests/integration/sourcemaps/upload.rs
This change will make `sentry-cli` skip the upload of files that are already present for the given release.
It's using `sha1` checksum for comparison, as we already have this data for every file that was uploaded to our servers.
When skipped, an appropriate message is added to the upload report.
The same behavior already exists for all other debug files formats.
> feat: Use checksum to dedupe uploaded release artifacts

- .github/workflows/build.yml
When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
> ci: Disable rustup self-update

- src/commands/upload_proguard.rs
- tests/integration/_cases/upload_proguard/upload_proguard-help.trycmd
I think easlier is not a common English word. Fixed it by replacing it with easily and added a missing comma.
> ref: Fix typo in upload_proguard

- src/commands/react_native/appcenter.rs
**Before:**
```
> Fetching latest AppCenter deployment info
> Processing react-native AppCenter sourcemaps
error: No such file or directory (os error 2)
```
**After:**
```
> Fetching latest AppCenter deployment info
> Processing react-native AppCenter sourcemaps
error: Failed processing path: "./src/missing_dir"
caused by: No such file or directory (os error 2)
```
Fixes https://github.com/getsentry/sentry-cli/issues/1286
> ref: Print better error when processing appcenter paths

- package.json
- src/commands/releases.rs
- src/utils/formatting.rs
- yarn.lock
Should fix a vulnerability mentioned in https://github.com/getsentry/sentry-javascript/issues/5415 and #1079 in v1 of the CLI
CI seems happy and building/installing works locally for me. Feel free to close if this PR seems like a bad idea.
Changes in `releases.rs` and `formatting.rs` were purely made to make the linter happy
> chore: Add resolution to bump ansi-regex to version ^3.0.1

- CHANGELOG.md
`1.x` changelogs need to be included on master as well, see https://github.com/getsentry/sentry-cli/pull/1289
> misc: 1.74.5 changelog

- src/commands/sourcemaps/explain.rs
- tests/integration/_cases/sourcemaps/sourcemaps-explain-frame-malformed-abspath.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-frame-no-extension.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-select-frame-out-of-range.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-select-frame.trycmd
- tests/integration/_responses/sourcemaps/get-event-select-frame.json
- tests/integration/sourcemaps/explain.rs
This allows us to select other frames that might be for some reason not resolved. It's 0-indexed.
```terminal
sentry-cli sourcemaps explain <id> --frame 2
```
> feat: Allow for selecting frame in sourcemaps explain

- src/utils/dif_upload.rs
This will produce the warning below:
```
WARN    2022-08-04 12:32:50.920489 +02:00 Source exceded maximum item size limit (116303). /Applications/Xcode.app/usr/include/c++/v1/chrono
WARN    2022-08-04 12:32:50.961811 +02:00 Source exceded maximum item size limit (103509). /Applications/Xcode.app/usr/include/c++/v1/atomic
WARN    2022-08-04 12:32:50.980145 +02:00 Source exceded maximum item size limit (157727). /Applications/Xcode.app/usr/include/c++/v1/type_traits
WARN    2022-08-04 12:32:51.003650 +02:00 Source exceded maximum item size limit (169525). /Applications/Xcode.app/usr/include/c++/v1/string
WARN    2022-08-04 12:32:51.056923 +02:00 Source exceded maximum item size limit (112450). /Applications/Xcode.app/usr/include/c++/v1/vector
```
Question is, whether we should leave it as …
> ref: Log warning when debug source excedes item size limit

- src/utils/xcode.rs
This is sort of an edge-case, as XCode is not producing an `Info.plist` file
by default anymore. However, it still does so for some templates.
For example iOS Storyboard template will produce a partial `Info.plist` file,
with a content only related to the Storyboard itself, but not the project as a whole. eg.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>UIApplicationSceneManifest</key>
<dict>
<key>UISceneConfigurations</key>
<dict>
<key>UIWindowSceneSessionRoleApplication</key>
<array>
<dict>
<key>UISceneStoryboardFile</key>
<string>Main</string>
</dict>
</array>
</dict>
</dict>
</dict>
</plist>
```
This causes a false-positive in this branch, as …
> fix: Fallback to xcodebuild vars for faulty Info.plist files

- src/api.rs
- src/commands/events/list.rs
- src/commands/events/mod.rs
- src/commands/mod.rs
- tests/integration/_cases/events/events-help.trycmd
- tests/integration/_cases/events/events-list-empty.trycmd
- tests/integration/_cases/events/events-list-help.trycmd
- tests/integration/_cases/events/events-no-subcommand.trycmd
- tests/integration/_cases/help/help-windows.trycmd
- tests/integration/_cases/help/help.trycmd
- tests/integration/events/list.rs
- tests/integration/events/mod.rs
- tests/integration/mod.rs
Sorry to re-open a PR for the same feat, but I can't re-open #1047. This PR adds
```
Manage events on Sentry.
USAGE:
sentry-cli events [OPTIONS] <SUBCOMMAND>
OPTIONS:
--auth-token <AUTH_TOKEN>    Use the given Sentry auth token.
-h, --help                       Print help information
--header <KEY:VALUE>         Custom headers that should be attached to all requests
in key:value format.
--limit <LIMIT>              Limit of requests [default: 10]
--log-level <LOG_LEVEL>      Set the log output verbosity. [possible values: trace, debug,
info, warn, error]
--max-rows <MAX-ROWS>        Max of rows for a table.
-o, --org <ORG>                  The organization slug
-p, --project <PROJECT>          The project slug.
--quiet                      Do not print any output while preserving correct …
```
> Retrieve the events list for a project for v2

- src/commands/sourcemaps/explain.rs
- tests/integration/_cases/sourcemaps/sourcemaps-explain-detect-from-file-content.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-detect-from-sourcemap-header.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-detect-from-xsourcemap-header.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-print-sourcemap.trycmd
- tests/integration/_responses/sourcemaps/get-file-metadata-sourcemap-header.json
- tests/integration/_responses/sourcemaps/get-file.js
This better mimics the behavior of https://github.com/getsentry/sentry/blob/72e351082168f68cbaa5700a51e8ed577222e887/src/sentry/lang/javascript/processor.py#L984 and our internal release fetching mechanism.
Based on https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.lmz475t4mvbx the sourcemap url should be relative to the path the JS file was loaded from.
Thos `http://whatever.com/static/js/bundle.js` with `sourceMappingURL=foo.js` should point to `http://whatever.com/static/js/foo.js` and not just `http://whatever.com/foo.js`.
Also fixes https://github.com/getsentry/sentry-cli/issues/1313 along the way.
> ref: Use better artifacts url resolution for sourcemaps explain

- src/commands/sourcemaps/upload.rs
- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-upload-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-no-dedupe.trycmd
- tests/integration/_fixtures/vendor.min.js.map
- tests/integration/sourcemaps/upload.rs
Some people prefer not to use it, as it "costs" sometimes quite a lot of requests (our release artifacts paging is 20 items each afair), that count toward API quota.
Resolves https://github.com/getsentry/sentry-cli/issues/1322
> feat(sourcemaps): Add no-dedupe flag for skipping deduplication

- src/api.rs
- src/utils/xcode.rs
Workaround for the small regression introduced in https://github.com/getsentry/sentry-cli/pull/1275 that happens in usecases where over 20k of files are uploaded for a single release.
Potential improvement is explained in the comment:
> Instead of breaking out of the loop here when we reach the limit
> (200 pages of 100 items, for a total of 20_000 files), we should send a list of hashes
> to the server, perform an intersection there, and change the upload mechanism
> to leave out only those files that were gave back to us by the server.
> This would also limit number of API requests for deduping from `N=[1:200]` to 1.
Related DIFs functionality that we can reuse here:
1. https://github.com/getsentry/sentry/blob/f9bf16e7d663c780c1e0c0378ae92f2a93aa326b/src/sentry/api/urls.py#L1941-L1945 …
> fix: Break out of the loop when we reach cursor limit for list_release_files

- Cargo.lock
- Cargo.toml
When using `difutil bundle-sources` on a symbolicator dif built with the latest Rust compiler, we would otherwise get a spurious EOF error.
Possibly related to https://github.com/getsentry/symbolic/pull/652
> fix: Update symbolic to fix spurious EOF errors

- src/commands/debug_files/find.rs
NOTE: `takes_name` implicitly sets `Arg::takes_value(true)`
Whoops.
#no-changelog
> fix: paths argument for debug-files find should take a value

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
Used `Get-ChildItem . -Filter *.yml | Foreach-Object { pin-github-action --allow 'actions/*,getsentry/*' $_.FullName }` and manually reverted the most disturbing formatting changes it's making (line breaks on long lines)...
There should be no need to do this again + new PRs will automatically get a failure through Danger.
> ci: update and pin GHA to commit hash

- Cargo.lock
- Cargo.toml
- src/api.rs
- src/commands/debug_files/check.rs
- src/commands/debug_files/find.rs
- src/commands/debug_files/upload.rs
- src/utils/dif.rs
- src/utils/dif_upload.rs
- src/utils/fs.rs
- src/utils/system.rs
- tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
- tests/integration/_cases/upload_dif/upload_dif-help.trycmd
This adds support to the `debug-files` subcommand to check, find and upload Portable PDB files.
The actual upload still depends on properly exposing this in sentry.
> feat: Add support for Portable PDB debug files

- src/api.rs
Ref: https://github.com/getsentry/sentry-cli/issues/1362
> fix: Add % and / to reserved path characters in url encoding

- js/helper.js
- js/index.d.ts
Allow multiple headers to be passed to sentry-cli when usingy the JS interface.
Fixes https://github.com/getsentry/sentry-cli/issues/1354
> feat: Add `headers` option on sentry cli js interface (#1354)

- src/api.rs
Fixes https://github.com/getsentry/sentry/issues/40307
However, at this point, I'm not sure if we couldn't just encode all reserved characters.
Our `validate_release` is very loose, so it'd make sense. Or would it be too much?
It looks like our own UI does just that. For example `foo.bar@4.2+1337` is encoded as `foo.bar%404.2%2B1337` (delete all artifacts call below)
```
Request URL: https://sentry.io/api/0/projects/kamil-test/test-1/files/source-maps/?name=foo.bar%404.2%2B1337
Request Method: DELETE
```
If we follow https://www.rfc-editor.org/rfc/rfc3986#section-2.2 then it'd change the code to:
```rust
// RFC3986 Reserved Characters: https://www.rfc-editor.org/rfc/rfc3986#section-2.2
const ENCODE_SET: AsciiSet = CONTROLS
.add(b':')
.add(b'/')
.add(b'?')
.add(b'#')
.add(b'[')
.add(b']') …
```
> fix: Add + to reserved query characters in url encoding

- Cargo.lock
- Cargo.toml
- src/utils/formatting.rs
- tests/integration/_cases/releases/releases-new-help.trycmd
- version bump
- enabled `yaml` feature for `insta`
- added `.ok()` to previously unused result in `formatting.rs` (we do ignore the error anyway)
Closes https://github.com/getsentry/sentry-cli/pull/1361
> deps: Bump all dependencies to their latest versions (except clap and indicatif)

- js/helper.js
It appears that `path.resolve` already caters for path separator differences so you can safely use forwards slashes and everything works.
Closes #1368
> fix: Windows binary location

- js/helper.js
- package.json
- scripts/test-vercel-nft.js
- src/api.rs
- src/utils/file_upload.rs
- src/utils/xcode.rs
- yarn.lock
This is a backport of #1374 to the 1.x branch.
I had to disable the `@vercel/nft` test on node.js v8 because it doesn't support versions that old
I also allowed a few Rust clippy lint failures which is no doubt caused by this branch being built with a newer version of Rust than was intended. I chose to disable them rather than follow the lint fix suggestions since this branch will never get merged back into master and it didn't seem appropriate to change the code at this point!
> feat: Replace usage of `eval` to obfuscate binary path from bundlers [backport to 1.x]

- js/helper.js
- package.json
- scripts/test-vercel-nft.js
- yarn.lock
`eval` is not ideal because it causes Rollup to display warnings. 
As per my [test repo](https://github.com/timfish/vercel-nft-test), it's reasonably easy to obfuscate paths from `@vercel/nft` without using `eval` as the evaluator can only simplify so far.
This PR adds a test to check that the binaries are not picked up by `@vercel/nft`.
For the purposes of demonstrating the newly added test, the first commit replaces the `eval` usage with `path.resolve()` which will cause the test to fail as the binary is picked up. 
A subsequent commit will add the mildly obfuscated path generation.
> fix: Replace usage of `eval` to obfuscate binary path from bundlers

- Cargo.lock
- Cargo.toml
fix #1382 by using contexts integration
> fix:  Re-add `server_name` in events

- Cargo.lock
- Cargo.toml
- src/commands/files/upload.rs
- src/commands/react_native/appcenter.rs
- src/commands/react_native/gradle.rs
- src/commands/react_native/xcode.rs
- src/commands/send_event.rs
- src/commands/sourcemaps/upload.rs
- src/utils/args.rs
- tests/integration/_cases/send_event/send_event-raw-fail.trycmd
- tests/integration/send_event.rs
Make sure we limit the length of the incoming distribution name, which should not be longer than 64 characters, which is enforced on the DB side.
This change just adds the validation as closer to the user as possible.
related: https://github.com/getsentry/relay/pull/1556
> feat(dist): Add limit validation

- scripts/install.js
Fixes https://github.com/getsentry/sentry-cli/issues/1387
> fix: Handle closed connection when downloading sentry-cli binary

- .github/workflows/ci.yml
While working on the install script, I noticed there aren't really any tests covering the install script (which made it hard to verify if everything works on different versions of node).
This PR adds a very basic test on CI that:
* Checks out the branch
* Creates a new, empty npm app
* Installs sentry-cli from the checked out branch
* Verifies the binary exists
I _hope_ the binary check is correct for what the install.js script does (it passes at least). But it should give at least a bit more security about changes to the install script!
Note that I also extended the test matrix to node 18, which is also LTS by now.
> chore: Add test for install script

- src/utils/xcode.rs
In https://github.com/getsentry/sentry-cli/pull/1311 expanding Plist var when reading from the path was removed. I believe this was a mistake as this change is causing issues in react native.
Fixes https://github.com/getsentry/sentry-react-native/issues/2581
Fixes https://github.com/getsentry/sentry-cli/issues/1395
> fix(xcode): Plist vars are always expanded

- js/__tests__/helper.test.js
- js/releases/index.js
- js/releases/options/uploadSourcemaps.js
Adds the ability to pass the `--decompress` flag to the CLI from JS. Need this to deal with files compressed by gzip 
PR where the `--decompress` flag was added to the CLI: https://github.com/getsentry/sentry-cli/pull/1277
This PR is entirely based on this other PR: https://github.com/getsentry/sentry-cli/pull/373
> feat: Add --decompress option

- src/utils/sourcemaps.rs
`/this/is/valid/location.js.map`
> fix: Allow for path based sourcemaps in validation report

- build.rs
- src/commands/bash_hook.rs
- src/commands/monitors/run.rs
- src/utils/appcenter.rs
- src/utils/chunks.rs
- src/utils/codepush.rs
- src/utils/xcode.rs
Previously if a monitor run tried to invoke a non existing binary the status of the monitor check-in remained as `in_progress`. With this change it will properly report as `error`.
> feat(monitors): Report spawn failures

- src/bashsupport.sh
- tests/integration/_cases/bash_hook/bash_hook.trycmd
Bash has a nifty feature `set -u` to error on unbound variables. This is also trappable (like with `set -e`), so Sentry can catch this.
However, Sentry itself may attempt to access arguments via `$1` and `$2`, which may not be set, which will trigger a bash error if `set -u` is used. This will create an error output: `./my_script.sh: line 42: $1: unbound variable`.
The proposed fix here will check for existence of `$1...$n` via the argument count `$#`, without accessing `$1...$n`, making it possible to use Sentry for bash scripts with `set -u`
> Prevent Sentry from attempting to access unbound variables

- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-env.trycmd
- tests/integration/monitors/run.rs
This adds `SENTRY_MONITOR_ID` to the environ of the executing command.
This is in support of https://github.com/getsentry/sentry/issues/43647
and will allow SDKs embedded in the executing command to associate the
monitor context to any events produced by the SDK.
> feat(monitors): Pass SENTRY_MONITOR_ID to executing process

- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-env.trycmd
This adds `SENTRY_TRACE_ID` to the environ of the executing command.
This is in support of https://github.com/getsentry/sentry/issues/43647
and will allow SDKs embedded in the executing command to associate the
monitor checkin to any events produced by the SDK.
This is the second part of #1438
> feat(monitors): Pass SENTRY_TRACE_ID down execution path

- tests/integration/_cases/monitors/monitors-run-win.trycmd
- tests/integration/monitors/run.rs
Currently fails with the following error when run on Windows
```
Testing tests/integration/_cases/monitors/monitors-run.trycmd:2 ... failed
Expected success, was 1
---- expected: stdout
++++ actual:   stdout
1      - 123
1 + error could not invoke program 'echo': program not found
stderr:
```
> test: fixcommand_monitors_run test on windows

- src/api.rs
- src/commands/monitors/run.rs
This is consistent with the sentry codebase
> ref(monitors): Rename MonitorStatus -> MonitorCheckinStatus

- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-env.trycmd
This will be implemented in a different way in the near future
> ref(monitors): Drop passing `SENTRY_TRACE_ID`

- CHANGELOG.md
Not 100% sure about the `ref` entires, they do seem kind of relevant for the changelog maybe, but not sure?
Note: Make sure to publish this _after_ https://github.com/getsentry/sentry-cli/pull/1474.
> meta(changelog): Update CHANGELOG for 2.13.0

- Cargo.lock
- Cargo.toml
- src/utils/vcs.rs
`1.65` is the first stable release that supports `let-else` that we use in `sentry-rust`.
> build: Move to rust edition 2021 and msrv to 1.65

- scripts/install.js
Fixes https://github.com/getsentry/sentry-cli/issues/1452
> ref: Support lower and uppercased env vars for npm cache

- .craft.yml
- .github/workflows/build.yml
- MANIFEST.in
- pyproject.toml
- scripts/wheels
- setup.cfg
- setup.py
this packages up this binary as something that's `pip install`able -- hopefully making the setup process easier and not relying on the uptime of github packages or the sentry cdn for installation
how this works:
1. build a sdist and wheel from source (mostly to demonstrate that building from source works for _unsupported_ platforms)
2. download the prebuilt artifacts that we distribute through github releases
3. stitch the prebuilt binaries into wheels, adjusting the platform tag to match
(this saves building everything twice, and ensures that identical binaries are present independent of how it installs)
I've also pushed this to `release/just-testing` so I can validate that the build works (it should show in this PR too!)
```console
$ ./venv/bin/pip install …
```
> ref: also distribute sentry-cli as a pip package

- src/api.rs
Clippy changed in latest rust version, gotta go with the flow.
> fix: derive default to make clippy happy

- src/commands/sourcemaps/inject.rs
- src/commands/sourcemaps/upload.rs
- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
- tests/integration/_cases/sourcemaps/sourcemaps-upload-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-no-dedupe.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-skip-already-uploaded.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-successfully-upload-file.trycmd
This ensures that debug ids are injected into source files and sourcemaps before uploading. A `--no-inject` flag is provided to disable this behavior.
As a refactoring, most of the injection logic is moved into a new module under `utils/sourcemaps`. This may be easier to understand by looking at the commits individually.
Questions:
* should the `--no-inject` flag be hidden?
* is the injection happening in the right place in `upload.rs`?
> feat: Inject debug ids into source and sourcemap files before uploading

- CHANGELOG.md
- src/utils/sourcemaps/inject.rs
Writing to a vector of bytes does not overwrite it, it appends. Thus, when injecting a debug id into a sourcemap file, we must clear the buffer before writing the modified contents.
Fixes #1524.
> fix(inject): Clear buffer before writing sourcemap

- src/commands/sourcemaps/inject.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject-nomappings.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject.trycmd
The second commit slightly changes the `inject` tests to use multiple paths.
This is required for https://github.com/getsentry/sentry-react-native/issues/2892
> ref: Allow multiple paths in sourcemaps inject

- CHANGELOG.md
- src/commands/sourcemaps/upload.rs
- tests/integration/_cases/releases/releases-files-upload-sourcemaps.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-modern.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-no-dedupe.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-skip-already-uploaded.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-successfully-upload-file.trycmd
This disables injection on `sourcemaps upload` unless the env var `SENTRY_FORCE_ARTIFACT_BUNDLES` is set to `1`. Without this, debug ids don't do anything anyway.
> fix(inject): Gate injection on upload behind env var

- src/api.rs
- src/commands/info.rs
- src/config.rs
This is in support of https://github.com/getsentry/sentry-cli/issues/1537
Explicitly does not add this as a global cli parameter
> feat(auth): Support DSN auth for the API client

- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
This adds a function that should handle all forms of sourcemap URL correctly, not just the most basic ones. The logic that preserves initial `./` segments is pretty cursed though.
> feat(inject): Handle relative and absoule sourcemap URLs

- src/api.rs
- src/commands/info.rs
- src/commands/monitors/run.rs
- src/config.rs
- tests/integration/_cases/monitors/monitors-run-token-auth-win.trycmd
- tests/integration/_cases/monitors/monitors-run-token-auth.trycmd
- tests/integration/monitors/run.rs
Replaces https://github.com/getsentry/sentry-cli/pull/1541 and https://github.com/getsentry/sentry-cli/pull/1543
> ref(crons): Prefer DSN based auth

- src/utils/file_upload.rs
This changes the logic for the debug IDs of bundles to be deterministic on file contents and debug IDs. This way running the same upload twice should result in the new bundle replacing the old or no change being done by the server.
> Use a deterministic bundle ID

- src/utils/file_search.rs
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject-nofiles.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject-nomappings.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-modern.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-no-dedupe.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-skip-already-uploaded.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-successfully-upload-file.trycmd
- tests/integration/sourcemaps/inject.rs
Made the report exactly the same as we have one for Source Map upload. Including formatting, indentations and colors.
Also reports when there was no injections performed.
Reformatted:
```
> Found 19 release files
> Analyzing 19 sources
> Analyzing completed in 0.09s
> Injecting debug ids
Source Map Debug ID Injection Report
Modified: The following source files have been modified to have debug ids
2297b93d-928d-421e-8910-127c786382da - tests/integration/_fixtures/inject/server/chunks/1.js
049a6b25-335d-4d9e-b857-d5c05c079a40 - tests/integration/_fixtures/inject/server/pages/_document.js
6faf72f2-6ac7-4b71-be01-f744fede7d1a - tests/integration/_fixtures/inject/static/chunks/575-bb7d7e0e6de8d623.js
2297b93d-928d-421e-8910-127c786382df - …
```
> ref(inject): Improve injection report output

- js/helper.js
- js/index.d.ts
To support our new debug ID process we add the `forceArtifactBundles` which will set the `SENTRY_FORCE_ARTIFACT_BUNDLES` env var in the Sentry CLI child process.
Ref: https://github.com/getsentry/sentry-docs/pull/6551
Some prettier changes snuck in but i think its fine.
> feat: Add `forceArtifactBundles` bundles option to JS interface

- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject.trycmd
- tests/integration/_fixtures/inject/server/dummy_embedded.js
This injects debug ids into source files with embedded sourcemaps. The test for this is a dummy file added to the injection fixtures—perhaps not the most elegant solution, but it works.
> fix: Inject files with embedded sourcemaps

- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
This also fixes the `test_fixup_js_file_fs_roundtrip` test, which was unintentionally lenient. There were too few source mapping comments; even when they were deleted, the file still ended up longer after injection because the injected code snippet is so long.
> fix(inject): Use File::create to make sure files are truncated

- src/commands/sourcemaps/inject.rs
- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject-nomappings.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject.trycmd
This removes the checks on whether a source file references a sourcemap and whether that sourcemap can be found in the local file system. Instead, it now
1. always injects minified source files (unless they already have a debug id, of course)
2. injects the same debug id into the sourcemap file, if applicable
3. reuses the debug id in the sourcemap file, if any.
> fix(inject): Inject regardless of whether a sourcemap is present

- src/utils/sourcemaps.rs
Turns out that injecting every source file with type `MinifiedSource` is wrong—`is_likely_minified_js` can have positives for things that aren't minified js. Therefore we now additionally filter the files to be potentially injected by their extensions, disregarding anything but `.js`.
> fix(inject): Don't inject non-js files

- src/utils/sourcemaps/inject.rs
This implements deterministic debug ID generation for minified files based on the source map's contents.
> feat: Add deterministic debug IDs for minified JS files

- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
This now emits deterministic debug IDs even for when there are no source maps by falling back to content hashing.
> feat(debug_id): More determinism for JS debug IDs

- js/helper.js
Currently if you pass `{dist: undefined}` or `{release:undefined}` that value is skipped as parameter. However if you pass `{dist:null}` it turns into `--dist null` which just makes no sense. I would vote for removing this footgun and removing null the same way as undefined.
Refs https://github.com/getsentry/action-release/pull/125
Fixes #1578
> feat(js): Skip null as option same as undefined

- Cargo.lock
- Cargo.toml
- src/commands/send_envelope.rs
- src/commands/send_event.rs
- tests/integration/_cases/send_event/send_event-help.trycmd
This does not *fully* deserialize/validate the event JSON, just enough to extract an `event_id` from it. It is then sent as a raw envelope.
Depends on https://github.com/getsentry/sentry-rust/pull/568
> Add ability to send an Event as Raw Envelope

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/api.rs
- src/utils/sourcemaps.rs
This updates the `sourcemap` dependency to 6.2.3 in order to make [this fix](https://github.com/getsentry/rust-sourcemap/pull/61) accessible in v1 of `sentry-cli`. The changes to `src/utils/sourcemap.rs` are taken from 94bc533, the commit that updated `sourcemap` from `5.x.x` to `6.x.x` in v2.
> feat(backport): Update sourcemap to 6.2.3

- src/utils/file_upload.rs
- tests/integration/_cases/debug_files/debug_files-bundle-jvm-input-dir-empty.trycmd
- tests/integration/_cases/debug_files/debug_files-bundle-jvm-output-is-file.trycmd
- tests/integration/_cases/debug_files/debug_files-bundle-jvm-output-not-found.trycmd
- tests/integration/_cases/debug_files/debug_files-bundle-jvm.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-modern.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-no-dedupe.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-skip-already-uploaded.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-some-debugids.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-successfully-upload-file.trycmd
This outputs the generated bundle's debug id at the end of `build_artifact_bundle`.
> feat: Print bundle id after artifact bundle creation

- src/commands/debug_files/upload.rs
- tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
- tests/integration/_cases/upload_dif/upload_dif-help.trycmd
Proguard has a standalone method for uploading its mappings, as it has more detailed options that let modify said upload.
Fixes https://github.com/getsentry/sentry-cli/issues/1614
> ref: Remove proguard from debug-files upload types

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/QUESTION.md
Original copied from https://github.com/getsentry/.github/tree/main/.github/ISSUE_TEMPLATE with updated `BUG_REPORT.md` template, as you cannot override a single one, and inherit the rest of templates.
> misc: Add custom issues templates

- .github/workflows/build.yml
`10.x` is not even supported anymore 👀
> ci: Use macos-latest to run build workflow

- tests/integration/_cases/debug_files/debug_files-bundle-jvm-output-not-found.trycmd
- tests/integration/debug_files/bundle_jvm.rs
Use testcase-based cwd instead of project root for creating test input 👀 
> ref(test): Remove temp files created during integration tests

- src/api.rs
- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-token-auth-win.trycmd
- tests/integration/_cases/monitors/monitors-run-token-auth.trycmd
- tests/integration/_responses/monitors/post-monitors-environment.json
- tests/integration/monitors/run.rs
In https://github.com/getsentry/sentry-cli/pull/1618 we completely dropped support for check-ins via the API using token-auth.
While this method of creating cron monitor check-ins is long deprecated and undocumented, we would prefer to not break any users usages of crons when upgrading a non-major
> feat(crons): Bring back legacy token-auth checkin API

- src/utils/sourcemaps/inject.rs
Add a semicolon at the end of the injected snippet to prevent ASI issues.
Fixes https://github.com/getsentry/sentry-cli/issues/1642
> fix(inject): Add semicolon at the end of inject snippet

- Cargo.lock
- Cargo.toml
- src/utils/file_upload.rs
Building an artifact bundle is currently nondeterministic. This is because of two factors:
1. We depend on an outdated version of `symbolic` in which the order in which you add files to a source bundle matters.
2. When building the bundle, we iterate over source files in nondeterministic order.
This adds a failing test and then fixes the problem by updating `symbolic` and presorting source files.
> fix: Make artifact bundle creation deterministic

- CHANGELOG.md
- src/api.rs
- src/utils/file_upload.rs
- tests/integration/debug_files/bundle_jvm.rs
- tests/integration/mod.rs
- tests/integration/sourcemaps/upload.rs
This is a corrected version of #1651. The problem in that version was that we didn't check if a `missing_chunks: []` reply from the server actually meant anything. This led to not uploading anything if the server returned `[]` as a default value. Therefore, this version adds a new `ChunkUploadCapability` variant `ArtifactBundlesV2`. Only if the server supports this capability are the chunks deduplicated.
~The changelog looks weird right now because the revert of #1651 is not yet published.~
> feat: Don't upload chunks that are already on the server (fixed version)

- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject-split-ambiguous.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject-split.trycmd
- tests/integration/_fixtures/inject_split/code/foo/index.js
- tests/integration/_fixtures/inject_split/code/index.js
- tests/integration/_fixtures/inject_split/maps/foo/index.js.map
- tests/integration/_fixtures/inject_split/maps/index.js.map
- tests/integration/_fixtures/inject_split_ambiguous/code/foo/index.js
- tests/integration/_fixtures/inject_split_ambiguous/code/index.js
- tests/integration/_fixtures/inject_split_ambiguous/maps/foo/index.js.map
- tests/integration/_fixtures/inject_split_ambiguous/maps/index.js.map
- tests/integration/_fixtures/inject_split_ambiguous/maps2/foo/index.js.map
- tests/integration/sourcemaps/inject.rs
This generalizes the discovery of sourcemaps when injecting, which should make the command easier to use. In particular, you can now have source and sourcemap files in different directories, but the directory hierarchies need to mirror each other. For example, consider:
```
code/
index.js -> index.js.map
child/
foo.js -> foo.js.map
index.js -> index.js.map
sourcemaps/
index.js.map
foo.js.map
child/
index.js.map
```
With this change, each `index.js.map` reference will be matched to its counterpart in the `sourcemaps` directory, but the `foo.js.map` reference would not be resolved because the file is not in the right place. If there is any ambiguity, as in
```
code/
index.js -> index.js.map
sourcemaps/
index.js.map
sourcemaps2/
index.js.map
```
a warning is printed and the sourcemap is …
> feat(inject): Make sourcemap discovery smarter

- src/utils/system.rs
Since errors can occur before the config is set, requiring a config to print errors is a bad idea.
> fix: Don't require config to be set in print_error

- src/commands/debug_files/upload.rs
Somehow it was missing 👀 
Fixes https://github.com/getsentry/sentry-cli/issues/1682
> fix: Add wasm to supported debug-files upload formats

- Cargo.lock
- Cargo.toml
- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
- tests/integration/sourcemaps/upload.rs
~Blocked by getting https://github.com/getsentry/rust-sourcemap/pull/66 released.~
This updates the `sourcemap` dependency to 6.3.0 so that we can use the new debug id features. Specifically:
1. Rewriting sourcemaps leaves the debug id alone.
2. Adding a debug id to a sourcemap doesn't require manual JSON parsing anymore.
> ref: Use sourcemap debugid features

- src/api.rs
- src/commands/upload_proguard.rs
Creates a weak release association with a proguard mapping file. https://github.com/getsentry/team-mobile/issues/27
> feat(proguard): Release association

- CHANGELOG.md
- scripts/install.js
This fixes the nasty issue when using `npm` to install cli with locally existing binary.
`which` iterates over all possible binaries available in the PATH, and by default it reports the first occurrence. 
This is however problematic when using `npm` since I believe v8, as they started to include all `node_modules/.bin` in the `PATH` when executing npm script, making `npm run install` detect the `bin/sentry-cli` file that we have, which is just a JS proxy to the _actual_ binary.
It works fine when running install script directly in node or using `yarn`, as they don't modify the PATH.
We want the last possible match, eg.
```
/Users/kamilogorek/Desktop/tmp-cli/node_modules/.bin/sentry-cli,/usr/local/bin/sentry-cli
```
> fix: Correctly detect local binary when installing via npm

- js/helper.js
Hey friends 👋🏻 
What do you think about allowing me to provide my own Sentry CLI binary location?
> Allow the CLI binary path to be overridden

- README.md
They were never documented, so it's nice to have them all in one place.
> docs: Add all installation/js usage env vars

- src/commands/releases/set_commits.rs
Not sure how we missed it and no one reported this in such a long time 👀 
Fixes https://github.com/getsentry/sentry-cli/issues/1701
> fix(set-commits): Allow --initial-depth to be specified alongside --auto

- Cargo.lock
- Cargo.toml
Fixes https://github.com/getsentry/sentry-cli/issues/1710
> deps: Bump sourcemap to 6.4.1

- src/api.rs
- src/bashsupport.sh
- src/commands/bash_hook.rs
- tests/integration/_cases/bash_hook/bash_hook-help.trycmd
- tests/integration/_cases/bash_hook/bash_hook-release-env.trycmd
- tests/integration/_cases/bash_hook/bash_hook-release.trycmd
- tests/integration/bash_hook.rs
- tests/integration/mod.rs
This PR adds support for `SENTRY_RELEASE` variable in the `bash-hook` command.
It adds `--release` argument in the command but the environment variable is
still available, so it checks the value from env first.
Resolves https://github.com/getsentry/sentry-cli/issues/1674
> Add support for `SENTRY_RELEASE` in bash-hook

- src/commands/react_native/xcode.rs
- tests/integration/_cases/react_native/xcode-wrap-call-bundle.trycmd
- tests/integration/_cases/react_native/xcode-wrap-call-custom-bundle.trycmd
- tests/integration/_cases/react_native/xcode-wrap-call-expo-export.trycmd
- tests/integration/_cases/react_native/xcode-wrap-call-minimum.trycmd
- tests/integration/_fixtures/binary.sh
- tests/integration/_fixtures/react_native/empty-sourcemap-report.json.expected
- tests/integration/_fixtures/react_native/full-sourcemap-report.json.expected
- tests/integration/mod.rs
- tests/integration/react_native/mod.rs
Fixes `sentry-expo` issue.
- https://github.com/expo/sentry-expo/issues/364
In Expo SDK 49 new Expo CLI Bundle command was introduced, but current Sentry CLI supports only `bundle` and `ram-bundle` commands.
This PR adds support for `export:embed` from Expo CLI as well as custom bundle command by using env var `SENTRY_RN_BUNDLE_COMMAND`.
> feat(rn): Allow custom bundle command in xcode wrap calls

- src/utils/file_upload.rs
This does two things.
1. It moves the call to `upload_chunks` into the case where there are chunks to upload. This is essentially a cosmetic change.
2. It calls `poll_assemble` no matter if chunks had to be uploaded or not. This causes the artifact bundle to be assembled in edge cases where the chunks are already on the server, but the bundle hasn't been assembled.
Part of the fix of #1724.
> fix: Always poll artifact assembly, even if nothing was uploaded

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
- tests/integration/_fixtures/inject/server/chunks/1.js
- tests/integration/_fixtures/inject/server/pages/_document.js
This replaces https://github.com/getsentry/sentry-cli/pull/1734. The logic for trimming source mapping URLs was implemented in https://github.com/getsentry/symbolic/pull/809.
> deps: Update symbolic

- src/commands/login.rs
This causes the `login` command to open the page for creating org auth tokens.
> feat(login): Open org auth token creation page

- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-upload-file-ram-bundle.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-indexed-ram-bundle.trycmd
- fixes https://github.com/getsentry/sentry-cli/issues/1741
`rust-sourcemap` package only parses modules but doesn't include the root bundle file therefore also doesn't include it's source map.
> fix(rn): Upload root bundle source map for ram bundles

- Cargo.lock
- Cargo.toml
- src/utils/file_upload.rs
This pulls in https://github.com/getsentry/symbolic/pull/813.
> deps: Update symbolic to 12.4.1

- src/config.rs
It is unclear why `sentry` would send a URL containing a `/api/0` prefix, but it happens in practice and is definitely incorrect. We now make sure to strip these prefixes.
Fixes https://github.com/getsentry/sentry-cli/issues/1722, https://github.com/getsentry/sentry-cli/issues/348.
> fix: Strip `/api/0` prefix from endpoint URLs

- src/commands/react_native/xcode.rs
If hermesc path is in envs and exists react native tooling assumes hermes is enabled.
Sentry cli puts itself on the path therefore react native tooling always assumes hermes is enabled.
> fix(rn): Remove hermesc envs if hermes is disabled

- src/api.rs
As reported on Slack, calling `upload-proguard` twice with the exact same arguments causes an error, even though it's perfectly benign. The issue is that Sentry returns `409` for identical `ProguardArtifactRelease` objects: https://github.com/getsentry/sentry/blob/4882e79cd67363cb40e9d3f08b161783f21eb4e8/src/sentry/api/endpoints/debug_files.py#L136-L151
(Strictly speaking, a duplicate (release, debug file, uuid) triple will cause an error. I don't think the distinction matters in practice.)
We should just log a message in this case and otherwise succeed.
> fix: Don't fail on duplicate proguard release association

- src/config.rs
This makes the URL field of org auth tokens optional. Local and self-hosted Sentry instances don't return a URL within their tokens sometimes. In such cases, the URL now needs to be set via one of the other ways (CLI option, env var, config file). It is still an error to pass different URLs via the token and another method.
Fixes #1763, #1765.
> fix: Make URL in org auth tokens optional

- src/config.rs
URLs in org auth tokens were made optional in #1766, but there was some logic left that manually bailed if the URL was unset.
> fix: Org auth token logic

- src/utils/dif_upload.rs
Currently an exe without a debug id just results in "0 debug files found", which is confusing. This adds log messages for objects that have no debug ids or are otherwise invalid.
> fix: Log messages for invalid objects

- .craft.yml
Temporarily removes the PyPI targets from Craft. As it stands nearly every Python release of `sentry-cli` fails and this causes trouble for the rest of the release process.
The PyPI issue for diagnosing this is [here](https://github.com/pypi/support/issues/3222). We might also open an upload limit request.
> meta: Disable Python releases

- Cargo.lock
- Cargo.toml
- src/commands/mod.rs
- tests/integration/_cases/help/help-windows.trycmd
- tests/integration/_cases/help/help.trycmd
This adds the ability to generate shell completions to the CLI.
While this PR is not in an ideal form yet, I'd be more than happy to work together to make it fit the used patterns in this repo.
I tried following them, but ran into trouble because the `execute` method for each command did not get a `Command` passed, which this shell completions generator needs.
Here is an example of me using the completions this generates:
https://asciinema.org/a/dsXad2IayVyXJFHKX0GjvRhjH
> feat: add shell completion generation

- src/commands/mod.rs
> Allow log-level parameter to affect log from reading config

- Cargo.toml
Sentry CLI is downloaded many times during consumers' CI. Even though the download should be fast in general and the binary size reduction wouldn't have a great effect on individual runs, it does have an effect at the scale it is used at.
Example: macOS arm64 binary size reduction by these changes is about 30 %.
> chore: reduce realease binary size

- Dockerfile
- scripts/build-in-docker.sh
As shown in https://github.com/getsentry/sentry-cli/issues/1796, our fork of `rust-musl-cross` is outdated and it is unclear why we still need it.
> build: Use upstream rust-musl-cross docker image

- scripts/build-in-docker.sh
If we don't vendor OpenSSL on ArmV7, `sentry-cli` won't build (as seen [here](https://github.com/getsentry/sentry-cli/actions/runs/6769700929/job/18396616213)).
> build: Vendor OpenSSL on ArmV7

- src/config.rs
We already include the argument in the error message for organisation and release, hence also adding it for project.
> ref: Improve error message if a project slug is missing

- Cargo.lock
fixes an important issue on Windows, that sporadically would return " [56] Failure when receiving data from the peer"
I suggest merging ASAP, all tests pass. thanks!
> chore: bump curl-sys dependency to 0.4.68

- CHANGELOG.md
- js/index.d.ts
- js/index.js
- js/install.js
- scripts/install.js
We would like to be able to install the CLI manually in downstream dependencies in case postinstall scripts did not get executed.
> feat: Expose `downloadBinary` function to install binary

- CHANGELOG.md
Just a changelog change so that we can release CLI v2 right after the v1 release: https://github.com/getsentry/publish/issues/2992
> meta: Add changelog entry for v1 release override

- npm-binary-distributions/darwin/bin/sentry-cli
- npm-binary-distributions/darwin/package.json
- npm-binary-distributions/linux-arm/bin/sentry-cli
- npm-binary-distributions/linux-arm/package.json
- npm-binary-distributions/linux-arm64/bin/sentry-cli
- npm-binary-distributions/linux-arm64/package.json
- npm-binary-distributions/linux-i686/bin/sentry-cli
- npm-binary-distributions/linux-i686/package.json
- npm-binary-distributions/linux-x64/bin/sentry-cli
- npm-binary-distributions/linux-x64/package.json
- npm-binary-distributions/win32-i686/bin/sentry-cli
- npm-binary-distributions/win32-i686/package.json
- npm-binary-distributions/win32-x64/bin/sentry-cli
- npm-binary-distributions/win32-x64/package.json
Adds packages for binary distributions on npm based on the binaries we currently distribute.
Ref https://github.com/getsentry/sentry-cli/issues/1360#issuecomment-1819270364
> build: Add placeholder packages for npm binary distributions

- .craft.yml
- .github/workflows/build.yml
- npm-binary-distributions/darwin/README.md
- npm-binary-distributions/darwin/bin/sentry-cli
- npm-binary-distributions/linux-arm/README.md
- npm-binary-distributions/linux-arm/bin/sentry-cli
- npm-binary-distributions/linux-arm64/README.md
- npm-binary-distributions/linux-arm64/bin/sentry-cli
- npm-binary-distributions/linux-i686/README.md
- npm-binary-distributions/linux-i686/bin/sentry-cli
- npm-binary-distributions/linux-x64/README.md
- npm-binary-distributions/linux-x64/bin/sentry-cli
- npm-binary-distributions/win32-i686/README.md
- npm-binary-distributions/win32-i686/bin/sentry-cli
- npm-binary-distributions/win32-x64/README.md
- npm-binary-distributions/win32-x64/bin/sentry-cli
- scripts/bump-version.sh
Sets up CI to upload the tarballs of the sentry CLI binary distributions for different architectures on release branches.
Ref: https://github.com/getsentry/sentry-cli/issues/1360#issuecomment-1819270364
We will verify this with an alpha release.
> feat: Publish binary distributions on npm

- CHANGELOG.md
- npm-binary-distributions/darwin/package.json
- npm-binary-distributions/linux-arm/package.json
- npm-binary-distributions/linux-arm64/package.json
- npm-binary-distributions/linux-i686/package.json
- npm-binary-distributions/linux-x64/package.json
- npm-binary-distributions/win32-i686/package.json
- npm-binary-distributions/win32-x64/package.json
We need this to be able to publish the packages for the first time
> build: Set npm publish config public

- .github/workflows/build.yml
The github upload/download action seems to strip away the x flag causing `EACCESS` errors when trying to execute the binaries
> build: Add executable flag to linux binaries before packing tarballs

- CHANGELOG.md
Apparently we can't do alpha releases on brew. CLI is alpha-free zone.
Fixes https://github.com/getsentry/sentry-cli/issues/1840
> fix: Changelog entry for empty release to fix brew

- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject-split-ambiguous.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-some-debugids.trycmd
- tests/integration/_fixtures/inject/server/dummy_hosted.js
- tests/integration/_fixtures/inject/server/dummy_hosted.js.map
When a sourceMappingURL is a remote URL (e.g. static storage in an S3 bucket), `sentry-cli sourcemaps inject` was treating it like a normal file path, attempting to "normalize" it with the source path, and producing a bogus url such as `path/to/source/dir/https://some-static-host.example.com/path/to/foo.js.map`, which of course doesn't exist, and thus the sourcemap isn't found and doesn't have the debug id injected - even if it's sitting right there in the local directory, next to its corresponding bundled source file.
With this change, the sourcemap discovery step does not attempt to use the discovered sourcemap URL if it is a remote URL. Instead, it falls back to guessing the sourcemap location based on the source filename and its location.
I also changed a couple trycmd tests to remove …
> fix(sourcemaps): don't attempt to treat remote URL as a local file path

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
This change separates the GitHub Bug Report Issue template's **Expected/Actual Result** section into two separate sections titled **Expected Result** and **Actual Result**. This change should make it easier to tell at a quick glance what the user expected to happen versus what actually happened, and it will hopefully make bug report issues easier for us to understand. We already have separate expected and actual results sections in the getsentry/sentry-python repository, and I find issues with the separated structure easier to read and understand.
> meta: Restructure Bug Report Issue Template

- src/utils/releases.rs
When the `sentry-cli releases propose-version` command fails to automatically determine a release name, it will output a more descriptive error message. The new error message specifically directs users to ensure their version control system is properly configured.
Fixes GH-1853
> feat(api): More descriptive `releases propose-version` error

- Cargo.toml
For whatever reason, when the Sentry CLI is compiled with link-time optimizations enabled, it hangs when run in Xcode Cloud and ends up resulting in a timeout error after c.a. 30 minutes. The CLI appears to run correctly if it is compiled without link-time optimizations, so by disabling these optimizations, we can fix the problem in Xcode Cloud.
Fixes GH-1820
> build: Fix CLI in Xcode Cloud by Disabling Link-time Optimizations

- src/api.rs
- src/commands/organizations/list.rs
- src/config.rs
- tests/integration/organizations/list.rs
The `organization list` command currently relies on the base `https://sentry.io/api/0/organizations/` route to query the user's active organizations; however, this will stop working when we incorporate multiple regions.
In order to address this, we've added logic to query an active user's regions, then fan-out to each of the individual regions in order to query all active organizations. This list is then combined and sorted by name as per usual.
In order to make this change, some of the underlying URI and request construction code had to be modified to allow overriding the request hostname with the region's hostname.
> fix(hybrid-cloud): Adds region fan-out to organizations list command

- Cargo.lock
- Cargo.toml
> ref: upgrade git2 so safe.directory is implemented more correctly

- js/install.js
Fixes https://github.com/getsentry/sentry-cli/pull/1817/files#r1432446927
> fix: Return promise from download binary when `SENTRYCLI_SKIP_DOWNLOAD` is set

- src/commands/organizations/list.rs
Addresses an edge case with organization listing in SAAS, where a user with a single organization in a non-default region will only be shown organizations in the default region.
> fix(hybrid-cloud): Updates organization list to handle single org fanout

- js/helper.js
- package.json
- scripts/install.js
Fixes https://github.com/getsentry/sentry-cli/issues/1849 to some degree.
With this PR we re-add a post-install script that will manually download the Sentry CLI binary from our CDN if we cannot find the npm binary distributions that would be installed via optional dependencies.
This will improve the reliability for situations where optional dependencies are not installed (like Vercel apparently).
We still require either postinstall scripts to be enabled, OR optional dependencies to be installed.
> fix: Manually download binary if optional dependency binary can't be found after installation

- js/helper.js
- scripts/install.js
Got inspired by esbuild and wanted to emit a better log message if the optional deps thing doesn't work.
> ref: Emit better log message for fallback postinstall script

- .github/workflows/ci.yml
The download will fail on release branches: https://github.com/getsentry/sentry-cli/actions/runs/7347591741/job/20004278485
Reason being that the new version isn't available yet - meaning optional deps won't be downloaded AND the CDN doesn't host the new version yet, crashing the install script.
This PR should fix that by simply skipping the fallback download for tests.
> ci: Skip fallback download in tests

- src/utils/sourcemaps.rs
Fixes Clippy error that was showing up in the linting CI action
> ref: Removed unneeded identity `map`

- CHANGELOG.md
- Cargo.lock
This reverts commit 6b9b32b4481e79282f14dcfbb52f54f2e59b1d7d.
- This fixes https://github.com/getsentry/sentry-cli/issues/1895
- But it brings a bug back on Windows https://github.com/getsentry/sentry-cli/pull/1815
> Revert "chore: bump curl-sys dependency to 0.4.68 (#1815)"

- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-environment-long.trycmd
- tests/integration/_cases/monitors/monitors-run-help.trycmd
- tests/integration/monitors/run.rs
There is `-e` option in `sentry-cli monitors run`, which allows to pass environment name. However, it was missing any non-shorthand variant. This pull request fixes this inconsistency by adding `--environment` as an alternative name for this option.
Some people prefer full option names for their explicitness, especially when writing scripts. All the other shorthand options for `monitors run`, i.e. `-s` and `-h`, have their non-shorthand variants, i.e. `--schedule` and `--help`, respectively.
> Add "--environment" option to "monitors run" (supplement "-e" shorthand)

- .craft.yml
This reverts commit bde2cbd4b450fc85ca73d0a0a872254ad744c028.
> meta: Revert "meta: Temporarily disable npm targets for v1 release (#1903)"

- src/config.rs
- src/utils/auth_token/org_auth_token.rs
- src/utils/auth_token/test.rs
- tests/integration/_cases/org_tokens/url-mismatch-empty-token.trycmd
- tests/integration/org_tokens.rs
With this change, the CLI will treat an org auth token that specifies an empty URL the same way as an org auth token that is not specifying a URL at all.
We implemented this change in behavior by changing the type of the `url` in the `AuthTokenPayload` from an `Option<String>` to a `String`. In cases where the `url` previously would have been set to `None`, the `url` will now be set to an empty string. Uses of the `AuthTokenPayload`'s `url` field have been updated to treat empty strings the way they previously treated `None` values.
Fixes GH-1913
> Prefer `--url` argument over empty auth token URL

- src/api.rs
- src/commands/debug_files/upload.rs
- src/commands/upload_proguard.rs
- src/utils/android.rs
- tests/integration/_cases/upload_proguard/upload_proguard-help.trycmd
Turns out this API has been deprecated and stubbed out for 5 years now, so it does not make any sense calling it.
See: https://github.com/getsentry/sentry/blob/cd404411c7b52154f5aca73af93e74b908b3ff27/src/sentry/api/endpoints/debug_files.py#L374-L383
I left the PList / Manifest parsing in there for now, as it does validate these files and throws errors. However that can probably also be removed, please advise.
> Remove `dsyms/associate` API usage

- src/utils/xcode.rs
Enabled users to share background logs with us.
Help debug the following issues:
- https://github.com/getsentry/sentry-cli/issues/1895
- https://github.com/getsentry/sentry-cli/issues/1915
> feat(xcode): Print redirected output file path when going to the background

- Cargo.lock
- Cargo.toml
- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-help.trycmd
This PR adds the `--failure-issue-threshold` and `--recovery-threshold` command line arguments. These control the number of consecutive failed cron checkins that trigger issue creation, and the number of consecutive successful cron checkins that trigger issue resolution, respectively.
Fixes GH-1919
> feat(crons): New monitor configuration options

- src/api.rs
- src/commands/deploys/new.rs
This commit fixes the `deploys new` command to use the `--project` argument. Previously, the `--project` argument was ignored; now, any projects specified with the `--project` argument are sent to Sentry in the request that creates the deploy ([relevant API docs](https://docs.sentry.io/api/releases/create-a-new-deploy-for-an-organization/)).
ref #1927
> fix(deploys): Use `--project` argument

- .github/workflows/ci.yml
We should lint without `actions-rs`. `actions-rs` is unmaintained, and we can call the necessary Cargo commands directly. `cargo clippy` occasionally fails when run with `actions-rs` even though it does not fail when run locally. Running the Cargo commands directly appears to fix the problem.
> ci: Lint without `actions-rs`

- .craft.yml
- .github/workflows/ci.yml
Reverts getsentry/sentry-cli#1779
We previously disabled PyPI releases since they kept failing. This PR re-enables them so we can check whether the problem still exists.
ref #1931
> meta: Re-enable Python releases

- .craft.yml
Reverts getsentry/sentry-cli#1932, because releasing with Python releases enabled [still fails](https://github.com/getsentry/publish/actions/runs/7872017223/job/21476396698)
> meta: Revert "meta: Re-enable Python releases"

- src/api.rs
- src/commands/deploys/new.rs
This reverts commit e11e231bb6b59fb3c5c5e6a235bbe93151bad129, which appears to be causing issues for some users (see #1939)
> fix(deploys): Revert "fix(deploys): Use `--project` argument (#1930)"

- src/api.rs
We don't call this method anywhere. The CLI compiles without it, so let's delete it!
> ref: Delete dead code

- src/api.rs
- src/commands/files/delete.rs
For some reason, until now, 404 errors received special treatment when running the `sentry-cli files delete --all` command. Therefore, if for whatever reason, the files could not be deleted due to a 404 error, the command would fail silently. The only indication that anything went wrong would be that the "All files deleted" message would not be printed.
Instead, it would make more sense to print the error message from the Sentry API and fail with a nonzero status, since the CLI has likely failed to accomplish what the user intended for it to accomplish when running the command.
Or, is there any reason why we need to keep the special logic for 404 errors around?
> fix(files): Fail when deleting all files fails with 404 error

- src/api.rs
We removed `Api::reset` way back in #489. We should delete this comment that continues to reference `Api::reset`, since it is clearly inaccurate.
> docs: Remove outdated comment

- src/api.rs
Most of the low-level Api functions are never called outside `api.rs`, yet we still label them as public functions. Let's make all the low-level Api functions only called in `api.rs` private, since we should anyways probably be using the high-level functions.
> ref: Privatize most low-level api functions

- src/commands/react_native/xcode.rs
- tests/integration/_cases/react_native/xcode-upload-source-maps-invalid-plist.trycmd
- tests/integration/_cases/react_native/xcode-upload-source-maps-release_and_dist_from_env.trycmd
- tests/integration/_fixtures/react_native/react-native-xcode-bundle.js
- tests/integration/_fixtures/react_native/react-native-xcode-bundle.js.map
- tests/integration/_fixtures/react_native/react-native-xcode.sh
- tests/integration/react_native/mod.rs
- tests/integration/react_native/xcode.rs
- this fix enables a workaround for https://github.com/getsentry/sentry-cli/issues/1936
If users use debug IDs and auto-release reading is disabled, we don't have to read and part Info.plist.
The same applies when users use ENV to set release and dist
> fix(xcode): Only parse Plist when required during RN source maps upload

- src/utils/sourcemaps.rs
- tests/integration/_cases/react_native/xcode-upload-source-maps-release_and_dist_from_env.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-file-hermes-bundle-reference-debug-id.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-file-ram-bundle.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-indexed-ram-bundle.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-some-debugids.trycmd
The distinction between "Scripts" and "Minified Scripts" is arbitrary. #1958 already eliminates the distinction for `sourcemaps inject`, and since the same code is also used to distinguish between files to output as "Scripts" and "Minified Scripts," merging #1958 already will cause the two sections to merge in the `sourcemaps upload` output.
However, with #1958, the two sections are merged as "Minified Scripts." If this PR is applied along with #1958 (which is my intention), it will cause the two sections to be merged as "Scripts." However, this PR is also completely independent of #1958 – applied alone, it will have the same effect of merging the "Minified Scripts" and "Scripts" sections of the sourcemaps upload report output under "Scripts."
> fix: Merge "Scripts" and "Minified Scripts" under sourcemaps upload report

- tests/integration/_cases/react_native/xcode-upload-source-maps-release_and_dist_from_env.trycmd
The desired behavior of the command being tested is different from what the test specifies. This PR adds a comment to clarify the situation.
Ref #1963
> Add clarifying comment to RN sourcemaps upload test

- CHANGELOG.md
- src/api.rs
- src/commands/monitors/run.rs
- tests/integration/_cases/monitors/monitors-run-help.trycmd
- tests/integration/_cases/monitors/monitors-run-token-auth-win.trycmd
- tests/integration/_cases/monitors/monitors-run-token-auth.trycmd
We brought this back in GH-1634, since unfortunately at the time we had many customers still using the legacy check-in endpoints.
We've just disabled the legacy endpoints as of [0] and will be removing them completely with [1]. This means the token-auth based version of the monitors run command will no longer work.
Unfortunatly we did claim that we would remove these *only in the next major version*
> Token auth is deprecated for cron monitor checkins and will be removed in the next major version.
> Please use DSN auth.
This was unfortuantely probably a lie since removing these endpoints is something we commited to at the beginning of Q1, and it's unlikely we're going to release a new major just for this
[0]: https://github.com/getsentry/sentry-options-automator/pull/851
[1]: …
> feat(crons): Fully drop auth-token based check in support

- src/utils/dif_upload.rs
- src/utils/fs.rs
A new Rust version introduced some new Clippy lints, which are now blocking PRs from merging since our code was violating the new lints. This PR fixes those lints.
> ref: Fixed new Clippy errors

- src/main.rs
- src/utils/system.rs
The default ctrl-c handling should be sufficient, since we don't perform any clean-up logic on ctrl-c. The only change in behavior following this change is that we will no longer print "Interrupted" when ctrl-c is pressed; however, this is a small change that likely most users will not even notice.
> ref: Remove custom ctrl-c handling code

- .github/workflows/ci.yml
We should run Clippy only with the default features. Our features either do nothing (`with_crash_reporting`) or disable compilation of code (`managed`). Therefore, somewhat unintuitively, enabling all features leads to the `update` and `uninstall` command code to not be linted, since these modules are excluded with the `managed` feature. Linting with the default feature set ensures all code is linted.
Partially unblocks #1992
> ci: Run Clippy with default features

- src/api.rs
- src/commands/upload_proguard.rs
- src/utils/auth_token/org_auth_token.rs
- src/utils/dif_upload.rs
When using org auth token authentication, we now direct any API requests to the `projects/{}/{}/files/dsyms/` endpoint directly to the region URL encoded in the token. We only do this when the URL is configured to `https://sentry.io`. For other authentication methods, we default to the old behavior, and log an info message to inform the user that the default URL was used for the upload.
This PR implements part of what is required by #1990. The next step will be to use the region URL when a user auth token is used.
> feat(api): `files/dsyms/` hits org auth token's region URL

- src/main.rs
The Sentry CLI is not a library, and we probably don't need a comment for our 1-line `main` function.
> docs: Remove inaccurate and unnecessary comments

- .vscode/settings.json
Four spaces is [Rust's default](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#tab_spaces) and what we use in basically everywhere in the codebase. No clue why we have the tab size set to 2 here.
> meta(vscode): Change editor tab size to 4

- src/api/mod.rs
- src/api/pagination.rs
Simplifies pagination logic by removing result that never results in error, and introducing new `next_pagination_cursor` convenience method. Tests added in #2015.
ref #2008
> ref(api): Simplify pagination code

- src/api/connection_manager.rs
- src/api/mod.rs
> ref(api): Split `CurlConnectionManager` into its own submodule

- src/api/connection_manager.rs
- src/api/mod.rs
By using `Infallible`, the type signature guarantees an error can never occur. Depends on #2016. 
ref #2008
> ref(api): Change connection manager error to `Infallible`

- src/api/errors/mod.rs
- src/api/mod.rs
This commit adds a new submodule to the API module, `errors`, which contains error types. Future PRs will split the `errors` module into submodules for each error type.
ref #2008
> ref(api): Errors submodule

- src/api/mod.rs
This change maintains consistency with other submodule imports
> ref(api): Remove `self` from error import

- src/config.rs
When a user sets up a project in xcode, e.g., by using the wizard, the .sentryclirc config is created in the project folder. However, when this file isn't included in the Input Files of the Xcode script for uploading debug files, an error is thrown  in Xcode which isn't very clear. This commit improves that error message by specifying what the user needs to do.
Fixes GH-1924
> fix(xcode): Improve Xcode error msg when config load fails

- src/commands/debug_files/check.rs
- tests/integration/_cases/debug_files/debug_files-check-directory.trycmd
- tests/integration/debug_files/check.rs
See #2033.
Currently, the `debug-files check` command only supports checking individual files. However, the error message we emit when passing a directory is a very vague `error: Unsupported file`. This change improves the error message. We should still consider #2033's suggestion of supporting recursive search through directories for this command.
> Improve error message when we pass a directory to `debug-files check`

- src/commands/react_native/xcode.rs
- src/config.rs
- src/utils/ui.rs
Fixes three new Clippy lints, added in Rust 1.78.0. See the three individual commits for links to the lints' documentation.
> Fix new Clippy lints

- src/api/mod.rs
- src/commands/files/upload.rs
- src/utils/chunks.rs
- src/utils/file_upload.rs
- src/utils/progress.rs
This code is more closely related to the utils module's progress bar code than to the api code, so we should move it there. 
Ref https://github.com/getsentry/sentry-cli/issues/2008
> Split out progress bar logic from API

- Cargo.lock
Update `curl-sys` to the latest version to avoid crashing on macOS Sonoma.
Fixes #1802
> build: Update `curl-sys`

- src/api/data_types/chunking/artifact.rs
- src/api/data_types/chunking/compression.rs
- src/api/data_types/chunking/dif.rs
- src/api/data_types/chunking/file_state.rs
- src/api/data_types/chunking/hash_algorithm.rs
- src/api/data_types/chunking/mod.rs
- src/api/data_types/chunking/upload/capability.rs
- src/api/data_types/chunking/upload/mod.rs
- src/api/data_types/chunking/upload/options.rs
- src/api/data_types/mod.rs
- src/api/mod.rs
- Create a new `data_types` submodule under the `api` module.
- Crate a `chunking` submodule under the `data_types` module.
- Move all data types related to chunking from `src/api/mod.rs` to the `chunking` submodule, splitting their definitions further into submodules under `chunking`.
This PR only moves existing code, adding `mod` and `use` statements and adjusting visibility as needed. No other modifications were made.
Ref #2077
> ref(api): Move chunk data types to submodule

- Cargo.toml
`curl` had already been updated to `0.4.44` in `Cargo.lock`; this commit updates the dependency in `Cargo.toml` to match.
ref #2097
> build: Bump `curl` to `0.4.46` in `Cargo.toml`

- src/utils/auth_token/test.rs
- src/utils/auth_token/user_auth_token.rs
https://github.com/getsentry/sentry/pull/68148 changed user auth tokens, so that they now start with a `sntryu_` prefix. While the CLI correctly handles these new tokens, the CLI issued a warning when using these new format tokens.
This PR updates the CLI's auth token parsing logic to recognize the new user auth token format (in addition to the old format), so that the warning is no longer issued.
> feat(auth): Recognize new format user tokens

- src/api/errors/api_error.rs
- src/config.rs
- src/utils/args.rs
- tests/integration/_cases/debug_files/debug_files-bundle-jvm-help.trycmd
- tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
- tests/integration/_cases/deploys/deploys-help.trycmd
- tests/integration/_cases/deploys/deploys-no-subcommand.trycmd
- tests/integration/_cases/events/events-help.trycmd
- tests/integration/_cases/events/events-list-help.trycmd
- tests/integration/_cases/events/events-no-subcommand.trycmd
- tests/integration/_cases/issues/issues-help.trycmd
- tests/integration/_cases/issues/issues-list-help.trycmd
- tests/integration/_cases/monitors/monitors-list-help.trycmd
- tests/integration/_cases/projects/projects-help.trycmd
- tests/integration/_cases/projects/projects-list-help.trycmd
- tests/integration/_cases/projects/projects-no-subcommand.trycmd
- tests/integration/_cases/releases/releases-help.trycmd
- tests/integration/_cases/releases/releases-new-help.trycmd
- tests/integration/_cases/releases/releases-no-subcommand.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-no-subcommand.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-resolve-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-help.trycmd
- tests/integration/_cases/upload_dif/upload_dif-help.trycmd
- tests/integration/_cases/upload_dsym/upload_dsym-help.trycmd
- tests/integration/_cases/upload_proguard/upload_proguard-help.trycmd
With the API changes [we made to support ids as well as slugs](https://vanguard.getsentry.net/p/clyoo0m4a000u12nb53fkxanl), we get the added bonus that our CLI can also support ids.
Turns out the CLI also uses a couple endpoints which passed project slug in the body parameter, so we also had to update them:
https://github.com/getsentry/sentry/pull/74232
https://github.com/getsentry/sentry/pull/74371
With these prs, all the endpoints the CLI uses have ID support.
@szokeasaurusrex  and I had a conversation about how we would like to roll this change out in an [earlier closed pr](https://github.com/getsentry/sentry-cli/pull/2098), and decided that once we support ids in all the CLI commands, we can change all the help strings at once, which is what i am doing here.
> docs(id-support): Document that -p and -o arguments accept slugs and IDs

- js/releases/index.js
- src/api/mod.rs
- src/commands/sourcemaps/explain.rs
- src/utils/chunks.rs
- src/utils/dif_upload.rs
- src/utils/file_upload.rs
- src/utils/http.rs
- src/utils/system.rs
Found via `typos --hidden --format brief`
> docs: Fix typos

- Cargo.lock
- src/utils/file_upload.rs
`symbolic-debuginfo` version 12.8.0 is the latest version excluding https://github.com/getsentry/symbolic/pull/816, which caused a regression in `sentry-cli`.
Fixes https://github.com/getsentry/sentry-cli/issues/2107
> build: Downgrade symbolic-debuginfo to 12.8.0

- Cargo.lock
- src/utils/file_upload.rs
Prompted by #2107 and #2108.
This matches on the error kind returned by `SourceBundleWriter::add_file` and silently skips `ReadFailed` errors, which happen on files that aren't valid UTF8. Errors like this are likely caused by asset files that weren't intended to be included in the bundle anyway. It might also make sense to log that we're skipping the file, though.
> fix(sourcebundle): Skip non-UTF8 files

- .vscode/settings.json
- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-inject.trycmd
- tests/integration/_fixtures/inject/server/dummy_hosted.js
- tests/integration/_fixtures/inject/server/dummy_hosted_full.js
- tests/integration/_fixtures/inject/server/dummy_hosted_full.js.map
Applies a heuristic to guess that a sourcemap URL is a remote URL path (without scheme and domain):
1. The string starts with `/`
2. The string is not a path to an existing local file
Fixes #1870.
> Fall back to co-location heuristic if sourcemap url appears remote

- src/api/errors/api_error.rs
> Improve "not found" error messages

- Cargo.lock
- Cargo.toml
- src/commands/derive_parser.rs
- src/commands/mod.rs
- src/utils/auth_token/auth_token_impl.rs
- src/utils/auth_token/test.rs
- src/utils/value_parsers.rs
- tests/integration/_cases/token_validation/warn-invalid-auth-token.trycmd
Separate logic for issuing the invalid auth token format validation warning from the parsing logic. This will allow us in the future to test whether a certain string might be an auth token without logging a warning.
> ref(token): Separate validation warning from parsing

- src/commands/mod.rs
- src/utils/auth_token/auth_token_impl.rs
- src/utils/auth_token/mod.rs
- src/utils/auth_token/org_auth_token.rs
- src/utils/auth_token/user_auth_token.rs
- tests/integration/_cases/token-redacted.trycmd
- tests/integration/mod.rs
Redact anything that might be an auth token when logging the command line arguments to console. This occurs only when the log level is set to `info` or `debug`; the default is `warn`.
> fix: Redact auth tokens when logging CLI args

- Cargo.lock
- Cargo.toml
- src/api/mod.rs
- src/config.rs
- src/utils/auth_token/auth_token_impl.rs
- src/utils/auth_token/org_auth_token.rs
- src/utils/auth_token/test.rs
- src/utils/auth_token/user_auth_token.rs
- tests/integration/_cases/token-redacted.trycmd
- tests/integration/mod.rs
Using the secrecy crate prevents the auth token from accidentally being leaked if we log the `AuthToken` struct.
> ref(token): Use secrecy crate to store auth token

- src/commands/mod.rs
- src/utils/auth_token/auth_token_impl.rs
- src/utils/auth_token/mod.rs
- src/utils/auth_token/redacting.rs
- tests/integration/_cases/token-redacted-2.trycmd
- tests/integration/_cases/token-redacted.trycmd
- tests/integration/mod.rs
#2115 aimed to redact auth tokens when logging the arguments to the CLI. Although that change addressed some cases where auth tokens were passed as a CLI argument, not all cases were addressed. For example, the following was redacted properly with #2115:
```sh
sentry-cli --auth-token this-gets-redacted --log-level=info info
```
But, the following was not:
```sh
sentry-cli --auth-token=this-does-not-get-redacted --log-level=info info
```
The difference is that in the second example, the auth token is passed with `--auth-token=token` rather than separated by whitespace `--auth-token token`.
This change improves the redacting so that auth tokens passed like `--auth-token=token` are also redacted. The change also redacts any non-whitespace-containing substrings starting with `sntrys_` or …
> fix: Improve token redaction in CLI arg logging

- .github/workflows/build.yml
This reverts commit d0e87177afc988d0193df75f4dc234ec637fb7da, which bumped `upload-artifact` to version 4.
Due to https://github.com/actions/upload-artifact/issues/478, `upload-artifact` version 4 is incompatible with our current release proces. This change is blocking us from successfully creating [release builds](https://github.com/getsentry/sentry-cli/actions/runs/10213847803).
As a workaround, we will revert this change for now.
> meta: Revert upload-artifact bump (#2110)

- Cargo.lock
- Cargo.toml
Fix a wasm too big name section and legacy exceptions support.
It should fix this issue: https://github.com/getsentry/symbolic/issues/848
Related to https://github.com/getsentry/symbolic/pull/853
> build: Update symbolic dependency to 12.10.0

- README.md
The version pin we include in our example for pinning the CLI version is quite old. Let's increase it to the latest version.
Perhaps, in the future, we can automate this change in our release pipeline. For now, though, it is probably enough to make sure we periodically update this, especially after any important fixes.
> meta: Update version pin README.md

- src/commands/mod.rs
- src/config.rs
- tests/integration/_cases/org_tokens/url-mismatch.trycmd
Previously, we would error when the auth token's embedded URL differed from the manually provided URL. Now, we instead always use the token URL and log a warning.
Closes [#2104](https://github.com/getsentry/sentry-cli/issues/2104)
> feat: Prefer org auth token URL over manually provided URL

- .npmignore
- bin/sentry-cli-dev
- src/commands/mod.rs
- This RP fixes https://github.com/getsentry/sentry-react-native/issues/4036
The change enables wrapped call to execute other child calls.
This is need due to recent RN 0.75 change.
- https://github.com/facebook/react-native/pull/44721/files#diff-16a358d6a9dea8469bfdb899d0990df1c32b8c3b1149c86685bec81f50bd24be
`sentry-cli-fake-node react-native/cli.js config` is called by `sentry-cli-fake-node @react-native-community/cli bundle`
For this we need to allow the recursive wrapped calls. This is currently not an issue as the wrapped call doesn't execute Sentry-CLI binary commands.
---
The added `[sentry-cli-dev](https://github.com/getsentry/sentry-cli/pull/2131/files#diff-03f1f612bbc5cf7f68294e8711ae18b595e02639a86cf9c3c4e633576ca1836c)` makes testing dev build easier in node environments.
> fix(react-native): Fix RN 0.75 node binary build fail

- src/utils/sourcemaps/inject.rs
- tests/integration/_fixtures/inject_bundlers/esbuild/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/esbuild/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/rollup/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/rollup/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/rspack/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/vite/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/vite/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/webpack/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/webpack/iife.js.expected
This PR makes a small change to the JavaScript snippet that's injected into user files to set the debugId.
Previously, we'd instantiate `new Error` in the script, which usually implicitly instantiates `globalThis.Error`. However, if users or frameworks would create their own `Error` class in the very file where the debugId snippet is instantiated, `new Error` would of course take the user-created class rather than the global one. To fix this, this PR now explicitly instantiates the `globalThis.Error` class.
fixes: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/593
> fix(debugIds): Always instantiate global `Error` class in debugId injection snippet

- Cargo.lock
- Cargo.toml
Incorporate upstream bugfix from `symbolic` `12.10.1`.
Fixes #2124
> build: Bump symbolic to `12.10.1`

- src/api/errors/api_error.rs
- src/api/mod.rs
- src/utils/http.rs
> feat(proguard): Retry `upload-proguard` on 507 status

- .github/workflows/build.yml
Since we use `actions/upload-artifact@v3`, we cannot upgrade to `actions/download-artifact@v4` quite yet.
> ci: Downgrade to `actions/download-artifact@v3`

- Cargo.lock
- Cargo.toml
- src/commands/debug_files/bundle_sources.rs
- src/utils/dif_upload.rs
When a file has an invalid (non-UTF-8) encoding, it is skipped from being added to source bundles. Previously, the file was silently skipped. Now, we log when we skip a file.
The logs are emitted at the `info` level, which is hidden by default (default log level is `warn`). To see these logs, users will need to set the log level, for example by passing `--log-level=info`.
Fixes #2135
Fixes #2147
> feat: Log when file not added to source bundle

- src/commands/send_metric/mod.rs
- tests/integration/_cases/help/help-windows.trycmd
- tests/integration/_cases/help/help.trycmd
- tests/integration/_cases/send_metric/send_metric-distribution-help.trycmd
- tests/integration/_cases/send_metric/send_metric-gauge-help.trycmd
- tests/integration/_cases/send_metric/send_metric-help.trycmd
- tests/integration/_cases/send_metric/send_metric-increment-help.trycmd
- tests/integration/_cases/send_metric/send_metric-increment-unsuccessful-api-call.trycmd
- tests/integration/_cases/send_metric/send_metric-no-subcommand.trycmd
- tests/integration/_cases/send_metric/send_metric-set-help.trycmd
> ref(metrics): Deprecate `send-metric` commands

- src/api/mod.rs
- src/commands/deploys/new.rs
Previously, we ignored the `--project` arguments passed to the `sentry-cli deploys new` command. Regardless of whether any `--project` was provided, the deploy was created for all projects associated with the given release.
Now, we respect the `--project` argument. If provided, we only create the deploy for the project(s) specified. If omitted, the deploy is created for all projects associated with the release, as previously.
Fixes #2156
> fix(deploys): Honor `--project` in `deploys new` subcommand

- src/api/data_types/deploy.rs
- src/api/data_types/mod.rs
- src/api/mod.rs
- src/commands/deploys/new.rs
- Use `Cow<str>` rather than `String` in the `Deploy` struct to avoid allocations where unnecessary
- Separate `Deploy` struct into separate module
I have split this PR into two commits which separately implement each of the above changes. It might be easier to review the commits individually.
ref #2077
> Refactor deploys

- src/commands/debug_files/upload.rs
- src/commands/react_native/xcode.rs
- src/config.rs
- src/utils/xcode.rs
- tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
- tests/integration/_cases/upload_dif/upload_dif-help.trycmd
- tests/integration/_cases/upload_dsym/upload_dsym-help.trycmd
Perform all uploads from Xcode in the foreground. The new behavior is equivalent to the old `--force-foreground` behavior.
Since uploads are now always executed in the foreground, (soft) deprecate the `--force-foreground` option by hiding it in the command help text. The `--force-foreground` option no longer has any effect, but passing it will continue to be possible at least until the next major release to keep the API backwards compatible.
Background functionality is completely removed from Sentry-CLI with this change.
Closes #2166
Fixes #2148
> feat(xcode): All uploads in foreground

- src/commands/monitors/run.rs
The `--auth-token` argument is hidden from the `sentry-cli monitors run` subcommand since the command uses DSN authentication, however passing the argument is still possible (it is simply ignored).
However, providing this argument causes a panic with a not-very-user-friendly message, since the argument was defined here without the auth token parser, and we attempt to read the auth token as an AuthToken.
This PR fixes the bug.
Fixes #2170
> fix(crons): Don't panic when passing `--auth-token`

- src/utils/system.rs
- tests/integration/_cases/debug_files/debug_files-bundle-jvm-output-is-file.trycmd
- tests/integration/_cases/info/info-no-token-backtrace.trycmd
- tests/integration/_cases/releases/releases-delete-active.trycmd
- tests/integration/_cases/send_metric/send_metric-increment-unsuccessful-api-call.trycmd
- tests/integration/info.rs
The `anyhow` crate we use for error handling adds stack backtraces errors whenever [certain standard environment variables](https://doc.rust-lang.org/std/backtrace/index.html#environment-variables) are set (e.g. when `RUST_BACKTRACE=1`).
Modify our error-printing logic to include these stack backtraces when printing errors that crash Sentry CLI, so that users can add this information to bug reports.
Closes #2187
> feat(errors): Print backtrace when `RUST_BACKTRACE=1`

- src/commands/mod.rs
`commands::main` does not return because it explicitly calls `std::process::exit`. Update `commands::main`'s function signature to indicate this.
> ref: Indicate that `commands::main` does not return

- src/main.rs
Sentry CLI's `main` function calls `commands::main`, which does not return, since it calls `std::process::exit`. Update the function signature to reflect this.
Depends on #2191
> ref: Update `main` to indicate it does not return

- Cargo.lock
- Cargo.toml
This pulls in https://github.com/getsentry/symbolic/pull/870.
> deps: Update symbolic to 12.12.0

- src/api/mod.rs
We added a blanket `allow(dead_code)` for the entire api module in #2096 because of some new clippy lints which were failing.
Here, we remove the blanket `allow(dead_code)` and only allow dead code for the specific lines where it occurs. It might not be possible to remove these because serde might rely on their presence.
> ref(api): Only allow dead code where needed

- src/api/data_types/chunking/upload/options.rs
Remove the blanket `allow(dead_code)` in `api::data_types::chunking::upload::options`
> ref(api): Remove blanket `allow(dead_code)`

- src/api/mod.rs
- src/utils/fs.rs
- src/utils/progress.rs
- src/utils/update.rs
Instead, mark all code that is not needed for the `managed` build with `cfg(not(feature = "managed"))`.
> ref(utils): Remove `allow(dead_code)` from update utils

- CONTRIBUTING.md
- src/api/mod.rs
- tests/integration/mod.rs
We do not appear to use the output generated by SENTRY_DUMP_RESPONSE anywhere. The code only appears to be there for debugging/development purposes, so developers can add it back as needed. No need to ship this code to end users.
> ref: Remove `SENTRY_DUMP_REPONSE` environment variable

- src/api/mod.rs
This dead code caused a CI linter failure in `master`. Likely, we did not update #2212 with the changes from #2213 before merging.
> ref(api): Remove dead code

- tests/integration/mod.rs
- tests/integration/test_utils/env.rs
- tests/integration/test_utils/mod.rs
As a part of #2194, I intend to introduce the [`assert_cmd` crate](https://docs.rs/assert_cmd/latest/assert_cmd/) to have more control over how the assertions for the chunk upload tests are run. This control would be difficult to achieve with `trycmd`.
So, here, I am splitting off the logic for setting environment variables to make it also reusable for `assert_cmd` tests
> ref(tests): Decouple test env vars from trycmd code

- Cargo.lock
- Cargo.toml
- tests/integration/debug_files/upload.rs
- tests/integration/test_utils/env.rs
Add an integration test for the `debug-files upload` command, which ensures that given a certain file, the expected initial request to the assemble endpoint is made to the Sentry server. Unlike existing tests, this test primarily does not serve to validate command output, but rather to ensure other behavior (in this case, that a specific HTTP request is made).
Also, add the [`assert_cmd`](https://docs.rs/assert_cmd/latest/assert_cmd/) crate as a dev dependency. The crate provides an interface which allows more fine-grained control over how an individual integration test is run compared with the `trycmd` crate we currently use everywhere. `assert_cmd` will help us write better integration tests for chunk uploading, which not only assert command output, but also ensure that the correct data …
> test(debug-files): Add test for assemble endpoint call

- .github/workflows/codeql-analysis.yml
Currently, this action only runs on PRs against master, which is a problem when we have a stack of PRs, which are originally opened against a branch other than `master`, but later are changed to have a base of `master` when the parent branch is merged into `master`.
> ci: Run codeql-analysis on all PRs

- src/utils/dif.rs
- tests/integration/_cases/debug_files/debug_files-check-no-file-allow-failure-env-windows.trycmd
- tests/integration/_cases/debug_files/debug_files-check-no-file-allow-failure-env.trycmd
- tests/integration/_cases/debug_files/debug_files-check-no-file-allow-failure-windows.trycmd
- tests/integration/_cases/debug_files/debug_files-check-no-file-allow-failure.trycmd
- tests/integration/_cases/debug_files/debug_files-check-no-file-windows.trycmd
- tests/integration/_cases/debug_files/debug_files-check-no-file.trycmd
This removes some redundant `map_err` calls and adds context to `DifFile::open_path`.
> fix: Improve error handling in dif.rs

- tests/integration/bash_hook.rs
`trycmd` is [smart enough](https://docs.rs/trycmd/latest/trycmd/#getting-started) to enumerate all of these test cases
> test: Batch `bash_hook` tests together

- tests/integration/mod.rs
- tests/integration/react_native/mod.rs
- tests/integration/react_native/xcode.rs
We can just mark the entire module as macos-only
> test(react_native): Bubble up `target_os`

- tests/integration/test_utils/env.rs
Some of our `trycmd` tests assume that no backtrace is printed in the test commands output, even when an error is supposed to occur. `RUST_BACKTRACE=0` appears to be set in CI, but this becomes a problem running tests locally, where tests sometimes fail when the local environmnent has `RUST_BACKTRACE=1`.
Note that backtraces are still logged tracing back to the error that caused the test failure. But, if we are testing that a specific command which we expect to fail has a certain output, this change ensures that regardless of the outside environment, we don't get a backtrace _in the test output_, as this could fail the test.
> test: Run `trycmd` tests with `RUST_BACKTRACE=0`

- tests/integration/mod.rs
- tests/integration/test_utils/mocking.rs
- tests/integration/test_utils/mod.rs
Done in preparation for a refactor of how we construct mock endpoints
> ref(test): Move mock endpoint code to module

- tests/integration/test_utils/mocking.rs
This will allow us to change the implementation details of the struct.
> ref(test): Privatize struct fields of `EndpointOptions`

- tests/integration/debug_files/upload.rs
- tests/integration/deploys/list.rs
- tests/integration/deploys/new.rs
- tests/integration/events.rs
- tests/integration/info.rs
- tests/integration/issues/list.rs
- tests/integration/mod.rs
- tests/integration/monitors.rs
- tests/integration/organizations.rs
- tests/integration/projects.rs
- tests/integration/releases/delete.rs
- tests/integration/releases/finalize.rs
- tests/integration/releases/info.rs
- tests/integration/releases/list.rs
- tests/integration/releases/new.rs
- tests/integration/send_envelope.rs
- tests/integration/send_event.rs
- tests/integration/send_metric.rs
- tests/integration/sourcemaps/explain.rs
- tests/integration/sourcemaps/upload.rs
- tests/integration/test_utils/mocking.rs
- tests/integration/test_utils/mod.rs
- tests/integration/upload_proguard.rs
The new name describes more accurately what the struct now does.
> ref(test): Rename `EndpointOptions` to `MockEndpointBuilder`

- tests/integration/test_utils/mock_common_endpoints.rs
`.expect` is equivalent to calling `.expect_at_most` and `.expect_at_least` with the same value
> ref(tests): Simplify `mock_common_upload_endpoints`

- tests/integration/test_utils/mock_common_endpoints.rs
- tests/integration/test_utils/mock_endpoint_builder.rs
Separate the logic for configuring the common upload mocks and the logic for actually creating the mocks
> ref(tests): `mock_common_endpoints` refactor

- tests/integration/debug_files/upload.rs
Use the `TestManager` in the recently-added `ensure_correct_assemble_call` test. In the future, we would plan to add `assert_cmd` support to `TestManager`, which would make the remaining custom logic in this test redundant, but we will wait until we have a better idea of how this should look like. For now, this change should make #2223 easier to implement
> ref(test): Use `TestManager` in new chunk upload test

- tests/integration/_responses/debug_files/get-chunk-upload.json
The mock response we use for the chunk upload options contains `kamil-test` as the org for the chunk uploading URL, when elsewhere in tests, we typically use the `wat-org` org. So, change the URL accordingly.
> ref(test): Change chunk upload options org

- tests/integration/debug_files/upload.rs
- tests/integration/deploys/list.rs
- tests/integration/deploys/new.rs
- tests/integration/events.rs
- tests/integration/info.rs
- tests/integration/issues/list.rs
- tests/integration/monitors.rs
- tests/integration/organizations.rs
- tests/integration/projects.rs
- tests/integration/releases/delete.rs
- tests/integration/releases/finalize.rs
- tests/integration/releases/info.rs
- tests/integration/releases/list.rs
- tests/integration/releases/new.rs
- tests/integration/send_envelope.rs
- tests/integration/send_event.rs
- tests/integration/send_metric.rs
- tests/integration/sourcemaps/explain.rs
- tests/integration/sourcemaps/upload.rs
- tests/integration/test_utils/mock_common_endpoints.rs
- tests/integration/test_utils/mock_endpoint_builder.rs
- tests/integration/upload_proguard.rs
`mockito`'s default mock response status is `200`. Since most of our mocks reply with `200`, let's also use this default in our mocks.
> ref(test): Make mock builder status default to `200`

- tests/integration/test_utils/mock_endpoint_builder.rs
Change the `body` parameter of `with_response_body` to match the parameter that `mockito` takes. Also, add a `'static` bound because the builder closure can only capture `'static` items
> ref(test): Align `with_reponse_body` parameter to `mockito`

- tests/integration/debug_files/upload.rs
- tests/integration/test_utils/mock_endpoint_builder.rs
Allow accpting any key that implements `IntoHeaderName` and any matcher taht implements `Into<Matcher>`. This is the same signature as `mockito`'s `match_header` method.
> ref(test): Broaden `with_header_matcher` types

- src/commands/upload_proguard.rs
We have some code which opens all the proguard files just to compute the SHA1 sum, which is just debug-logged and then added into a vector, which is never read from, and which is not needed for any lifetime purposes. We definitely can get rid of the vector, the debug log is also probably okay to get rid of because this information can easily be obtained using the `sha1sum` command
> ref(proguard): Delete pointless code

- src/utils/proguard_upload.rs
When chunk uploading Proguard mappings, we need to wait until the server has finished assembling the Proguard mappings. Otherwise, if the user passes an `--app-id` to the function, associating the Proguard mappings with the App ID could fail, since the server may not have assembled the Proguard file by the time we make the request to associate the App ID.
> fix(proguard): Wait until chunks are assembled

- tests/integration/debug_files/upload.rs
This line is redundant, since `env::set_all` already handles setting the auth token.
> ref(test): Remove redundant line

- src/commands/upload_proguard.rs
Likely would be better to keep this string in a constant to ensure we don't copy the wrong thing to the places where we use it
> ref(proguard): Define environment variable name in constant

- Cargo.lock
- Cargo.toml
- tests/integration/_fixtures/upload_debugid_alias/server/chunks/1.js.map
Previously parsing sourcemaps containing both `debug_id` and `debugId` would fail because the keys conflicted. This rectifies the problem by updating `symbolic` and `sourcemap`.
> fix(sourcemaps): Correctly read files with debug_id and debugId

- tests/integration/debug_files/upload.rs
- tests/integration/mod.rs
- tests/integration/test_utils/env.rs
- tests/integration/test_utils/mod.rs
- tests/integration/test_utils/test_manager.rs
This should reduce boilerplate when writing `assert_cmd` tests.
> ref(test): Introduce `assert_cmd` test manager

- src/commands/sourcemaps/explain.rs
Fix clippy lint which was initially discovered (and ignored) in #2269.
> ref(sourcemaps): Fix clippy lint

- src/utils/dif_upload.rs
- src/utils/file_upload.rs
- src/utils/fs.rs
- src/utils/proguard_upload.rs
Since we convert the argument to usize in the function anyways, it likely makes more sense for this function to explicitly take a usize. In future refactors, we can change the signatures of the functions that take the values to also take `usize`.
> ref(utils): Use `usize` in `get_sha1_checksums` signature

- src/utils/chunks/mod.rs
- src/utils/chunks/types.rs
- src/utils/dif_upload.rs
So that we can reuse the code for chunk uploading difs for other file types as well, replace the `ChunkedDifMatch` struct with a similar, generic type called `ChunkedObject`.
The code path is not fully generic yet, but it is a step in the right direction.
ref #2195
> ref(dif): Replace `ChunkedDifMatch` with generic `ChunkedObject`

- src/utils/dif_upload.rs
The new name is more specific and descriptive
We also need to change the trait so it is implemented for `&Chunked` rather than `Chunked`. Otherwise, clippy complains that `into_*` methods should take `self` rather than `&self`
> ref(dif): Rename `ToAssemble` trait

- src/utils/chunks/mod.rs
- src/utils/chunks/types.rs
- src/utils/dif_upload.rs
Rename the `Named` trait to `Assemblable`, in preparation for adding another method to get the Debug ID. We will need to be able to get the DebugID anywhere where we prepare a call to the assemble endpoint, and this is also the only place we need to have a name. So, it makes sense to have a single trait for both.
> ref(chunks): Rename `Named` trait to `Assemblable`

- src/api/data_types/chunking/dif.rs
- src/utils/chunks/types.rs
- src/utils/dif_upload.rs
- src/utils/proguard_upload.rs
Putting the hash in the `ChunkedDifRequest` allows us to avoid needing to transform objects into tuples with a `ChunkedDifRequest` and a hash. With this change, we can greatly simplify the API for creating a `ChunkedDifRequest` and an `AssembleDifRequest`
> ref(dif): Put hash in `ChunkedDifRequest`

- src/commands/upload_proguard.rs
There is no need to first open the file metadata. All the information we get from the metadata is the length, which we can already get from the `ByteView`.
>     ref(proguard): Directly open paths as `ByteView`

- src/commands/upload_proguard.rs
- src/utils/proguard/mapping.rs
- src/utils/proguard/mod.rs
- src/utils/proguard/upload.rs
- tests/integration/_cases/upload_proguard/upload_proguard-no-upload.trycmd
- tests/integration/_cases/upload_proguard/upload_proguard.trycmd
The new `ProguardMapping` type directly references the `ByteView` of the Proguard file, rather than simply storing the path to the file. This change will enable us to replace `ChunkedMapping` with `Chunked<ProguardMapping>`.
> ref(proguard): Replace MappingRef with ProguardMapping

- src/api/data_types/chunking/dif.rs
- src/utils/chunks/types.rs
- src/utils/dif_upload.rs
- src/utils/proguard/upload.rs
Also, update the `Assemblable` trait, so the `name` function returns `Cow<str>`
This refactor will allow `ChunkedDifRequest` to also store owned types for the `name`, making the type more flexible. We will use this ability when implementing `Assemblable` for `ProguardMapping`
> ref(chunks): Make `ChunkedDifRequest` take `Cow<str>` for `name`

- src/api/data_types/chunking/mod.rs
- src/api/data_types/chunking/upload/mod.rs
- src/api/data_types/chunking/upload/options.rs
- src/api/mod.rs
- src/utils/chunks/mod.rs
- src/utils/dif_upload.rs
- src/utils/file_upload.rs
- src/utils/proguard/upload.rs
This rename makes it clearer that the server sets the `ChunkedUploadServerOptions`. It also will allow `ChunkedUploadOptions` to be used to store options that are user-configured
> ref(api): Rename `ChunkedUploadOptions` to indicate they are set by server

- src/utils/proguard/mapping.rs
The leading `/` is [required](https://github.com/getsentry/sentry/blob/e5a117971a55245eadbc2f525dde11f93f10ef57/src/sentry/models/debugfile.py#L51) for Sentry to identify an uploaded file as a Proguard file.
This bug was initially created in #2296, which has fortunately not been released yet.
> fix(proguard): Add leading `/` to uploaded Proguard file name

- src/utils/sourcemaps/inject.rs
- tests/integration/_fixtures/inject_bundlers/esbuild/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/esbuild/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/rollup/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/rollup/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/rspack/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/vite/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/vite/iife.js.expected
- tests/integration/_fixtures/inject_bundlers/webpack/cjs.js.expected
- tests/integration/_fixtures/inject_bundlers/webpack/iife.js.expected
Similar to https://github.com/getsentry/sentry-javascript-bundler-plugins/pull/636 we want to write debug IDs to `globalThis` for runtimes that do not support the other global objects.
> feat(debugid): Update debug ID snippet to write on `globalThis` when available

- .github/workflows/release.yml
More details: https://www.notion.so/sentry/DACI-Replace-GitHub-bot-accounts-with-GitHub-Apps-getsentry-release-15109965d1204a91b9be71c49e8b66e0?pvs=4
> ci(release): Replace release bot with GH app

- src/utils/chunks/upload.rs
- src/utils/dif_upload.rs
This requires adding `should_wait` and `max_wait` functions to the `ChunkOptions` trait.
> ref(dif): Genericize `poll_assemble`

- src/commands/debug_files/upload.rs
- src/utils/dif_upload.rs
Owned string is not necesary here, and having it will make it harder to convert `DifUpload` into `ChunkOptions`
> ref(dif): Use `&str` in `DifUpload` struct

- src/utils/chunks/upload.rs
We should not mention `upload-dif` in this error message because (1) `upload-dif` is a soft-deprecated hidden alias to `debug-files upload` and (2) `poll_assemble` has now been generalized and could be used with other commands in the future.
For reason (2), this change makes the error message general rather than referring to the `debug-files upload` command.
> ref(chunks): Remove `upload-dif` reference from `poll_assemble`

- src/commands/upload_proguard.rs
- src/utils/chunks/upload.rs
- src/utils/proguard/mapping.rs
- src/utils/proguard/upload.rs
Use the existing chunked upload logic (already used for DIFs) when chunked-uploading Proguard mappings.
Closes #2195, #2196
> ref(proguard): Use existing chunked upload logic

- .cargo/config.toml
- Cargo.toml
Having `panic = "abort"` and `strip = "symbols"` makes backtraces generated with `RUST_BACKTRACE=1` completely useless in release builds.
By changing these options to `panic = "unwind"` and `strip = "debuginfo"` makes backtraces usable in release builds. This will help us debug issues we are unable to reproduce, since we can ask users to set `RUST_BACKTRACE=1` and provide the logs with this option.
This change does somewhat significantly increase release build binary size (from 7.9 MB to 13.9 MB on my system). This is likely acceptable if it improves our ability to debug problems. If folks complain, we can consider distributing a separate "stripped" binary for users sensitive to large binary size.
Closes #2200
> build: Make backtraces useable in release builds

- Cargo.toml
On my system, I obtained the smallest binary size with `opt-level = 2` (11.8 MB, versus 12.2 MB with `opt-level = "z"`).
> build: Change release `opt-level`

- src/api/mod.rs
Since we only use the `Vec` created by the `collect` in the loop below, there is no reason for the collect. Removing the collect prevents an unnecessary allocation of the `Vec`, and allows the loop instead to lazily compute the stringified chunks during iteration
> ref(api): Remove unnecessary `collect`

- src/utils/dif_upload/error.rs
- src/utils/dif_upload/mod.rs
Having a type for DIF validation errors will give us more flexible error handling abilities.
> ref(dif): Create type for DIF validation errors

- src/utils/dif_upload/error.rs
- src/utils/dif_upload/mod.rs
- tests/integration/_responses/debug_files/get-chunk-upload-small-max-size.json
- tests/integration/debug_files/upload.rs
- tests/integration/test_utils/test_manager.rs
Previously, we only logged an easy-to-miss warning when we had to skip uploading a debug file because it was too big. Now, we instead fail the entire upload loudly, to ensure users do not miss this important information.
Depends on:
- #2330 
- #2329 
Resolves #2313
> feat(dif): Fail `debug-files upload` when file is too big

- Cargo.lock
Recently, `cargo build` started failing on my local system, with an error related to `memmap2`. Upgrading the dependency to the latest version fixes the problem.
Depends on:
- #2341
> build: Update `memmap2`

- src/commands/debug_files/bundle_jvm.rs
- src/commands/files/upload.rs
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
Prevent an unnecessary copy of all sourcemap files being uploaded from being stored in memory, by using an `Arc` for the `contents` field of `SourceFile`.
Depends on:
- #2340
- #2341
Fixes #2342
> ref(sourcemaps): Reduce sourcemap upload memory usage

- src/api/data_types/chunking/compression.rs
This custom deserializer can be easily replaced with `derive(Deserialize)`.
> ref(api): Replace custom deserializer with derive

- Cargo.lock
- Cargo.toml
Symbolic version `12.13.3` includes [a change](https://github.com/getsentry/symbolic/pull/890), which will reduce the memory usage of sourcemap uploads, in some cases very significantly.
ref #2344
> build: Bump `symbolic` to `12.13.3`

- Cargo.lock
- Cargo.toml
- src/utils/system.rs
Replace the unmaintained crate `dotenv` with the maintained fork `dotenvy`.
Fixes #2350
> build: Replace `dotenv` with `dotenvy`

- src/commands/sourcemaps/upload.rs
> feat: Deprecate `--use-artifact-bundle` option

- Cargo.lock
- Cargo.toml
- src/commands/mod.rs
- src/utils/system.rs
This change improves Sentry CLI's panic hook to make panic messages more user-friendly.
The panic message generated by the hook emphasizes that panics are internal errors in the Sentry CLI, and the message directs users to our bug report issue form. The message also always includes a stack backtrace, regardless of whether `RUST_BACKTRACE` is set.
The new panic message looks like the following:
```
🔥 Internal Error in Sentry CLI 🔥
Uh-oh! 😬 Sentry CLI has just crashed due to an internal error. Please open a bug report issue at https://github.com/getsentry/sentry-cli/issues/new?template=BUG_REPORT.yml. 🐞
🔬 Technical Details 🔬
thread 'main' panicked at src/commands/sourcemaps/upload.rs:422:5:
test error
Stack Backtrace:
0: std::backtrace_rs::backtrace::libunwind::trace
at …
```
> feat: Improve custom panic hook

- src/commands/mod.rs
- tests/integration/_cases/send_envelope/send_envelope-help.trycmd
- tests/integration/_cases/send_event/send_event-help.trycmd
- tests/integration/_cases/send_metric/send_metric-distribution-help.trycmd
- tests/integration/_cases/send_metric/send_metric-gauge-help.trycmd
- tests/integration/_cases/send_metric/send_metric-help.trycmd
- tests/integration/_cases/send_metric/send_metric-increment-help.trycmd
- tests/integration/_cases/send_metric/send_metric-set-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-inject-help.trycmd
We don't need custom logic to parse the log level, `clap` can do this.
> ref: Simplify `--log-level` parsing

- .github/workflows/ci.yml
Currently, the lint action specifies `-D clippy::all`. This means that if we enable any additional lints in the code, e.g. by adding `#![warn(clippy::pedantic)]` to the `main` module, these lints will not fail CI. By specifying `-D warnings` instead, any lints we enable as warnings in code will fail CI.
> ci: Change lint action to `-D warnings`

- .github/workflows/ci.yml
- src/api/mod.rs
- src/commands/mod.rs
- src/commands/sourcemaps/resolve.rs
- src/config.rs
- src/main.rs
- src/utils/sourcemaps.rs
- src/utils/update.rs
- src/utils/value_parsers.rs
However, since fixing each existing violation would require changes to how each function is called, we hold off on fixing the violations in this PR. Instead, we `expect` the current violations individually. Future PRs will fix the existing violations.
Ref #2357
> ref: Enable `clippy::unnecessary_wraps` lint

- src/config.rs
This function does not need to return a `Result`, as it can never fail.
Ref #2357
> ref(config): Remove unneeded `Result` from `Config::from_file`

- src/commands/login.rs
- src/commands/mod.rs
- src/config.rs
Fixing the lint for `set_auth` makes `configure_auth` violate the lint, so we also fix that new violation here.
Ref #2357
> ref(config): Fix `unnecessary_wraps` lint for `set_auth`

- src/api/mod.rs
> ref(api): Make `with_retry` return `Self`

- src/api/envelopes_api.rs
- src/api/mod.rs
No need for a `Result` here.
Ref #2357
> ref: Make `Api::with_body` return `Self`

- src/commands/sourcemaps/resolve.rs
We always return the `Some` variant, so no `Option` needed here.
Ref #2357
> ref(sourcemaps): Make `lookup_pos` not return `Option`

- src/commands/react_native/appcenter.rs
- src/commands/react_native/gradle.rs
- src/commands/react_native/xcode.rs
- src/commands/sourcemaps/inject.rs
- src/commands/sourcemaps/upload.rs
- src/utils/sourcemaps.rs
> ref(sourcemaps): Fix `unnecessary_wraps` lint for `SourceMapsProcessor::add`

- src/commands/update.rs
- src/utils/update.rs
The current code suppresses any API errors that occur when trying to get the latest CLI version. This is probably ideal behavior in the update nagger, but likely not in the `sentry-cli update` command.
This change also fixes a `clippy::unnecessary_wraps` lint.
Ref #2357
> fix(update): Properly handle errors when getting latest CLI version

- src/utils/value_parsers.rs
We need `#[expect(clippy::unnecessary_wraps)]` on this function, add a comment to explain why.
> docs: Explain why lint is disabled

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
Several of our GitHub Actions runners are running on `ubuntu-latest`, `windows-latest`, and `macos-latest`, making the actions vulnerable to breakage when these images are updated. Therefore, we should pin to specific versions of these images.
Pinning to `ubuntu-24.04`, `windows-2022`, and `macos-14` because these are currently equivalent to `ubuntu-latest`, `windows-latest`, and `macos-latest`, respectively.
> ci: Pin Actions runners' OS versions

- .github/workflows/build.yml
This will cause `sentry-cli:<hash>` to be created and pushed to GHCR in the release build action, which runs on push to branches matching `release/*`. We can add a step to the actual release process which tags these GHCR images with the version number and also publish them to Docker Hub
Ref #1338
> build: Build Docker image in CI and publish to GHCR

- Dockerfile
Instead of using cross-compilation with `rust-musl-cross`, build Sentry CLI Docker container using the official Rust Alpine Docker image. This image will by default build for `musl` Linux (as before) using the architecture of the host system, rather than cross compiling
> build(docker): Build Docker image on host architecture

- .github/workflows/build.yml
When building the multiarch Docker image, build two separate Docker images for `amd64` and `arm64` natively by using a GitHub Actions runner with the respective architecture (note: `ubuntu-24.04-arm` is currently under public preview, so this could break in the future, but we likely get the best performance by building on the native architecture).
Then, we make the multiarch image by combining the two platform-specific images.
Depends on:
- #2386
Ref #1338
> ci(docker): Build each architecture natively

- .github/workflows/build.yml
There is no `--push` argument for `docker buildx imagetools create`. The command should automatically push the new image.
> ci(docker): Remove invalid argument

- .craft.yml
Add four new Craft targets to enable releases to Docker Hub and GHCR. These targets simply copy the multiarch Docker image built during the Release Build action to GHCR and Docker Hub. For both GHCR and Docker Hub, we create an image tagged with the version number and with "latest."
Ref #1338
> ci(docker): Add Craft targets for `docker`

- .craft.yml
It appears that Craft does not support pushing to GHCR, only to Docker Hub: https://github.com/getsentry/publish/actions/runs/13391431698/job/37399828094
> ci(docker): Don't publish to GHCR via Craft

- .github/workflows/build.yml
Because we are building two different Docker containers (one for each platform), we need separate caches for each one, otherwise both builds use the same cache, resulting in them overwriting each other. By setting a [separate scope for each,](https://docs.docker.com/build/cache/backends/gha/#scope)
the caches will be separate and not overwrite each other.
> ci(docker): Fix caching

- .github/workflows/release-ghcr-latest-tag.yml
- .github/workflows/release-ghcr-version-tag.yml
We already build and push our Docker images to GHCR, tagged with commit hash, during the Release Build action. This PR adds two new actions which will tag these images with the version number and with the "latest" once the GitHub release is created. We have two separate actions for each, since we only want to add the "latest" tag for releases, not for preleases, but the version tag should be created for both.
Ref #1503
> ci(docker): Release Docker image to GHCR

- yarn.lock
Bump the `cross-spawn@^6.0.5` subdependency to the latest `6.x` version, `6.0.6`.
> build(node): Bump `cross-spawn@^6.0.5`

- yarn.lock
Bump `cross-spawn@7.0.2` and `cross-spawn@7.0.3` to use version `7.0.6`
> build(node): Bump `cross-spawn@7.0.X`

- yarn.lock
Bump dependencies on major version 7 of `semver` to the latest version. This also removes the `lru-cache` subdependency.
> build(node): Bump `semver@^7.*` dependencies

- src/api/data_types/chunking/artifact.rs
- src/config.rs
- src/utils/file_upload.rs
I'm not sure if this covers all instances/paths
closes #2385
> fix: warn about missing SENTRY_RELEASE when it's set to empty string

- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
Attempts to fix https://github.com/getsentry/sentry-cli/issues/2413
> fix: Fix path mismatches on Windows

- .github/workflows/release-ghcr-latest-tag.yml
- .github/workflows/release-ghcr-version-tag.yml
Our current release process for GHCR makes the images tagged with the version number and "latest" only be single-arch images, rather than keeping them as multi-arch images.
This change _should_ fix this behavior.
> ci(docker): Fix GHCR releases so they are multiarch

- .github/workflows/build.yml
- entitlements.plist
- rcodesign.toml
> build(macos): Sign macOS binaries

- Cargo.lock
- Cargo.toml
- src/commands/upload_proguard.rs
- src/utils/dif_upload/mod.rs
The zip dependency was on a very old version. This updates
it to the same version that's already pulled in via symbolic.
Fortunately the required code changes are small.
Fixes #2422.
> deps: Update zip to 2.4.2

- .github/workflows/build.yml
- .github/workflows/ci.yml
`actions-rs` is no longer maintained. We can instead just call Rust commands directly.
This change also removes explicit installs of Rust toolchains, since GitHub Runners ship with the needed Rust tools installed. Instead, we only use `rustup target add` when needed for cross-compilation to other targets.
> ci: Stop using `actions-rs`

- .github/workflows/ci.yml
This explicit `-D warnings` is redundant, since we set the `RUSTFLAGS` environment variable to `-Dwarnings` above.
#2426 tests this change by intentionally introducing a Clippy warnings. As expected, the CI lint action fails.
> ci: Remove unneeded `-D warnings`

- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release-ghcr-latest-tag.yml
- .github/workflows/release-ghcr-version-tag.yml
- .github/workflows/release.yml
Many of the actions we are using were pinned to old versions. This PR updates all actions to the latest avaialable versions, and securely pins them using their full hashes, which is a [recommended security practice](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions), since version tags are mutable.
A future PR will add a Dependabot configuration which will periodically check for new actions releases, and open PRs to update the actions.
> ci: Update and securely pin all actions

- Cargo.lock
- Cargo.toml
- src/utils/fs.rs
We can use the `windows-sys` crate (published by Microsoft and actively maintained) instead.
Ref #1426
> build: Remove direct `winapi` dependency

- Cargo.lock
- Cargo.toml
- src/commands/bash_hook.rs
- src/commands/send_event.rs
`username` is completely unmaintained, and it depends on `winapi`, preventing us from supporting Windows on ARM. Use `whoami` instead to get the curent user.
Ref #1426
> build: Replace `username` with `whoami`

- .github/workflows/build.yml
- scripts/wheels
Create a release build for Windows ARM. We still will need to make changes to actually distribute this through all channels (e.g. through `npm` and possibly the install shell script).
Closes #1426
> ci: Build for Windows ARM

- src/utils/fs.rs
- src/utils/update.rs
Don't compile the function at all for Windows (this avoids `unnecessary_wraps` lint on Windows). Partially unblocks #2360.
> ref: Simplify `set_executable_mode`

- src/utils/system.rs
Unblocks #2360 by avoiding `unnecessary_wraps`
> ref: Simplify `is_homebrew_install`

- .github/workflows/ci.yml
- src/utils/system.rs
Sentry CLI contains platform-dependent code. Therefore, to ensure we catch all linter errors, we need to run `cargo clippy` against all targets.
> ci: Run lint action on all target operating systems

- src/commands/sourcemaps/explain.rs
- src/utils/appcenter.rs
- src/utils/sourcemaps.rs
One of them appears to be a false positive, though.
> chore: Fix current clippy lints

- src/commands/debug_files/upload.rs
- src/commands/issues/mute.rs
- src/commands/issues/resolve.rs
- src/commands/issues/unresolve.rs
- src/commands/react_native/appcenter.rs
- src/commands/react_native/gradle.rs
- src/commands/react_native/xcode.rs
- src/commands/upload_proguard.rs
These appear to have been originally added in #670; however, we have not adopted these info logs consistently across all of our commands, and we believe they are likely not very useful.
Since some of these commands are going to be modified to accept multiple projects, the info log would anyways need to be reworked if we were to keep it; however, it is simpler just to get rid of the log for now.
> feat: Remove organization and project info log

- src/api/mod.rs
- src/commands/files/upload.rs
- src/utils/file_upload.rs
Legacy (i.e. non-chunked) are distinct from chunked uploads, so it makes sense to have a separate struct to enforce these differences via the type system.
Specifically, legacy uploads must be associated with a release, whereas this is not required for many chunk uploads. Legacy uploads must also be associated with at most one project, whereas chunked uploads can have multiple projects (support for which we will add in the CLI with #2408)
> ref: Separate `LegacyUploadContext` for legacy uploads

- src/api/data_types/chunking/artifact.rs
- src/api/mod.rs
- src/utils/file_upload.rs
> ref: Use slice instead of vec for assemble artifact request

- src/api/mod.rs
- src/commands/debug_files/bundle_jvm.rs
- src/commands/files/upload.rs
- src/commands/react_native/appcenter.rs
- src/commands/react_native/gradle.rs
- src/commands/react_native/xcode.rs
- src/commands/sourcemaps/upload.rs
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
- tests/integration/_cases/react_native/xcode-upload-source-maps-release_and_dist_from_env.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-debugid-alias.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-file-hermes-bundle-reference-debug-id.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-file-ram-bundle.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-indexed-ram-bundle.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-modern.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-no-dedupe.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-skip-already-uploaded.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-some-debugids.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-successfully-upload-file.trycmd
It is now possible to upload sourcemaps to multiple projects at once, by passing the `-p`/`--project` flag multiple times to the `sentry-cli sourcemaps upload` command. Previously, it was possible to specify multiple projects via this flag, but all but the first project were ignored.
Multi-project sourcemaps uploads only work for Sentry servers which support chunked uploads – since this feature was added quite some time ago, we expect most self-hosted Sentry instances will support this. Older versions of Sentry continue to only support single-project uploads, but now, instead of silently ignoring all but the first project, an error is returned.
Closes #2408
> feat(sourcemaps): Multi-project sourcemaps upload

- src/utils/sourcemaps.rs
- src/utils/sourcemaps/inject.rs
> ref: Rename `fixup_js_file_end`

- src/commands/react_native/gradle.rs
- src/commands/sourcemaps/upload.rs
- src/utils/file_upload.rs
- src/utils/sourcemaps.rs
- tests/integration/_cases/sourcemaps/sourcemaps-upload-file-ram-bundle.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-upload-indexed-ram-bundle.trycmd
Remove the branch from `guess_sourcemap_reference` which handles the case of there only being one sourcemap. If there are multiple minified souces, they would all (erroneously) end up associated with the same single sourcemap.
Also, since code for uploading bundles was relying on this branch (specifically when unpacking bundles), refactor so that we use the sourcemap which is passed to the command directly, rather thna "guessing" it.
Fixes https://github.com/getsentry/sentry-cli/issues/2438
Fixes https://github.com/getsentry/sentry-cli/issues/2503
> fix(sourcemaps): Avoid associating only sourcemap with all minified sources

- src/utils/system.rs
Added support for multiple files in SENTRY_DOTENV_PATH variable. Multiple files are separated with a comma and override each other.
See #2451
> Support multiple files in SENTRY_DOTENV_PATH

- src/commands/files/delete.rs
- src/commands/files/list.rs
- src/commands/files/mod.rs
- src/commands/files/upload.rs
- src/commands/sourcemaps/explain.rs
- tests/integration/_cases/help/help-windows.trycmd
- tests/integration/_cases/help/help.trycmd
- tests/integration/_cases/releases/releases-files-upload-sourcemaps.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-explain-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-help.trycmd
- tests/integration/_cases/sourcemaps/sourcemaps-no-subcommand.trycmd
The commands are now hidden from help output (making them less likely to be discovered and used), and they are marked with a deprecation notice.
When invoking the commands, a deprecation notice will be printed as well.
Also the previously deprecated `sourcemaps explain` command (which was replaced by an in-app sourcemaps debugger)  which already prints a deprecation notice is also being marked as hidden to be less discoverable.
Ref #2513
> feat: Mark all `files` subcommands as deprecated.

- src/commands/debug_files/bundle_sources.rs
For dSYMs, `canonical_path` excludes the original dSYM extension, causing any extension before the `.dSYM` to be lost when adding the `.src.zip` extension. This caused the bug observed in #2502.
Instead, we should use the file name given in the original path when generating the file name for the output source bundle.
Fixes #2502
> fix: Use `orig_path` for bundle sources output file name

- src/api/mod.rs
- src/commands/releases/finalize.rs
- tests/integration/_cases/releases/releases-finalize-dates.trycmd
- tests/integration/releases/finalize.rs
The Sentry server [already ignores the value passed as `--started`](https://github.com/getsentry/sentry/blob/993bddbb73d9091fb949ad34578c7b28e0e3b8ab/src/sentry/api/endpoints/organization_release_details.py#L415-L534) to the `releases finalize` command. So, the option does not work as expected.
Here, we explicitly mark the parameter as deprecated by logging a warning message stating that the value is ignored. We also stop sending the started date to the server.
Fixes #2481
> fix: Explicitly deprecate `--started` flag

- src/api/errors/api_error.rs
- src/api/mod.rs
- src/config.rs
Currently, if an invalid value is supplied for the maximum retry count, the CLI will panic, if a command which reads this value is called.
Since we can always fall back to a reasonable default, we should probably warn instead of errroring at all when an invalid value is supplied.
This change is done in preparation for #2209, since that change will add retries to all endpoints, increasing the chance of a user encountering a panic if this behavior is left unfixed.
> fix: Don't error if invalid value supplied for max retries

- src/api/mod.rs
- src/config.rs
With the current implementation, we attempt to retrieve the max retry count from the environment or from the ini file on every access, which could lead to the user being warned multiple times if an invalid value is supplied. Instead, we should only obtain this count once and store it in the `Config`
Depends on:
- #2520
> ref: Only obtain max retry count once

- src/api/mod.rs
> feat: Retry all HTTP requests

- js/helper.js
- npm-binary-distributions/linux-arm/package.json
- npm-binary-distributions/linux-arm64/package.json
- npm-binary-distributions/linux-i686/package.json
- npm-binary-distributions/linux-x64/package.json
- scripts/install.js
Android systems should be able to run the Linux binary. This change enables the Linux binary to be fetched when the `npm` package is installed on an Android system.
Fixes #2288
> feat(npm): Add support for installing `npm` package on Android

- src/commands/react_native/appcenter.rs
- Hide the command from the help menu.
- Print a deprecation notice when the command is used.
Modelled on #2512
Fixes #2488
> feat: Mark `react-native appcenter` as deprecated

- Cargo.toml
- src/utils/system.rs
This will allow us to use lints which require newer MSRV (such as [`clippy::allow_attributes`](https://rust-lang.github.io/rust-clippy/master/index.html#allow_attributes)).
Also, fix a lint which surfaces after bumping MSRV.
> build: Bump MSRV to 1.86

- src/utils/logging.rs
Unsure what this is meant for, seems like we should just remove it.
Depends on:
- #2527
> ref: Delete dead `logging` code

- .github/CODEOWNERS
List @szokeasaurusrex as the default `CODEOWNER` for the Sentry CLI repo
> meta: Add `CODEOWNERS` file

- src/commands/mobile_app/mod.rs
- src/commands/mobile_app/upload.rs
- src/commands/mod.rs
- tests/integration/_cases/mobile_app/mobile_app-help.trycmd
- tests/integration/_cases/mobile_app/mobile_app-upload-help.trycmd
- tests/integration/mobile_app/mod.rs
- tests/integration/mobile_app/upload.rs
- tests/integration/mod.rs
In preparation for adding mobile application upload support to Sentry, this creates the basic scaffolding of a new `mobile-app` command with a single `upload` subcommand. The implementation of this subcommand will come in subsequent PRs.
Currently, the `mobile-app` command is set to hidden to ensure minimal exposure if a release is cut.
> Setup initial mobile-app command scaffold

- clippy.toml
- src/main.rs
Since we run our clippy lints with `--test` in CI, the `unwrap::used` lint, as currently written, was not triggering (e.g. on the PR #2532, which contains a violation which should have triggered the lint).
This change should make the `unwrap_used` lint active, also in CI, but not for test code, as was originally intended.
> build: Fix clippy `unwrap::used` lint in CI

- Cargo.toml
- build.rs
- src/main.rs
- tests/mod.rs
This change also requires some changes to the `tests/` and `build.rs`, since the lints are now active for those as well.
> build: Move lint config to `Cargo.toml`

- src/commands/mobile_app/upload.rs
- src/utils/mobile_app/validation.rs
For ease of parsing artifacts on the backend, we'll "normalize" all provided paths to a basic zip file. This ensures that no matter the artifact uploaded (files: APK, AAB, directory: XCArchive), we can process all as a zip file on the backend. This was an optimization done with Emerge that greatly simplified backend artifact handling.
Skipping tests here to be added at a later time when I leverage a full integration test to validate the chunked uploads match the expected zip format.
> Add Zip normalization of provided paths before uploading

- .github/workflows/build.yml
> ci: Use `windows-2022`

- src/commands/login.rs
> feat(login): Warn when overwriting existing auth token

- CONTRIBUTING.md
After adding some tests in a recent PR, figured it could be good to add some notes about debugging and the `dump` command usage to the docs.
> meta: Add some testing notes to docs

- src/commands/mobile_app/upload.rs
WIthout this, the code would remove the xcarchive wrapper directory, which causes issues when trying to parse the artifact in launchpad
> fix(launchpad): Ensure mobile artifact's zip structures are preserved

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .github/workflows/swift-test.yml
- .github/workflows/test.yml
- .github/workflows/test_node.yml
This PR contains several improvements to our CI process which aim to make the CI workflow cleaner and to make it easier to configure required tests in code.
Before the change:
After the change:
After the change, with some of the groups expanded:
As can be observed in the screenshots, this restructuring makes it clearer what all the CI check is doing, when viewing the workflow summary in CI.
The restructure also moves the Swift tests from a separate workflow file into the main `ci.yml` file.
This PR also adds a "Check required jobs" job, which passes only if all other jobs in `ci.yml` pass. We intend to make this check the only required status from `ci.yml` to make PRs mergeable. 
Making "Check required jobs" required will indirectly make the previously non-required checks required: Test …
> ci: Restructure CI process

- yarn.lock
Looks like yarn.lock was stale and missed am entry for a new(?) binary
> chore(js): Unstale yarn lock

- .github/workflows/test_node.yml
builds on top of and should be merged after #2611 
This PR removes usage of `npm` to install dependencies and run tests in the `node_tests.yml` CI workflow. Instead we now use `yarn` like in the rest of the repo.
The reason we seemed to prefer npm over yarn here was that yarn is stricter with the `engines` field and it throws if the older node versions (10 and 12 in our case) don't support a package that needs to be installed. 
Therefore, I added the `--ignore-engines` flags to the install commands for Node 10 and 12. Which, I think is fair. (fwiw, if there was any actual problem, the usage of npm wouldn't have fixed that, it just wouldn't have thrown an error). 
This change now ensures that we use `yarn` for Node tests and type checking, which also means we can use the exact dependencies …
> chore(ci): Use yarn for node tests instead of npm

- src/commands/mobile_app/upload.rs
This was copying files without preserving permissions, resulting in binary files that couldn't be executed
> fix: Fix file permissions in zip

- apple-catalog-parsing/build.rs
If `cargo` is invoked inside a sandbox on Darwin, the build will fail when it invokes `swift`. This is because `swift` builds within its own sandbox by default, but nested sandboxes are not allowed on Darwin.
This is the case, for example, when building `sentry-cli` inside Homebrew.
For builds that already happen inside a sandbox, allow setting an environment variable `SWIFT_DISABLE_SANDBOX` which then results in `swift` being invoked with `--disable-sandbox` to enable the build to succeed.
> feat: allow optionally disabling Swift sandbox

- src/commands/mobile_app/upload.rs
- src/commands/react_native/gradle.rs
- src/commands/send_metric/mod.rs
Previously, `cargo fmt` was unable to find these files, so CI could not enforce formatting. Fortunately, seems as though most contributors have been using rust-analyzer locally, so there are only a few formatter violations to fix here.
Prerequisite for #2622
> ref: Reformat `src/commands`

- .github/workflows/test_node.yml
So it turns out `yarn` handles `optionalDependencies` more strictly than `npm`: Revert "chore(ci): Use yarn for node tests instead of npm (#2612)"
TLDR: We need to revert installing dependencies with `yarn` because in contrast to npm, `yarn` exits the installation of `optionalDependencies` if the version does not exist. We're running into this edge case on our release branch, where we first bump the dependency versions to the next version to be released and then run tests which try to install this new version.
More details in Revert "chore(ci): Use yarn for node tests instead of npm (#2612)"
(this is not a bug but an implementation decision of yarn)
> Revert "chore(ci): Use yarn for node tests instead of npm (#2612)"

- src/commands/mobile_app/upload.rs
It is a bit weird to have this block defining two variables inside the definition of another variable.
I think the following is a bit more readable. It also keeps the code DRY.
Review alongside #2618, this is basically the changes I would have suggested on that PR
> ref: Clean up code

- Cargo.toml
- src/commands/debug_files/bundle_jvm.rs
- src/commands/files/upload.rs
- src/commands/send_event.rs
- src/commands/sourcemaps/explain.rs
- src/config.rs
- src/utils/sourcemaps.rs
- src/utils/vcs.rs
Using `clone` makes it clearer that we are cloning a `String` versus calling `to_string` on a `String.
> ref: Enable `string-to-string` lint

- js/index.d.ts
- js/releases/index.js
While working on #2605, I missed that we also need to add the new `live` option to the manually created *public* type declaration of the `SentryCLI().releases.uploadSourceMaps` method. This PR now adds the `live` option to this method. (feat because although there's no behaviour change, from a user perspective #2605 is only public with this change)
Very good reason to tackle #2617, since it will eliminate this kind of divergence. I gave it a quick try and got results pretty quickly. However, due to our internal typing currently being a lot more lenient than what the type declarations specify, I'd consider unifying the typing a breaking change. The goal is that our exported type declarations come from out internal type definitions BUT to get to this point, we first need to change these …
> feat(js): Export `live` option type for `releases.uploadSourceMaps`

- js/index.d.ts
- js/index.js
Of course I missed more occurances of the `live` mode in type declarations 🤦‍♂️ 
(no urgency this time though)
This PR now adds the new `rejectOnError` to the remaining `.execute` type declarations so that this mode can also be set by library consumers directly calling `.execute` (e.g. `@sentry/react-router` SDK).
> feat(js): Expose `rejectOnError` in public `execute` type declarations

- Cargo.toml
- clippy.toml
- src/api/mod.rs
- src/commands/debug_files/check.rs
- src/commands/debug_files/find.rs
- src/commands/files/upload.rs
- src/commands/monitors/run.rs
- src/commands/react_native/appcenter.rs
- src/commands/react_native/xcode.rs
- src/commands/send_event.rs
- src/commands/sourcemaps/upload.rs
- src/config.rs
- src/utils/appcenter.rs
- src/utils/chunks/upload.rs
- src/utils/dif_upload/mod.rs
- src/utils/file_upload.rs
- src/utils/mobile_app/apple.rs
- src/utils/progress.rs
- src/utils/system.rs
https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
> ci: Enable `uninlined-format-args` Clippy lint

- .github/workflows/lint.yml
- .github/workflows/test.yml
- .vscode/settings.json
- Cargo.toml
- src/api/data_types/chunking/mobile_app.rs
- src/api/data_types/chunking/mod.rs
- src/api/mod.rs
- src/commands/mobile_app/mod.rs
- src/commands/mod.rs
- src/utils/mobile_app/mod.rs
- tests/integration/mobile_app/mod.rs
This reverts commit 952feeb58f7ef928904bb590ca3fcea1b5317b42.
Fixes #2642
> feat(mobile-app): Reintroduce mobile-app feature gating

- .cursor/rules/cicd-patterns.mdc
- .cursor/rules/javascript-development.mdc
- .cursor/rules/rule-management.mdc
- .cursor/rules/rust-development.mdc
- .cursor/rules/sentry-cli-project.mdc
Add some basic Cursor rules to the repo.
> meta: Add Cursor rules

- .vscode/settings.json
Having this setting ensures that any linter warnings (at least, for the developer's system) are displayed in the IDE. I have had it enabled in my user settings for awhile, but we should also ensure it is set in the project settings, so that future Sentry CLI contributors have this setting enabled out of the box.
> meta(vscode): Make `rust-analyzer` run Clippy

- src/commands/mobile_app/upload.rs
- src/utils/mobile_app/mod.rs
- src/utils/mobile_app/validation.rs
- tests/integration/_cases/mobile_app/mobile_app-upload-help-not-macos.trycmd
Updates the mobile app command to make sure apple apps aren't uploaded from non-macos ARM, follow up from https://github.com/getsentry/sentry-cli/pull/2619
> fix: XCArchive upload on macOS ARM only

- src/commands/logs/mod.rs
- tests/integration/_cases/help/help-windows.trycmd
- tests/integration/_cases/help/help.trycmd
- tests/integration/_cases/logs/logs-help.trycmd
- tests/integration/_cases/logs/logs-list-help.trycmd
- tests/integration/_cases/logs/logs-list-no-logs-found.trycmd
- tests/integration/_cases/logs/logs-list-with-data.trycmd
Sentry's Logs feature is in beta. The commands therefore also should have been explicitly marked as beta.
> fix(logs): Mark `logs` command as beta

- .github/workflows/lint.yml
- .github/workflows/test.yml
- rust-toolchain.toml
This reverts commit 1dcc54dc77b95aa5d13a646de2c1f9f4e8d24da5.
Unfortunately, pinning the toolchain causes the release build to fail. Hopefully, we can reintroduce pinning soon, but for now, I would like to unblock release builds.
> revert: "build: Pin Rust toolchain minor version (#2687)"

- src/api/mod.rs
- src/commands/logs/list.rs
- tests/integration/_cases/logs/logs-list-help.trycmd
- tests/integration/_cases/logs/logs-list-no-logs-found-project-id.trycmd
- tests/integration/_cases/logs/logs-list-no-logs-found.trycmd
- tests/integration/_cases/logs/logs-list-with-data-project-id.trycmd
- tests/integration/logs.rs
- Allow project slugs & continue allowing project ids for project parameter in logs list
> feat(logs): allow project slugs in logs list

- src/api/data_types/chunking/mobile_app.rs
- src/api/mod.rs
- src/commands/mobile_app/upload.rs
- tests/integration/_cases/mobile_app/mobile_app-upload-apk-all-uploaded.trycmd
- tests/integration/_cases/mobile_app/mobile_app-upload-apk.trycmd
- tests/integration/_cases/mobile_app/mobile_app-upload-ipa.trycmd
- tests/integration/mobile_app/upload.rs
Adds output when uploading a mobile app to show the analysis URL:
```
$ sentry-cli mobile-app upload ~/apks/HackerNews.apk
> Preparing for upload completed in 0.229s
Successfully uploaded 1 file to Sentry
- /Users/chromy/apks/HackerNews.apk https://sentry.my.sentry.io/sentry/preprod/internal/57
```
Also updates the `sentry-cli` logic for recent changes to the upload endpoint:
- `gitSha` renamed to `headSha`
- Endpoint also returns `artifactId`
- We now are not expected to poll till assemble is complete, instead we call assemble twice:
- First time to find the missing chunks
- (here we upload all missing chunks)
- Second time to get the `artfiactId` and trigger an assembly job
This avoids having to wait for the (slow) assembly process to complete prior to the CLI exiting.
> feat(preprod): Show analysis URL after mobile-app upload

- src/api/data_types/chunking/mobile_app.rs
- src/api/mod.rs
- src/commands/mobile_app/upload.rs
- src/utils/vcs.rs
- tests/integration/_cases/mobile_app/mobile_app-upload-apk.trycmd
- tests/integration/_cases/mobile_app/mobile_app-upload-help-macos.trycmd
- tests/integration/_cases/mobile_app/mobile_app-upload-help-not-macos.trycmd
- tests/integration/_cases/mobile_app/mobile_app-upload-ipa.trycmd
- tests/integration/mobile_app/upload.rs
Adds new VCS params as args to the `mobile-app` command and passes them to the API (pending https://github.com/getsentry/sentry/pull/97332). Notably removes `sha` in favor of `head_sha`. Given this command is still unreleased and marked experimental, this would usually be a breaking change but I don't believe we need any backwards compatibility here.
We'll implement default value providing for most of these as well in follow ups, as I'd prefer to silo those implementations for easier review && testing.
> feat(mobile-app): Add new VCS params to mobile-app command

- .cursor/rules/cicd-patterns.mdc
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .vscode/settings.json
- Cargo.toml
- src/api/data_types/chunking/mobile_app.rs
- src/api/data_types/chunking/mod.rs
- src/api/mod.rs
- src/commands/mobile_app/mod.rs
- src/commands/mod.rs
- src/utils/mobile_app/mod.rs
- src/utils/vcs.rs
- tests/integration/mobile_app/mod.rs
This reverts commit eccd48c3836350166e19a458fcd2b286d58d5af9.
> Revert "feat(mobile-app): Reintroduce mobile-app feature gating (#2643)"

- src/api/mod.rs
- src/commands/build/upload.rs
- src/utils/vcs.rs
Adds default handling of `head_ref` (branch name) to the `mobile-app upload` subcommand. This will leverage the `head.shorthand()` value if no value is provided by the user.
Also handles the detached HEAD state with some logging that will require the user to specify using the command arguments.
> feat(mobile-app): Add default vcs base_ref parsing for mobile-app subcommand

- src/api/data_types/chunking/build.rs
- src/api/mod.rs
- src/commands/build/upload.rs
- tests/integration/_cases/build/build-upload-help-macos.trycmd
- tests/integration/_cases/build/build-upload-help-not-macos.trycmd
Adds an option for release notes, used by build distribution
> feat(mobile-app): Add release notes option

- .cursor/rules/rust-development.mdc
And also, make some other minor corrections to the development guidelines.
> meta(cursor): Tell Cursor to `cargo fmt`

- CLAUDE.md
Add a `CLAUDE.md` file, which instructs the Claude Code agent to read and follow the Cursor rules.
> meta(claude): Add `CLAUDE.md`

- apple-catalog-parsing/build.rs
When the Xcode app is not installed, compiling `apple-catalog-parsing` fails due to linker errors. The problem can be fixed by expanding the linker search path.
Fixes #2732
> build(macos): Allow compiling without Xcode

- package-lock.json
This did not get done automatically on release. I will put a PR on top of this to fix the automatic script, so we do not need to do this manually again.
> build(npm): Pin latest optional deps in `package-lock.json`

- package-lock.json
- scripts/post-release.sh
As we are doing `--package-lock-only` (which does not actually install packages), we don't have the dependencies needed to run the `install.js` script, which is auto-run when installing. By passing `--ignore-scripts`, we skip running `install.js`, and only end up bumping the `package-lock.json`, which is what we want to do.
> ci: `--ignore-scripts` on post-release `npm install`

- apple-catalog-parsing/native/swift/AssetCatalogParser/Sources/AssetCatalogParser/AssetCatalogReader.swift
While we still have this in two codebases we need to copy over the emerge change from: https://github.com/EmergeTools/emerge/pull/11525
> fix: Safer asset catalog reader for liquid glass

- Cargo.toml
Lately, I have been using the `dbg!` macro frequently for local development. Enabling the [`dbg-macro` lint](https://rust-lang.github.io/rust-clippy/master/index.html#dbg_macro) will ensure I don't accidentally commit any of these `dbg!` statements.
> build: Lint against `dbg_macro`

- Cargo.lock
`adler` is not maintained, use `adler2` instead
Fixes BE-577
> build(rust): Remove `adler` dependency

- Cargo.lock
- Cargo.toml
- src/api/mod.rs
Fixes [BE-574](https://linear.app/getsentry/issue/BE-574/remove-brotli2-dependency)
> build: Replace `brotli2` with `brotli`

- Cargo.lock
- Cargo.toml
- src/api/errors/mod.rs
- src/api/mod.rs
- src/constants.rs
- src/utils/retry.rs
Resolves [BE-578](https://linear.app/getsentry/issue/BE-578/remove-backoff-dependency)
> ref: Replace unmaintained `backoff` with `backon`
