getsentry/sentry-cli

Cargo.lock
Cargo.toml
src/api.rs
src/commands/releases.rs
src/lib.rs
src/sourcemaputils.rs

Added support for automatically processing sourcemaps to make working with react native work.

Add Sourcemap Processing

---

.npmignore
bin/install-sentry-cli
package.json

This PR adds the needed files to allow users to install via npm, as discussed in #31

Add package & install script for npm

---

Cargo.lock
Cargo.toml
src/api.rs
src/commands/projects.rs
src/commands/releases.rs
src/commands/repos.rs
src/errors.rs
src/lib.rs
src/vcs.rs

Added releases set-commits command

---

src/commands/upload_dsym.rs
src/macho.rs

Skip over files that do not contain dwarf data

---

bin/install-sentry-cli

Fixes missing parentheses in install-sentry-cli

---

Cargo.lock
Cargo.toml
src/utils/vcs.rs

fix: Add bitbucket to reference url check

---

src/config.rs

feat: Add better error reporting for config related io errors

---

docs/configuration.rst
src/main.rs

feat: Disable .env loading optionally

---

src/api.rs
src/commands/repos.rs
src/utils/vcs.rs

feat: Ignore missing urls on repo api endpoint responses

---

.ci/build.sh
appveyor.yml

build: Always build with locked Cargo.lock

---

src/commands/send_event.rs

https://github.com/getsentry/sentry-cli/issues/168

Use fail when event can't send

---

js/index.js

uploadSourceMaps lost scope when in the map function

execute was undefined

---

.ci/build-docker.sh

https://www.openssl.org/news/secadv/20171207.txt

build: Update OpenSSL to 1.0.2n

---

src/config.rs

This gets sentry-cli in line with other SDKs.

feat: No longer require the DSN secret

---

src/commands/difutil_check.rs
src/commands/difutil_find.rs
src/commands/difutil_uuid.rs
src/commands/mod.rs
src/commands/upload_breakpad.rs
src/utils/dif.rs
src/utils/iter.rs
src/utils/mod.rs

feat: Implement breakpad support

---

js/__tests__/index.test.js
js/index.js
src/commands/releases.rs

**_Note: We need to add `{ rewrite: true }` to our webpack plugin by default._**

ref: Refactor command normalization

---

src/commands/bash_hook.rs
src/commands/send_event.rs
src/config.rs
src/constants.rs
src/event.rs
src/utils/system.rs

This adds the enhancement https://github.com/getsentry/sentry-cli/issues/188.
I'm testing locally and it works. I tried follow the style in config.rs.
_Edit: combined commits and removed extra info to make easier for reviewers._

Check for model and family

---

.travis.yml
bin/install-sentry-cli

Allow to override the CDN URL via environment variable or NPM configuration.
Closes #197

build(npm): Set npm install CDN URL via environment variable

---

CHANGELOG.md
js/__tests__/index.test.js
js/index.js

fix: Expose getPath

---

docs/releases.rst

Fixes getsentry/sentry-webpack-plugin#15

docs(releases): Clarify on upload-sourcemaps --ext

---

src/api.rs
src/utils/dif_upload.rs

Changes for https://github.com/getsentry/sentry/pull/7226

ref(upload): Support fixed chunk assemble response

---

src/utils/dif_upload.rs

I outdented the progress bars again. Looks nicer I think and we did this before.

feat: Some progress bar beautification

---

docs/dif.rst
docs/index.rst
docs/pdb.rst

doc: Add a description for PDB files

---

src/utils/vcs.rs

Previously newly introduced vcs systems on the server fully broke the
client side repo detection.  Now we continue probing until we find one
and if we make it all the way down to not finding one we produce a
more accurate error message.
Fixes #300

feat: Add visualstudio support and fix unsupported configured repos breaking detection

---

src/api.rs

```
$ sentry-cli releases -o sentry-test -p rust2 list
error: project not found
caused by: project was renamed to 'rust'
```

fix(api): Generate proper errors for project renames

---

src/utils/codepush.rs

Reverts getsentry/sentry-cli#325
Merged this PR too fast before realizing that codepush package labels can only be retrieved via a different endpoint (`appcenter codepush deployment history`). This will require more changes in sentry-cli.
We will open a follow-up PR to fix this.

Revert "Switch from codepush to App Center CLI"

---

docs/pdb.rst

Ref https://github.com/getsentry/sentry-cli/issues/332

docs(pdb): Add troubleshooting guide for encoding issues

---

docs/configuration.rst

Closes https://github.com/getsentry/sentry-cli/issues/323

doc(configuration): Add required scopes

---

src/commands/mod.rs

Fixes two small issues in the help message output.

Fix: Incorrect grammar in help message

---

.craft.yml
.travis.yml
appveyor.yml
scripts/bump-version.sh

https://github.com/getsentry/craft

feat: Use "craft" for releasing

---

.appveyor.yml
.gitignore
.travis.yml
CHANGELOG.md
Dockerfile
scripts/build-in-docker.sh

Also: 
* Change entrypoint for resulting Dockerfile
* Add smoke tests for built binaries

feat: Use secured base Docker image for Linux builds

---

docker-entrypoint.sh

Just so we are on the safe side.

fix(docker): Allow to run "sh" as an entrypoint

---

js/__tests__/helper.test.js
js/releases/__tests__/index.test.js
js/releases/index.js
js/releases/options/uploadSourcemaps.js
src/commands/releases.rs

To support query params, eg. https://github.com/getsentry/sentry-webpack-plugin/issues/65

feat: Add url-suffix option

---

Cargo.lock
Cargo.toml
src/commands/bash_hook.rs
src/commands/difutil_find.rs
src/commands/mod.rs
src/utils/dif_upload.rs
src/utils/fs.rs

Waiting of release of symbolic 5.2.0

build: Upgrade symbolic

---

src/api.rs

feat: List all release files

---

src/api.rs
src/utils/vcs.rs

feat: Added debug logs for version control support

---

js/releases/index.js
scripts/install.js

This should clear up some confusion when the downloaded binary does not match the expected version.
Ref #407

ref(npm): Improve binary version verification error message

---

src/utils/vcs.rs

We'll want folks who use gitlab to also be able to set release commits with sentry-cli.
Refs APP-628

Add gitlab to supported VCS providers

---

src/utils/dif_upload.rs

This PR fixes a bug that occurs when specifying files directly to `upload-dif`. The file system walker removed the input path from the found filename, which removed the entire path for files.
**Invalid**:
```
$ sentry-cli upload-dif /path/to/filename
OK 27d16d76-924d-3a1d-b471-604e3b70fb0c (Generic; x86_64 executable)
```
**Fixed**:
```
$ sentry-cli upload-dif /path/to/filename
OK 27d16d76-924d-3a1d-b471-604e3b70fb0c (filename; x86_64 executable)
```

fix(upload): Correctly determine file names in FS scan

---

src/commands/mod.rs
src/utils/system.rs

feat: Add log-level helper output in case of error

---

.gitignore
js/helper.js
scripts/install.js
src/api.rs
src/commands/mod.rs
src/commands/update.rs
src/constants.rs
src/utils/system.rs
src/utils/update.rs

Also: fix check that the installation was done via NPM.

ref: Use release registry for update checks

---

.travis.yml
src/commands/difutil_check.rs
src/commands/difutil_find.rs
src/commands/difutil_id.rs
src/utils/dif.rs

```
Debug Info File Check
Type: dsym executable
Contained debug identifiers:
> 1ddb3423-950a-3646-b17b-d4360e6acfc9 (x86_64)
Contained debug information:
> symtab
> unwind
Usable: yes
```

feat(difutil): Support ELF files and output features

---

Cargo.lock
Cargo.toml
src/api.rs
src/commands/difutil_check.rs
src/commands/difutil_find.rs
src/commands/upload_dif.rs
src/commands/upload_proguard.rs
src/utils/args.rs
src/utils/dif.rs
src/utils/dif_upload.rs

This upgrades `symbolic` to the latest major version, in preparation for PDB support.
Until symbolic is released, this PR will remain WIP.

ref: Upgrade symbolic

---

azure-pipelines.yml
azure-pipelines/install-rust.yml
azure-pipelines/prescript-common.yml
scripts/build-in-docker.sh

I realized I didn't merge it.
We can let it run side-by-side with Travis for now.
https://dev.azure.com/sentry-builds/sentry-cli/_build?definitionId=1

ci: Build on Azure Pipelines

---

src/utils/vcs.rs

feat(releases): Allow port in url

---

src/commands/releases.rs
src/utils/sourcemaps.rs

Fixes #311
I wanted to add tests for this but this requires a greater refactoring as this is currently not well
abstracted :(

fix: Add support for --url-prefix=app:///

---

js/releases/index.js

This is a revisiting of #507 with some feedback incorporated. Exposes the ability to add commits to a release.

Allow setting commits on a release

---

package.json
scripts/install.js
yarn.lock

Fixes https://github.com/getsentry/sentry-cli/issues/572

fix: Fix progress bar calculations

---

Cargo.lock
Cargo.toml
src/commands/difutil_bundle_sources.rs
src/utils/dif_upload.rs

This skips pch and large files in the source bundle writer.

feat: Skip pch and large files in source bundles

---

src/commands/react_native_xcode.rs

Closes #609
Closes https://github.com/getsentry/sentry-react-native/issues/676

feat: Allow overriding dist in Xcode

---

js/releases/options/uploadSourcemaps.js

I need this to publish artifacts with a dist so that sourcemap are associated correctly

support dist option

---

package.json
yarn.lock

Closes https://github.com/getsentry/sentry-cli/issues/640

deps: Update https-proxy-agent to 4.0.0

---

src/api.rs

Fixes https://github.com/getsentry/sentry-cli/issues/541

fix: Add Content-Length=0 header to reprocessing POST request

---

.travis.yml
build.rs
package.json
scripts/install.js
src/config.rs
src/utils/vcs.rs

Fixes https://github.com/getsentry/sentry-cli/issues/610

feat: Allow for --silent flag in installation script

---

src/commands/react_native_appcenter.rs

Allows the user to specify a `dist` value on their release artifacts when using `sentry-cli react-native appcenter` (see docs [here](https://docs.sentry.io/platforms/react-native/codepush/)), so that they'll match with events (which are given a `dist` value by default) - a prerequisite for deminification with source maps.
Fixes https://github.com/getsentry/sentry-react-native/issues/703.

feat(appcenter): Add `dist` option to `react-native appcenter`

---

Cargo.lock
Cargo.toml

deps: Bump runas to 2.0.1

---

src/utils/vcs.rs

Add bitbucket_server to reference url check

---

src/utils/releases.rs

Closes https://github.com/getsentry/sentry-cli/issues/461

feat: Detect CodeBuild slug for propose-version

---

src/commands/login.rs
src/config.rs

Closes: https://github.com/getsentry/sentry-cli/issues/120

feat: Introduce g/global flag for login command

---

src/commands/mod.rs

Fixes https://github.com/getsentry/sentry-cli/issues/731

fix: Dont panic on unknown log level

---

src/commands/mod.rs

fixes: https://github.com/getsentry/sentry-cli/issues/739

fix: log-level should be case insensitive

---

CHANGELOG.md
src/bashsupport.sh
src/commands/bash_hook.rs

feat: Provide --no-environ flag for bash-hook

---

scripts/install.js

The use-case here is that CI cannot render progress bars "in place" and it clutters logs a lot. Some people still want to see their npm/yarn output though, which currently is tightly coupled to the install progress bar.
I didn't want to introduce another env var, so I reused the one that we already have in the system.
Closes https://github.com/getsentry/sentry-cli/issues/726

install: Allow for disabling install progress-bar without silencing npm

---

CHANGELOG.md
Dockerfile

fix(docker): Update base alpine image

---

src/api.rs
src/commands/projects.rs

fixes https://github.com/getsentry/sentry-cli/issues/768

fix: Handle teamless projects correctly

---

src/commands/monitors.rs

Closes https://github.com/getsentry/sentry-cli/issues/735

feat: Provide flag for allowing failures in monitor command

---

src/commands/mod.rs

Remove unnecessary log and move nagger after we printed the original error message.

ref: Make Update Nagger less aggressive

---

src/utils/dif_upload.rs

fix: Path handling edgecases for upload-dif

---

src/utils/appcenter.rs
src/utils/codepush.rs
src/utils/cordova.rs
src/utils/releases.rs
src/utils/xcode.rs

Closes https://github.com/getsentry/sentry-cli/issues/802

ref: Update Android/iOS releases format

---

src/commands/uninstall.rs

This adds a `--skip-confirmation` argument to the `uninstall` command.
I use this tool on CI/Docker and uninstall after use so it doesn't add to an image. Uninstalling with the confirmation prompt is an issue, so having an argument like this ideal to skip the confirmation prompt all together and simply uninstall.
---
This is my first Rust code ever written, so please be gentle if I made a mistake. 😆

feat: add skip confirmation arg to uninstall cmd

---

src/utils/appcenter.rs

Fixes https://github.com/getsentry/sentry-cli/issues/815
Fixes https://github.com/getsentry/sentry-cli/issues/816
ref: https://app.asana.com/0/1142928854421177/1192318118715794

fix: Use updated release name format during upload process

---

src/commands/send_event.rs

Closes https://github.com/getsentry/sentry-cli/issues/819

feat: Allow for passing custom timestamp with send-event

---

scripts/install.js

Closes https://github.com/getsentry/sentry-cli/issues/832

ref: Use better error messages for install script

---

src/api.rs
src/commands/releases.rs

```
sentry-cli releases archive <version>
sentry-cli releases restore <version>
```

feat: Add archive and restore sub-commands to releases command

---

src/api.rs
src/commands/releases.rs
tests/commands/releases_finalize.rs

Fixes #868
Ref https://github.com/getsentry/sentry-cli/pull/869

fix: Restore release modification calls to use put request

---

src/utils/dif_upload.rs

Fixes https://github.com/getsentry/sentry-cli/issues/944
Tested locally:

ref: Allow upload-dif to follow symlinks to make it inline with difutil behavior

---

bin/sentry-cli
src/commands/react_native_appcenter.rs
src/commands/react_native_codepush.rs
src/config.rs
src/utils/appcenter.rs
src/utils/codepush.rs
src/utils/xcode.rs
tests/commands/releases_list.rs

This should resolve some issues from (closes https://github.com/getsentry/sentry-cli/issues/922)

ref: Rely on spawn process error for detecting command presence

---

Cargo.lock
Cargo.toml
src/utils/system.rs
src/utils/update.rs

No rust was harmed during this update.

build: Update outdated dependencies that require little to no work

---

src/commands/react_native_xcode.rs

Fix an issue: https://github.com/getsentry/sentry-react-native/issues/1229
Android cli PR: https://github.com/getsentry/sentry-react-native/pull/1548

[Fix] Allow to define a custom release name for source-maps upload

---

Cargo.lock
Cargo.toml
src/api.rs
src/commands/difutil_find.rs
src/commands/upload_dif.rs
src/utils/chunks.rs
src/utils/dif_upload.rs
src/utils/file_search.rs
src/utils/file_upload.rs
src/utils/progress.rs
src/utils/sourcemaps.rs

feat: Print sourcemaps/files operations timings information

---

src/utils/file_upload.rs

@jjbayer as you found this issue and have more context around it.
@mitsuhiko as you wrote this part of the code.

fix: Correctly resolve paths with hashes in url_to_bundle_path

---

scripts/install.js

Not that we cannot do this change globally in one place, as this would be a breaking change due to the fact that install logs went to `stderr` and progress bar to `stdout` in the current implementation.
Closes https://github.com/getsentry/sentry-cli/issues/1006

feat: Allow for changing log stream through SENTRYCLI_LOG_STREAM variable

---

src/utils/file_upload.rs

Closes https://github.com/getsentry/sentry-cli/issues/1012

feat: Print upload context details

---

src/commands/releases.rs

Fixes https://github.com/getsentry/sentry-cli/issues/1064#issuecomment-961024877

ref: Show project flag for releases command

---

src/commands/upload_dif.rs

This explains more what happens if you use the App Store Connect
integration.

docs: Clarify how --symbol-maps is used

---

scripts/install.js

feat: add SENTRYCLI_SKIP_DOWNLOAD flag for preventing download

---

.github/workflows/stale.yml
src/commands/bash_hook.rs

Add a stale bot to this repository

meta(gha): Deploy action stale.yml

---

src/utils/dif_upload.rs

This change moves removal of `debug_id` from `DifMatch` initialization to the assembling process.
This way it runs for both types of upload, no matter how `DifMatch` was produced, as well as for pooling calls _and_ upload calls.
Fixes https://github.com/getsentry/sentry-cli/issues/1056
Fixes https://github.com/getsentry/sentry-cli/issues/980

fix: Dont include debug_id during assemble when not PDBs are not supported

---

src/utils/xcode.rs

Resolves https://github.com/getsentry/sentry-cli/issues/1093

feat: Use default xcode values for plist struct

---

src/commands/difutil_find.rs

Not great, not terrible, but definitely easier to skim around.

ref: Rework find_id function of difutil find

---

package.json

I completely forgot about windows users. mi scusi!

revert: ref: Dont run install script using node binary #1151

---

CHANGELOG.md

Fixes https://github.com/getsentry/sentry-cli/issues/686
Resolves https://github.com/getsentry/sentry-cli/issues/765
Resolves https://github.com/getsentry/sentry-cli/issues/1130
Resolves https://github.com/getsentry/sentry-cli/issues/1142
Closes https://github.com/getsentry/sentry-cli/issues/1097
Closes https://github.com/getsentry/sentry-cli/issues/1143

misc: 2.0.0-beta.0 changelog

---

Cargo.lock
Cargo.toml
package.json
src/commands/sourcemaps/mod.rs
src/commands/sourcemaps/resolve.rs
tests/integration/_cases/sourcemaps/sourcemaps-help.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-no-subcommand.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-resolve-help.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-resolve.trycmd
tests/integration/_fixtures/bundle.min.js.map
tests/integration/mod.rs
tests/integration/sourcemaps/mod.rs
tests/integration/sourcemaps/resolve.rs
yarn.lock

Based on https://github.com/getsentry/sentry-cli/pull/1181 so it needs to get merged first.
Includes implementation and integration tests. Only the last commit of this PR is relevant.

feat: Add sourcemaps resolve command

---

src/commands/mod.rs
tests/integration/_cases/debug_files/debug_files-help.trycmd
tests/integration/_cases/debug_files/debug_files-no-subcommand.trycmd
tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
tests/integration/_cases/deploys/deploys-help.trycmd
tests/integration/_cases/deploys/deploys-no-subcommand.trycmd
tests/integration/_cases/info/info-help.trycmd
tests/integration/_cases/login/login-help.trycmd
tests/integration/_cases/releases/releases-help.trycmd
tests/integration/_cases/releases/releases-no-subcommand.trycmd
tests/integration/_cases/send_event/send_event-help.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-help.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-no-subcommand.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-resolve-help.trycmd
tests/integration/_cases/uninstall/uninstall-help.trycmd
tests/integration/_cases/update/update-help.trycmd
tests/integration/_cases/upload_dif/upload_dif-help.trycmd
tests/integration/_cases/upload_proguard/upload_proguard-help.trycmd

ref: Make --header a global flag so its position independent

---

src/bashsupport.sh
src/commands/bash_hook.rs
src/commands/mod.rs
tests/integration/_cases/bash_hook/bash_hook-help.trycmd
tests/integration/_cases/bash_hook/bash_hook.trycmd
tests/integration/bash_hook.rs
tests/integration/mod.rs

No functional changes in regards to v1.

ref: Restore bash-hook as hidden command w. integration tests

---

tests/integration/_cases/projects/projects-help.trycmd
tests/integration/_cases/projects/projects-list-help.trycmd
tests/integration/_cases/projects/projects-list.trycmd
tests/integration/_cases/projects/projects-no-subcommand.trycmd
tests/integration/_responses/projects/get-projects.json
tests/integration/mod.rs
tests/integration/projects/list.rs
tests/integration/projects/mod.rs

The title is self-explanatory.

test: Add integration tests for projects command

---

src/utils/dif_upload.rs

We could restrict it to just `ZipError::UnsupportedArchive`, but I thought it'd be too much, and we'd rather skip it than break builds anyway.
Before:
```
DEBUG   2022-05-27 14:59:26.963251 +02:00 searching location ../../playgrounds/sentry-cli/symbols-zip
DEBUG   2022-05-27 14:59:26.965591 +02:00 searching zip archive ../../playgrounds/sentry-cli/symbols-zip/archive.zip
error: unsupported Zip archive: Password required to decrypt file
```
After:
```
DEBUG   2022-05-27 14:59:26.963251 +02:00 searching location ../../playgrounds/sentry-cli/symbols-zip
DEBUG   2022-05-27 14:59:26.965591 +02:00 searching zip archive ../../playgrounds/sentry-cli/symbols-zip/archive.zip
DEBUG   2022-05-27 14:59:26.966591 +02:00 skipping zip archive ../../playgrounds/sentry-cli/symbols-zip/archive.zip
DEBUG …
```

ref: Skip protected zip files when uploading debug files

---

Cargo.lock
Cargo.toml
src/api.rs
src/commands/debug_files/upload.rs
src/utils/dif_upload.rs
tests/integration/_cases/debug_files/debug_files-upload-help.trycmd
tests/integration/_cases/upload_dif/upload_dif-help.trycmd

This depends on https://github.com/getsentry/symbolic/pull/516.

feat: Compute and upload il2cpp line mappings

---

Cargo.lock
Cargo.toml
src/utils/fs.rs

Cherry-picked from `1.x` branch. (originally from https://github.com/getsentry/sentry-cli/pull/1256)

fix: Increase TempFile robustness on Windows (#1256)

---

src/commands/login.rs

This should always work, but apparently we missed it for a looong time :3

fix: Allow for using --auth-token with login command

---

src/utils/xcode.rs

The recent fix (https://github.com/getsentry/sentry-cli/pull/1310) works perfectly fine when called directly from the CLI, however, there's an additional branch that is used when the CLI is used as the part of the build script configured and run within the XCode tool itself.
This PR covers this branch and unifies the rest of the builders to utilize the same helper for all cases.
Tested on 2 user-provided repro cases, both from the terminal and using XCode directly.
Fixes https://github.com/getsentry/sentry-cli/issues/1301

fix: Use direct plist env vars fallback when called within xcode itself

---

src/utils/dif_upload.rs

Fixing typo

---

README.md
src/commands/events/list.rs
src/commands/issues/mod.rs
src/commands/mod.rs
src/commands/organizations/list.rs
src/commands/react_native/xcode.rs
src/commands/releases/info.rs
src/commands/repos/list.rs
src/commands/sourcemaps/upload.rs
src/commands/uninstall.rs
src/utils/dif_upload.rs
src/utils/system.rs
src/utils/update.rs
src/utils/vcs.rs
src/utils/xcode.rs

Fixes https://github.com/getsentry/sentry-cli/issues/1373

docs: Update readme to include docker flags for resolving git issue

---

CHANGELOG.md

Had to do it manually to make it more readable this time.

meta: Update changelog for 2.9.0

---

CHANGELOG.md

Had to go manual way this time, as one of the PRs was not squashed, but merged instead, and would produce 3 entries.

meta: 2.10.0 changelog

---

.github/workflows/ci.yml

misc: Update incorrect comment in ci workflow

---

.github/workflows/ci.yml

This should fix the older node CI setups.

fix: Make older CI use an older NFT

---

Cargo.lock
src/utils/args.rs
src/utils/vcs.rs
yarn.lock

Closes https://github.com/getsentry/sentry-cli/pull/1424
Closes https://github.com/getsentry/sentry-cli/pull/1427
Closes https://github.com/getsentry/sentry-cli/pull/1428
Closes https://github.com/getsentry/sentry-cli/pull/1434
Closes https://github.com/getsentry/sentry-cli/pull/1435

deps: Update npm/cargo dependencies for dependabot

---

src/api.rs

ref: Use list_release_files_by_checksum directly in list_release_files

---

CHANGELOG.md

Update changelog for backport to fix the security vulnerability.

meta(changelog): Update CHANGELOG for 1.75.0

---

src/commands/sourcemaps/inject.rs

This keeps the `sourceMappingURL` comment at the end of a source file when injecting debug ids. It does this by reading the file to memory and writing it back line by line, but saving the comment line to the very end. It works fine in my limited tests, but it doesn't *feel* elegant to me. Suggestions for how to improve this would be very welcome.

ref(inject): Keep sourceMappingURL comment at end

---

src/bashsupport.sh
src/commands/bash_hook.rs
tests/integration/_cases/bash_hook/bash_hook-help.trycmd
tests/integration/_cases/bash_hook/bash_hook-tags.trycmd
tests/integration/bash_hook.rs

building on https://github.com/getsentry/sentry-cli/pull/1398/files to address https://github.com/getsentry/sentry-cli/issues/1514

feat: Adds tags to bash hook

---

CHANGELOG.md

chore: Add changelog note for 1.75.2

---

src/utils/dif_upload.rs

Closes https://github.com/getsentry/sentry-cli/issues/1583

ref(debug-files): Polish after-upload message output

---

js/__tests__/helper.test.js
js/index.d.ts
js/releases/index.js
js/releases/options/uploadSourcemaps.js

Ref https://github.com/getsentry/sentry-cli/issues/1605#issuecomment-1554427232

ref(types): Add dedupe to available TS types

---

Cargo.lock
Cargo.toml
src/api.rs
src/commands/monitors/run.rs
tests/integration/_cases/monitors/monitors-run-help.trycmd
tests/integration/_cases/monitors/monitors-run-token-auth-win.trycmd
tests/integration/_cases/monitors/monitors-run-token-auth.trycmd
tests/integration/monitors/run.rs

feat(crons): Replace API checkins w/ send_envelope

---

src/utils/dif_upload.rs

Closes https://github.com/getsentry/sentry-cli/issues/1622#event-9502706499
Profiled using https://crates.io/crates/cargo-instruments.
Before:
After:

ref(debug-files): Use temp file handle instead of keeping zips in memory

---

CHANGELOG.md
src/utils/file_upload.rs
tests/integration/debug_files/bundle_jvm.rs
tests/integration/mod.rs
tests/integration/sourcemaps/upload.rs

This reverts commit 7470bac7f77ce8fc4884b4e331b3aca2a5b463e1.
Need to do this while we fix things.

Revert "feat: Don't upload chunks that are already on the server (#1651)

---

src/api.rs

Fixes https://github.com/getsentry/sentry-cli/issues/1657

ref: Do not dedupe artifacts if server wont handle it due to url limit

---

src/config.rs

In particular, this points users towards making sure `system.url-prefix` is set if an org auth token doesn't contain a URL.
See https://github.com/getsentry/sentry-cli/issues/1750#issuecomment-1733849288.

fix: Print better error messages for org auth tokens

---

package.json
src/api.rs
src/commands/bash_hook.rs
src/commands/releases.rs
tests/integration/mod.rs

This seems to fail for node 8?

test: Skip code coverage generation

---

Cargo.lock
Cargo.toml
src/commands/login.rs
src/commands/mod.rs
src/config.rs
src/utils/system.rs
tests/integration/_cases/org_tokens/org-match.trycmd
tests/integration/_cases/org_tokens/org-mismatch.trycmd
tests/integration/_cases/org_tokens/url-match.trycmd
tests/integration/_cases/org_tokens/url-mismatch.trycmd
tests/integration/_cases/org_tokens/url-works.trycmd
tests/integration/mod.rs
tests/integration/org_tokens.rs

This is a backport of the org auth tokens functionality from v2.

feat: Support org auth tokens

---

src/commands/sourcemaps/upload.rs
src/utils/sourcemaps.rs
tests/integration/_cases/sourcemaps/sourcemaps-upload-help.trycmd

Sourcemap upload strict mode

---

Cargo.lock
Cargo.toml
src/commands/monitors/run.rs

Validate `monitors run` command's `--timezone` argument

---

Cargo.lock
Cargo.toml

Update `tempfile` dependency to latest version

build: Bump tempfile dependency

---

.github/workflows/ci.yml
src/utils/auth_token/test.rs

This PR implements @Swatinem's suggestions from #1934. #1934 was auto-merged before I could implement the suggestions there.

ci: Updates to lint GH action

---

.github/workflows/build.yml

Hoping to fix publish failures

ci: Bump node version to pack main package

---

js/helper.js

Ensures #1858 works even after a refactor

fix: support windows on arm via x64 binary

---

src/commands/sourcemaps/upload.rs
tests/integration/_cases/sourcemaps/sourcemaps-upload-cjs-mjs.trycmd
tests/integration/_cases/sourcemaps/sourcemaps-upload-help.trycmd
tests/integration/sourcemaps/upload.rs

fix(sourcemaps): Add `.cjs` and `.mjs` to default `sourcemaps upload` extensions

---

src/commands/monitors/mod.rs
tests/integration/_cases/help/help-windows.trycmd
tests/integration/_cases/help/help.trycmd
tests/integration/_cases/monitors/monitors-help.trycmd
tests/integration/_cases/monitors/monitors-no-subcommand.trycmd

ref(crons): Drop beta

---

Makefile

Companion PR for #1993, please see that PR for context!

build: `make lint` only with default features

---

src/api/encoding.rs
src/api/mod.rs

ref(api): `encoding` sub-module

---

src/api/mod.rs
src/api/pagination.rs

ref(api): Split pagination logic into submodule

---

src/api/mod.rs
src/api/pagination.rs

test(api): Add tests for pagination submodule

---

src/api/connection_manager.rs

test(api): Add tests for connection manager

---

src/api/errors/mod.rs
src/api/errors/sentry_error.rs
src/api/mod.rs

ref(api): Sentry error submodule

---

src/api/errors/sentry_error.rs

test(api): Add tests for Sentry error

---

src/api/errors/api_error.rs
src/api/errors/mod.rs
src/api/mod.rs

ref(api): ApiError submodule

---

src/api/mod.rs
src/api/pagination.rs

Revert 29df3e8bd783c98153848849f741cb9dafe4e18f (and also d62d2ec6f7bdfa42f868db41ef71cc45a484d470, which contains tests for 29df3e8bd783c98153848849f741cb9dafe4e18f). These changes, which meant to simplify our pagination logic, appear to have caused several closely-related regressions in Sentry CLI version 2.31.1.
Fixes GH-2053
Potentially fixes (but need to confirm) GH-2052, GH-2054, and GH-2055

fix(releases): Revert pagination refactor

---

src/commands/react_native/xcode.rs

See https://github.com/getsentry/sentry-cli/pull/2057#discussion_r1587694448

fix(xcode): Add back accidentally deleted check

---

Cargo.lock

build: Downgrade `curl-sys`

---

Cargo.lock

build: Upgrade `curl-sys`

---

.github/workflows/build.yml

Reverts getsentry/sentry-cli#2158

Revert "ci: update actions/upload-artifact to v4 with merge"

---

.github/workflows/build.yml

retry of https://github.com/getsentry/sentry-cli/pull/2158 but with a fix for https://github.com/getsentry/craft/issues/557#issuecomment-2383561809
...sorry. At the time I was working through a lot of similar PRs and so missed the discrepancy. 
Now it looks like it's absolutely the expected shape.
```
Archive:  /Users/josh/Downloads/3ff104a3d44ffab72f93cc9246ee8706256a4dba.zip
Length      Date    Time    Name
---------  ---------- -----   ----
7468045  10-01-2024 17:52   darwin/sentry-cli-darwin-2.36.5.tgz
5146352  10-01-2024 17:52   linux-arm/sentry-cli-linux-arm-2.36.5.tgz
5983672  10-01-2024 17:52   linux-arm64/sentry-cli-linux-arm64-2.36.5.tgz
5704226  10-01-2024 17:52   linux-i686/sentry-cli-linux-i686-2.36.5.tgz
5964322  10-01-2024 17:52   linux-x64/sentry-cli-linux-x64-2.36.5.tgz …
```

fix(ci): upload-artifact v4 retry

---

tests/integration/_cases/monitors/monitors-run-token-auth-win.trycmd
tests/integration/_cases/monitors/monitors-run-token-auth.trycmd
tests/integration/monitors/run.rs

We don't need to test unsupported features

test(monitors): Delete unneeded monitors test

---

tests/integration/test_utils/mocking.rs

Instead of using this struct to store options for the endpoint, which then manually need to be checked in the `mock_endpoint` method, convert the struct into a builder which constructs the mock with the provided configuration.
This will make `EndpointOptions` more flexible, allowing us to expand it with new features, and this also reduces branching.
Keeping `EndpointOptions` around, rather than simply calling `mockito` methods directly, will make it easier to handle any breaking changes to the `mockito` library, such as the ones that will occur when implementing #2223

ref(test): Refactor `EndpointOptions`

---

src/utils/fs.rs

fix(chunking): Remove power-of-two chunk size restriction

---

src/utils/dif_upload/error.rs
src/utils/dif_upload/mod.rs

This will make redundant the existing warning in the funciton used to validate a DIF's size, allowing us to delete that warning. This change will help make the code more readable and maintainable.
Depends on:
- #2329

ref(dif): Handle "too big" error with warning

---

src/api/mod.rs

No result needed here
Ref #2357

ref(api): Make `progress_bar_mode` return `Self`

---

src/commands/react_native/gradle.rs
src/commands/react_native/xcode.rs
src/commands/sourcemaps/upload.rs
src/utils/sourcemaps.rs

ref(sourcemaps): Fix `unnecessary_wraps` for `add_debug_id_references`

---

LICENSE

meta: Update LICENSE

---

.github/workflows/build.yml

Also, use v6 of build push action

ci(docker): Enable caching of Docker builds

---

src/utils/mobile_app/validation.rs

See https://github.com/getsentry/sentry-cli/pull/2531/files#r2125991193

ref(mobile-app): `&[u8]` instead of `&ByteView`

---

src/commands/mobile_app/upload.rs

Add basic debug logging to the mobile-app command.

ref(mobile-app): Add debug logging to mobile-app command

---

src/commands/bash_hook.rs
src/commands/login.rs
src/commands/react_native/gradle.rs
src/commands/react_native/xcode.rs
src/commands/sourcemaps/resolve.rs
src/config.rs
src/utils/dif_upload/error.rs
src/utils/file_upload.rs
src/utils/sourcemaps/inject.rs
src/utils/system.rs
tests/integration/test_utils/mock_common_endpoints.rs

Latest clippy stable version was released yesterday: https://forge.rust-lang.org/
Introduces new clippy lints which this fixes using `cargo clippy --fix`

chore: Fix latest clippy lints

---

.github/CODEOWNERS

meta: Add `@getsentry/owners-sentry-cli` to CODEOWNERS

---

.gitignore

Git-ignores jetbrains IDE settings folders

chore: Add `.idea` to gitignore

---

.github/workflows/audit.yml

Add a weekly action, which will create issues if any security vulnerabilities are detected in our dependencies.
Action was adopted from [`sentry-rust`](https://github.com/getsentry/sentry-rust/blob/9ba9a6452df7b8e828030f4d91ebd0c6664b6707/.github/workflows/weekly.yml#L33-L43)
Fixes #2567
Fixes CLI-119

ci: Add action to audit Rust dependencies
